  INFO root [0x00003144] [2018-08-06 09:41:21,380] - 
  INFO root [0x00003144] [2018-08-06 09:41:21,384] - -----------------------------------------------------------------------------------------


  INFO root [0x00003144] [2018-08-06 09:41:21,390] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003144] [2018-08-06 09:41:21,390] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00003144] [2018-08-06 09:41:21,391] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003144] [2018-08-06 09:41:21,405] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00003144] [2018-08-06 09:41:21,432] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00003144] [2018-08-06 09:41:21,450] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:5552 )
  INFO root [0x00003144] [2018-08-06 09:41:21,450] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:5552, SOMAXCONN=128.
  INFO root [0x00003144] [2018-08-06 09:41:21,451] - server-configs:
  INFO root [0x00003144] [2018-08-06 09:41:21,451] - 	gameUpdateHertz : 10
  INFO root [0x00003144] [2018-08-06 09:41:21,451] - 	entryScriptFile : kbemain
  INFO root [0x00003144] [2018-08-06 09:41:21,451] - 	internalAddr : 10.139.66.192:5552
  INFO root [0x00003144] [2018-08-06 09:41:21,451] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00003144] [2018-08-06 09:41:21,451] - 	componentID : 7001
  INFO root [0x00003144] [2018-08-06 09:41:21,651] - Components::findLogger: found logger, addr:10.139.66.192:5503
  INFO root [0x00003144] [2018-08-06 09:41:21,651] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00003144] [2018-08-06 09:41:21,652] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003144] [2018-08-06 09:41:21,674] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 6880 ----
  INFO root [0x00003144] [2018-08-06 09:41:21,675] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00003144] [2018-08-06 09:41:21,675] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003144] [2018-08-06 09:41:21,676] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003144] [2018-08-06 09:41:21,825] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003144] [2018-08-06 09:41:21,826] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003144] [2018-08-06 09:41:21,826] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003144] [2018-08-06 09:41:21,830] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003144] [2018-08-06 09:41:21,831] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003144] [2018-08-06 09:41:21,831] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003144] [2018-08-06 09:41:21,831] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003144] [2018-08-06 09:41:21,886] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003144] [2018-08-06 09:41:21,939] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00003144] [2018-08-06 09:41:21,940] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003144] [2018-08-06 09:41:22,427] - loaded entity-script:Account(1).
 DEBUG root [0x00003144] [2018-08-06 09:41:22,461] - loaded entity-script:Avatar(2).
 DEBUG root [0x00003144] [2018-08-06 09:41:22,674] - loaded entity-script:Spaces(3).
 DEBUG root [0x00003144] [2018-08-06 09:41:22,680] - loaded entity-script:Space(4).
 DEBUG root [0x00003144] [2018-08-06 09:41:23,071] - loaded entity-script:Equipment(5).
 DEBUG root [0x00003144] [2018-08-06 09:41:23,099] - loaded entity-script:Chat(6).
  INFO root [0x00003144] [2018-08-06 09:41:23,100] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003144] [2018-08-06 09:41:23,100] - TelnetServer server is running on port 40000
  INFO root [0x00003144] [2018-08-06 09:41:23,815] - ---- baseapp is running ----
 DEBUG root [0x00003144] [2018-08-06 09:41:23,815] - Components::process(): Request for the process of identity...
  WARN root [0x00003144] [2018-08-06 09:41:30,147] - Forwarding logs to logger[10.139.66.192:5503/0/0/0]...
 ERROR root [0x00003144] [2018-08-06 09:41:46,516] - Space::createCellEntityInNewSpace: cannot find the cellapp script(Space)!
 ERROR root [0x00003144] [2018-08-06 09:41:47,516] - Space::createCellEntityInNewSpace: cannot find the cellapp script(Space)!
 ERROR root [0x00003144] [2018-08-06 09:41:48,517] - Space::createCellEntityInNewSpace: cannot find the cellapp script(Space)!
 ERROR root [0x00003144] [2018-08-06 09:41:49,520] - Space::createCellEntityInNewSpace: cannot find the cellapp script(Space)!
 ERROR root [0x00003144] [2018-08-06 09:41:51,515] - Space::createCellEntityInNewSpace: cannot find the cellapp script(Space)!
 ERROR root [0x00003144] [2018-08-06 09:41:52,516] - Space::createCellEntityInNewSpace: cannot find the cellapp script(Space)!
 ERROR root [0x00003144] [2018-08-06 09:43:16,949] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003144] [2018-08-06 09:43:16,968] - The following logs sent to logger failed:
  WARN root [0x00003144] [2018-08-06 09:43:16,968] - ==> [2018-08-06 09:43:16 948] TCPPacketReceiver::processPendingEvents(10.139.66.192:5503): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003144] [2018-08-06 09:43:16,969] - ==> [2018-08-06 09:43:16 950] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003144] [2018-08-06 09:43:17,091] - TCPPacketReceiver::processPendingEvents(10.139.66.192:5521): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003144] [2018-08-06 09:43:17,095] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003144] [2018-08-06 09:43:17,102] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003144] [2018-08-06 09:43:17,113] - onBaseAppShutDown: state=0
  INFO root [0x00003144] [2018-08-06 09:43:17,114] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003144] [2018-08-06 09:43:17,114] - onBaseAppShutDown: state=1
  INFO root [0x00003144] [2018-08-06 09:43:17,114] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003144] [2018-08-06 09:43:17,115] - onBaseAppShutDown: state=2
 DEBUG root [0x00003144] [2018-08-06 09:43:17,133] - Space::~Space(): 4
 DEBUG root [0x00003144] [2018-08-06 09:43:17,133] - Space::~Space(): 5
 DEBUG root [0x00003144] [2018-08-06 09:43:17,133] - Space::~Space(): 6
 DEBUG root [0x00003144] [2018-08-06 09:43:17,134] - Space::~Space(): 7
 DEBUG root [0x00003144] [2018-08-06 09:43:17,134] - Space::~Space(): 8
 DEBUG root [0x00003144] [2018-08-06 09:43:17,134] - Space::~Space(): 9
 DEBUG root [0x00003144] [2018-08-06 09:43:17,134] - Spaces::~Spaces(): 3
 DEBUG root [0x00003144] [2018-08-06 09:43:17,134] - Chat::~Chat(): 2
 DEBUG root [0x00003144] [2018-08-06 09:43:17,136] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003144] [2018-08-06 09:43:17,137] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003144] [2018-08-06 09:43:17,137] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003144] [2018-08-06 09:43:17,137] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003144] [2018-08-06 09:43:17,137] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003144] [2018-08-06 09:43:17,138] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003144] [2018-08-06 09:43:17,138] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003144] [2018-08-06 09:43:17,138] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003144] [2018-08-06 09:43:17,156] - Script::uninstall(): is successfully!
 DEBUG root [0x00003144] [2018-08-06 09:43:17,156] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003144] [2018-08-06 09:43:17,457] - ThreadPool::destroy(): waiting for thread(2)[0x1cd0b10,0x1cd0a40,], try=1
  INFO root [0x00001f2c] [2018-08-06 09:43:21,888] - 
  INFO root [0x00001f2c] [2018-08-06 09:43:21,889] - -----------------------------------------------------------------------------------------


  INFO root [0x00001f2c] [2018-08-06 09:43:21,890] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001f2c] [2018-08-06 09:43:21,891] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00001f2c] [2018-08-06 09:43:21,891] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001f2c] [2018-08-06 09:43:21,903] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00001f2c] [2018-08-06 09:43:21,903] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00001f2c] [2018-08-06 09:43:21,924] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:6022 )
  INFO root [0x00001f2c] [2018-08-06 09:43:21,925] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:6022, SOMAXCONN=128.
  INFO root [0x00001f2c] [2018-08-06 09:43:21,925] - server-configs:
  INFO root [0x00001f2c] [2018-08-06 09:43:21,925] - 	gameUpdateHertz : 10
  INFO root [0x00001f2c] [2018-08-06 09:43:21,925] - 	entryScriptFile : kbemain
  INFO root [0x00001f2c] [2018-08-06 09:43:21,926] - 	internalAddr : 10.139.66.192:6022
  INFO root [0x00001f2c] [2018-08-06 09:43:21,926] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00001f2c] [2018-08-06 09:43:21,926] - 	componentID : 7001
  INFO root [0x00001f2c] [2018-08-06 09:43:22,204] - Components::findLogger: found logger, addr:10.139.66.192:6000
  INFO root [0x00001f2c] [2018-08-06 09:43:22,205] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00001f2c] [2018-08-06 09:43:22,205] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001f2c] [2018-08-06 09:43:22,223] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 8032 ----
  INFO root [0x00001f2c] [2018-08-06 09:43:22,224] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00001f2c] [2018-08-06 09:43:22,224] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001f2c] [2018-08-06 09:43:22,225] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,378] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,378] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,379] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,385] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,385] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,385] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,386] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,460] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f2c] [2018-08-06 09:43:22,512] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00001f2c] [2018-08-06 09:43:22,512] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,557] - loaded entity-script:Account(1).
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,569] - loaded entity-script:Avatar(2).
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,582] - loaded entity-script:Spaces(3).
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,589] - loaded entity-script:Space(4).
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,603] - loaded entity-script:Equipment(5).
 DEBUG root [0x00001f2c] [2018-08-06 09:43:22,606] - loaded entity-script:Chat(6).
  INFO root [0x00001f2c] [2018-08-06 09:43:22,606] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001f2c] [2018-08-06 09:43:22,607] - TelnetServer server is running on port 40000
  INFO root [0x00001f2c] [2018-08-06 09:43:23,161] - ---- baseapp is running ----
 DEBUG root [0x00001f2c] [2018-08-06 09:43:23,162] - Components::process(): Request for the process of identity...
  WARN root [0x00001f2c] [2018-08-06 09:43:29,435] - Forwarding logs to logger[10.139.66.192:6000/0/0/0]...
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,196] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001f2c] [2018-08-06 09:46:54,202] - The following logs sent to logger failed:
  WARN root [0x00001f2c] [2018-08-06 09:46:54,202] - ==> [2018-08-06 09:46:54 194] TCPPacketReceiver::processPendingEvents(10.139.66.192:6000): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,203] - ==> [2018-08-06 09:46:54 197] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001f2c] [2018-08-06 09:46:54,359] - TCPPacketReceiver::processPendingEvents(10.139.66.192:6002): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,362] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001f2c] [2018-08-06 09:46:54,377] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001f2c] [2018-08-06 09:46:54,385] - onBaseAppShutDown: state=0
  INFO root [0x00001f2c] [2018-08-06 09:46:54,386] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001f2c] [2018-08-06 09:46:54,386] - onBaseAppShutDown: state=1
  INFO root [0x00001f2c] [2018-08-06 09:46:54,386] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001f2c] [2018-08-06 09:46:54,386] - onBaseAppShutDown: state=2
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,412] - Account::onCellWriteToDBCompleted(10): not found dbmgr!
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,416] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,419] - Avatar::onCellWriteToDBCompleted(11): not found dbmgr!
 ERROR root [0x00001f2c] [2018-08-06 09:46:54,422] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,422] - Account::~Account(): 10
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,422] - Space::~Space(): 4
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,423] - Space::~Space(): 5
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,423] - Space::~Space(): 6
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,423] - Space::~Space(): 7
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,423] - Space::~Space(): 8
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,424] - Space::~Space(): 9
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,424] - Avatar::~Avatar(): 11
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,425] - Spaces::~Spaces(): 3
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,425] - Chat::~Chat(): 2
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,427] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,427] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,428] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,428] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,428] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,428] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,428] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,428] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f2c] [2018-08-06 09:46:54,453] - Script::uninstall(): is successfully!
 DEBUG root [0x00001f2c] [2018-08-06 09:46:54,453] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001f2c] [2018-08-06 09:46:54,755] - ThreadPool::destroy(): waiting for thread(2)[0x1a87380,0x1a87658,], try=1
  INFO root [0x000021c0] [2018-08-06 09:46:57,450] - 
  INFO root [0x000021c0] [2018-08-06 09:46:57,450] - -----------------------------------------------------------------------------------------


  INFO root [0x000021c0] [2018-08-06 09:46:57,451] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000021c0] [2018-08-06 09:46:57,452] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x000021c0] [2018-08-06 09:46:57,452] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000021c0] [2018-08-06 09:46:57,459] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x000021c0] [2018-08-06 09:46:57,469] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x000021c0] [2018-08-06 09:46:57,486] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:6745 )
  INFO root [0x000021c0] [2018-08-06 09:46:57,486] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:6745, SOMAXCONN=128.
  INFO root [0x000021c0] [2018-08-06 09:46:57,486] - server-configs:
  INFO root [0x000021c0] [2018-08-06 09:46:57,487] - 	gameUpdateHertz : 10
  INFO root [0x000021c0] [2018-08-06 09:46:57,487] - 	entryScriptFile : kbemain
  INFO root [0x000021c0] [2018-08-06 09:46:57,487] - 	internalAddr : 10.139.66.192:6745
  INFO root [0x000021c0] [2018-08-06 09:46:57,487] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x000021c0] [2018-08-06 09:46:57,487] - 	componentID : 7001
  INFO root [0x000021c0] [2018-08-06 09:46:57,911] - Components::findLogger: found logger, addr:10.139.66.192:6739
  INFO root [0x000021c0] [2018-08-06 09:46:57,911] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000021c0] [2018-08-06 09:46:57,911] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000021c0] [2018-08-06 09:46:57,939] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 11084 ----
  INFO root [0x000021c0] [2018-08-06 09:46:57,941] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x000021c0] [2018-08-06 09:46:57,943] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000021c0] [2018-08-06 09:46:57,944] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,105] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,106] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,107] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,111] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,111] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,111] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,112] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,192] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000021c0] [2018-08-06 09:46:58,277] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x000021c0] [2018-08-06 09:46:58,277] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,371] - loaded entity-script:Account(1).
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,378] - loaded entity-script:Avatar(2).
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,410] - loaded entity-script:Spaces(3).
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,414] - loaded entity-script:Space(4).
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,436] - loaded entity-script:Equipment(5).
 DEBUG root [0x000021c0] [2018-08-06 09:46:58,440] - loaded entity-script:Chat(6).
  INFO root [0x000021c0] [2018-08-06 09:46:58,441] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000021c0] [2018-08-06 09:46:58,441] - TelnetServer server is running on port 40000
  INFO root [0x000021c0] [2018-08-06 09:46:59,510] - ---- baseapp is running ----
 DEBUG root [0x000021c0] [2018-08-06 09:46:59,511] - Components::process(): Request for the process of identity...
  WARN root [0x000021c0] [2018-08-06 09:47:03,125] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20086, errorno=10048
  WARN root [0x000021c0] [2018-08-06 09:47:06,206] - Forwarding logs to logger[10.139.66.192:6739/0/0/0]...
 ERROR root [0x000021c0] [2018-08-06 10:00:34,567] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000021c0] [2018-08-06 10:00:34,572] - The following logs sent to logger failed:
  WARN root [0x000021c0] [2018-08-06 10:00:34,572] - ==> [2018-08-06 10:00:34 567] TCPPacketReceiver::processPendingEvents(10.139.66.192:6739): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000021c0] [2018-08-06 10:00:34,573] - ==> [2018-08-06 10:00:34 568] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000021c0] [2018-08-06 10:00:34,713] - TCPPacketReceiver::processPendingEvents(10.139.66.192:6740): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000021c0] [2018-08-06 10:00:34,715] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000021c0] [2018-08-06 10:00:34,717] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000021c0] [2018-08-06 10:00:34,717] - onBaseAppShutDown: state=0
  INFO root [0x000021c0] [2018-08-06 10:00:34,718] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000021c0] [2018-08-06 10:00:34,718] - onBaseAppShutDown: state=1
  INFO root [0x000021c0] [2018-08-06 10:00:34,718] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000021c0] [2018-08-06 10:00:34,718] - onBaseAppShutDown: state=2
 ERROR root [0x000021c0] [2018-08-06 10:00:34,741] - Avatar::onCellWriteToDBCompleted(2011): not found dbmgr!
 ERROR root [0x000021c0] [2018-08-06 10:00:34,741] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,742] - Space::~Space(): 2004
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,742] - Space::~Space(): 2005
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,742] - Space::~Space(): 2006
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,743] - Space::~Space(): 2007
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,743] - Space::~Space(): 2008
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,743] - Space::~Space(): 2009
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,743] - Avatar::~Avatar(): 2011
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,744] - Spaces::~Spaces(): 2003
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,744] - Chat::~Chat(): 2002
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,745] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,745] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,745] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,746] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,746] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,746] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,746] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,746] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000021c0] [2018-08-06 10:00:34,765] - Script::uninstall(): is successfully!
 DEBUG root [0x000021c0] [2018-08-06 10:00:34,765] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000021c0] [2018-08-06 10:00:35,065] - ThreadPool::destroy(): waiting for thread(2)[0x1ca61a8,0x1ca6210,], try=1
  INFO root [0x00002afc] [2018-08-06 10:00:37,598] - 
  INFO root [0x00002afc] [2018-08-06 10:00:37,598] - -----------------------------------------------------------------------------------------


  INFO root [0x00002afc] [2018-08-06 10:00:37,599] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002afc] [2018-08-06 10:00:37,600] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00002afc] [2018-08-06 10:00:37,600] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002afc] [2018-08-06 10:00:37,607] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00002afc] [2018-08-06 10:00:37,608] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00002afc] [2018-08-06 10:00:37,624] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:9555 )
  INFO root [0x00002afc] [2018-08-06 10:00:37,624] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:9555, SOMAXCONN=128.
  INFO root [0x00002afc] [2018-08-06 10:00:37,624] - server-configs:
  INFO root [0x00002afc] [2018-08-06 10:00:37,624] - 	gameUpdateHertz : 10
  INFO root [0x00002afc] [2018-08-06 10:00:37,624] - 	entryScriptFile : kbemain
  INFO root [0x00002afc] [2018-08-06 10:00:37,624] - 	internalAddr : 10.139.66.192:9555
  INFO root [0x00002afc] [2018-08-06 10:00:37,625] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00002afc] [2018-08-06 10:00:37,625] - 	componentID : 7001
  INFO root [0x00002afc] [2018-08-06 10:00:38,047] - Components::findLogger: found logger, addr:10.139.66.192:9550
  INFO root [0x00002afc] [2018-08-06 10:00:38,048] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00002afc] [2018-08-06 10:00:38,048] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002afc] [2018-08-06 10:00:38,068] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 8324 ----
  INFO root [0x00002afc] [2018-08-06 10:00:38,070] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00002afc] [2018-08-06 10:00:38,073] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002afc] [2018-08-06 10:00:38,073] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,240] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,241] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,241] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,247] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,248] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,248] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,249] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,329] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002afc] [2018-08-06 10:00:38,388] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00002afc] [2018-08-06 10:00:38,388] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,446] - loaded entity-script:Account(1).
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,452] - loaded entity-script:Avatar(2).
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,464] - loaded entity-script:Spaces(3).
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,466] - loaded entity-script:Space(4).
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,482] - loaded entity-script:Equipment(5).
 DEBUG root [0x00002afc] [2018-08-06 10:00:38,485] - loaded entity-script:Chat(6).
  INFO root [0x00002afc] [2018-08-06 10:00:38,485] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002afc] [2018-08-06 10:00:38,486] - TelnetServer server is running on port 40000
  INFO root [0x00002afc] [2018-08-06 10:00:39,115] - ---- baseapp is running ----
 DEBUG root [0x00002afc] [2018-08-06 10:00:39,115] - Components::process(): Request for the process of identity...
  WARN root [0x00002afc] [2018-08-06 10:00:45,370] - Forwarding logs to logger[10.139.66.192:9550/0/0/0]...
 ERROR root [0x00002afc] [2018-08-06 10:01:45,904] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002afc] [2018-08-06 10:01:45,906] - The following logs sent to logger failed:
  WARN root [0x00002afc] [2018-08-06 10:01:45,907] - ==> [2018-08-06 10:01:45 904] TCPPacketReceiver::processPendingEvents(10.139.66.192:9550): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002afc] [2018-08-06 10:01:45,907] - ==> [2018-08-06 10:01:45 906] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002afc] [2018-08-06 10:01:46,042] - TCPPacketReceiver::processPendingEvents(10.139.66.192:9551): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002afc] [2018-08-06 10:01:46,042] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002afc] [2018-08-06 10:01:46,052] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002afc] [2018-08-06 10:01:46,065] - onBaseAppShutDown: state=0
  INFO root [0x00002afc] [2018-08-06 10:01:46,066] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002afc] [2018-08-06 10:01:46,066] - onBaseAppShutDown: state=1
  INFO root [0x00002afc] [2018-08-06 10:01:46,067] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002afc] [2018-08-06 10:01:46,067] - onBaseAppShutDown: state=2
 ERROR root [0x00002afc] [2018-08-06 10:01:46,092] - Avatar::onCellWriteToDBCompleted(2011): not found dbmgr!
 ERROR root [0x00002afc] [2018-08-06 10:01:46,094] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,101] - Space::~Space(): 2004
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,102] - Space::~Space(): 2005
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,102] - Space::~Space(): 2006
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,102] - Space::~Space(): 2007
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,102] - Space::~Space(): 2008
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,103] - Space::~Space(): 2009
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,103] - Avatar::~Avatar(): 2011
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,103] - Spaces::~Spaces(): 2003
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,104] - Chat::~Chat(): 2002
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,105] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,106] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,106] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,106] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,106] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,106] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,107] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,107] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002afc] [2018-08-06 10:01:46,128] - Script::uninstall(): is successfully!
 DEBUG root [0x00002afc] [2018-08-06 10:01:46,129] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00002afc] [2018-08-06 10:01:46,430] - ThreadPool::destroy(): waiting for thread(2)[0x1a51b10,0x1a519d8,], try=1
  INFO root [0x0000148c] [2018-08-06 10:01:48,828] - 
  INFO root [0x0000148c] [2018-08-06 10:01:48,829] - -----------------------------------------------------------------------------------------


  INFO root [0x0000148c] [2018-08-06 10:01:48,831] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x0000148c] [2018-08-06 10:01:48,832] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x0000148c] [2018-08-06 10:01:48,832] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x0000148c] [2018-08-06 10:01:48,841] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x0000148c] [2018-08-06 10:01:48,841] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x0000148c] [2018-08-06 10:01:48,861] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:9831 )
  INFO root [0x0000148c] [2018-08-06 10:01:48,862] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:9831, SOMAXCONN=128.
  INFO root [0x0000148c] [2018-08-06 10:01:48,862] - server-configs:
  INFO root [0x0000148c] [2018-08-06 10:01:48,862] - 	gameUpdateHertz : 10
  INFO root [0x0000148c] [2018-08-06 10:01:48,862] - 	entryScriptFile : kbemain
  INFO root [0x0000148c] [2018-08-06 10:01:48,863] - 	internalAddr : 10.139.66.192:9831
  INFO root [0x0000148c] [2018-08-06 10:01:48,865] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x0000148c] [2018-08-06 10:01:48,866] - 	componentID : 7001
  INFO root [0x0000148c] [2018-08-06 10:01:49,405] - Components::findLogger: found logger, addr:10.139.66.192:9825
  INFO root [0x0000148c] [2018-08-06 10:01:49,406] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x0000148c] [2018-08-06 10:01:49,406] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000148c] [2018-08-06 10:01:49,427] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 5128 ----
  INFO root [0x0000148c] [2018-08-06 10:01:49,428] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x0000148c] [2018-08-06 10:01:49,428] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000148c] [2018-08-06 10:01:49,429] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,603] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,603] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,604] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,609] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,609] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,609] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,610] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,688] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000148c] [2018-08-06 10:01:49,781] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x0000148c] [2018-08-06 10:01:49,781] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,859] - loaded entity-script:Account(1).
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,862] - loaded entity-script:Avatar(2).
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,878] - loaded entity-script:Spaces(3).
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,882] - loaded entity-script:Space(4).
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,897] - loaded entity-script:Equipment(5).
 DEBUG root [0x0000148c] [2018-08-06 10:01:49,899] - loaded entity-script:Chat(6).
  INFO root [0x0000148c] [2018-08-06 10:01:49,900] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000148c] [2018-08-06 10:01:49,900] - TelnetServer server is running on port 40000
  INFO root [0x0000148c] [2018-08-06 10:01:50,810] - ---- baseapp is running ----
 DEBUG root [0x0000148c] [2018-08-06 10:01:50,811] - Components::process(): Request for the process of identity...
  WARN root [0x0000148c] [2018-08-06 10:01:57,098] - Forwarding logs to logger[10.139.66.192:9825/0/0/0]...
 ERROR root [0x0000148c] [2018-08-06 10:03:15,463] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000148c] [2018-08-06 10:03:15,465] - The following logs sent to logger failed:
  WARN root [0x0000148c] [2018-08-06 10:03:15,465] - ==> [2018-08-06 10:03:15 460] TCPPacketReceiver::processPendingEvents(10.139.66.192:9825): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000148c] [2018-08-06 10:03:15,466] - ==> [2018-08-06 10:03:15 464] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000148c] [2018-08-06 10:03:15,621] - TCPPacketReceiver::processPendingEvents(10.139.66.192:9826): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000148c] [2018-08-06 10:03:15,621] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000148c] [2018-08-06 10:03:15,641] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000148c] [2018-08-06 10:03:15,648] - onBaseAppShutDown: state=0
  INFO root [0x0000148c] [2018-08-06 10:03:15,648] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000148c] [2018-08-06 10:03:15,648] - onBaseAppShutDown: state=1
  INFO root [0x0000148c] [2018-08-06 10:03:15,649] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000148c] [2018-08-06 10:03:15,649] - onBaseAppShutDown: state=2
 ERROR root [0x0000148c] [2018-08-06 10:03:15,673] - Avatar::onCellWriteToDBCompleted(2011): not found dbmgr!
 ERROR root [0x0000148c] [2018-08-06 10:03:15,677] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,682] - Space::~Space(): 2004
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,683] - Space::~Space(): 2005
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,683] - Space::~Space(): 2006
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,683] - Space::~Space(): 2007
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,683] - Space::~Space(): 2008
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,683] - Space::~Space(): 2009
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,684] - Avatar::~Avatar(): 2011
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,684] - Chat::~Chat(): 2002
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,684] - Spaces::~Spaces(): 2003
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,686] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,686] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,687] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,687] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,687] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,687] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,687] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,688] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000148c] [2018-08-06 10:03:15,708] - Script::uninstall(): is successfully!
 DEBUG root [0x0000148c] [2018-08-06 10:03:15,708] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000148c] [2018-08-06 10:03:16,009] - ThreadPool::destroy(): waiting for thread(2)[0x1c5d468,0x1c5dae8,], try=1
  INFO root [0x00002ad4] [2018-08-06 10:03:18,359] - 
  INFO root [0x00002ad4] [2018-08-06 10:03:18,360] - -----------------------------------------------------------------------------------------


  INFO root [0x00002ad4] [2018-08-06 10:03:18,362] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002ad4] [2018-08-06 10:03:18,362] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00002ad4] [2018-08-06 10:03:18,362] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002ad4] [2018-08-06 10:03:18,371] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00002ad4] [2018-08-06 10:03:18,372] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00002ad4] [2018-08-06 10:03:18,388] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:10177 )
  INFO root [0x00002ad4] [2018-08-06 10:03:18,389] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:10177, SOMAXCONN=128.
  INFO root [0x00002ad4] [2018-08-06 10:03:18,389] - server-configs:
  INFO root [0x00002ad4] [2018-08-06 10:03:18,390] - 	gameUpdateHertz : 10
  INFO root [0x00002ad4] [2018-08-06 10:03:18,390] - 	entryScriptFile : kbemain
  INFO root [0x00002ad4] [2018-08-06 10:03:18,390] - 	internalAddr : 10.139.66.192:10177
  INFO root [0x00002ad4] [2018-08-06 10:03:18,390] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00002ad4] [2018-08-06 10:03:18,390] - 	componentID : 7001
  INFO root [0x00002ad4] [2018-08-06 10:03:18,815] - Components::findLogger: found logger, addr:10.139.66.192:10172
  INFO root [0x00002ad4] [2018-08-06 10:03:18,815] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00002ad4] [2018-08-06 10:03:18,816] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ad4] [2018-08-06 10:03:18,837] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 5920 ----
  INFO root [0x00002ad4] [2018-08-06 10:03:18,838] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00002ad4] [2018-08-06 10:03:18,838] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002ad4] [2018-08-06 10:03:18,839] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002ad4] [2018-08-06 10:03:18,999] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,000] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,001] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,006] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,007] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,007] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,008] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,083] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002ad4] [2018-08-06 10:03:19,152] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00002ad4] [2018-08-06 10:03:19,153] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,220] - loaded entity-script:Account(1).
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,223] - loaded entity-script:Avatar(2).
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,241] - loaded entity-script:Spaces(3).
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,244] - loaded entity-script:Space(4).
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,262] - loaded entity-script:Equipment(5).
 DEBUG root [0x00002ad4] [2018-08-06 10:03:19,266] - loaded entity-script:Chat(6).
  INFO root [0x00002ad4] [2018-08-06 10:03:19,267] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002ad4] [2018-08-06 10:03:19,268] - TelnetServer server is running on port 40000
  INFO root [0x00002ad4] [2018-08-06 10:03:20,027] - ---- baseapp is running ----
 DEBUG root [0x00002ad4] [2018-08-06 10:03:20,028] - Components::process(): Request for the process of identity...
  WARN root [0x00002ad4] [2018-08-06 10:03:23,566] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20520, errorno=10048
  WARN root [0x00002ad4] [2018-08-06 10:03:23,911] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20643, errorno=10048
  WARN root [0x00002ad4] [2018-08-06 10:03:26,984] - Forwarding logs to logger[10.139.66.192:10172/0/0/0]...
 ERROR root [0x00002ad4] [2018-08-06 10:05:24,954] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002ad4] [2018-08-06 10:05:24,959] - The following logs sent to logger failed:
  WARN root [0x00002ad4] [2018-08-06 10:05:24,960] - ==> [2018-08-06 10:05:24 954] TCPPacketReceiver::processPendingEvents(10.139.66.192:10172): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ad4] [2018-08-06 10:05:24,960] - ==> [2018-08-06 10:05:24 956] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002ad4] [2018-08-06 10:05:25,094] - TCPPacketReceiver::processPendingEvents(10.139.66.192:10173): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ad4] [2018-08-06 10:05:25,097] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002ad4] [2018-08-06 10:05:25,100] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002ad4] [2018-08-06 10:05:25,106] - onBaseAppShutDown: state=0
  INFO root [0x00002ad4] [2018-08-06 10:05:25,107] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002ad4] [2018-08-06 10:05:25,107] - onBaseAppShutDown: state=1
  INFO root [0x00002ad4] [2018-08-06 10:05:25,107] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002ad4] [2018-08-06 10:05:25,107] - onBaseAppShutDown: state=2
 ERROR root [0x00002ad4] [2018-08-06 10:05:25,133] - Account::onCellWriteToDBCompleted(2010): not found dbmgr!
 ERROR root [0x00002ad4] [2018-08-06 10:05:25,135] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002ad4] [2018-08-06 10:05:25,137] - Avatar::onCellWriteToDBCompleted(2011): not found dbmgr!
 ERROR root [0x00002ad4] [2018-08-06 10:05:25,141] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,143] - Account::~Account(): 2010
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,144] - Space::~Space(): 2004
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,144] - Space::~Space(): 2005
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,144] - Space::~Space(): 2006
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,144] - Space::~Space(): 2007
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,144] - Space::~Space(): 2008
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,145] - Space::~Space(): 2009
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,145] - Avatar::~Avatar(): 2011
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,145] - Chat::~Chat(): 2002
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,146] - Spaces::~Spaces(): 2003
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,148] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,148] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,148] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,149] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,149] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,149] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,149] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,149] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002ad4] [2018-08-06 10:05:25,165] - Script::uninstall(): is successfully!
 DEBUG root [0x00002ad4] [2018-08-06 10:05:25,166] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00002ad4] [2018-08-06 10:05:25,467] - ThreadPool::destroy(): waiting for thread(2)[0x1b78c30,0x1b784e0,], try=1
  INFO root [0x00003198] [2018-08-06 10:05:27,924] - 
  INFO root [0x00003198] [2018-08-06 10:05:27,925] - -----------------------------------------------------------------------------------------


  INFO root [0x00003198] [2018-08-06 10:05:27,927] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003198] [2018-08-06 10:05:27,927] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00003198] [2018-08-06 10:05:27,928] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003198] [2018-08-06 10:05:27,942] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00003198] [2018-08-06 10:05:27,943] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00003198] [2018-08-06 10:05:27,974] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:10655 )
  INFO root [0x00003198] [2018-08-06 10:05:27,975] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:10655, SOMAXCONN=128.
  INFO root [0x00003198] [2018-08-06 10:05:27,975] - server-configs:
  INFO root [0x00003198] [2018-08-06 10:05:27,975] - 	gameUpdateHertz : 10
  INFO root [0x00003198] [2018-08-06 10:05:27,977] - 	entryScriptFile : kbemain
  INFO root [0x00003198] [2018-08-06 10:05:27,977] - 	internalAddr : 10.139.66.192:10655
  INFO root [0x00003198] [2018-08-06 10:05:27,977] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00003198] [2018-08-06 10:05:27,978] - 	componentID : 7001
  INFO root [0x00003198] [2018-08-06 10:05:28,595] - Components::findLogger: found logger, addr:10.139.66.192:10649
  INFO root [0x00003198] [2018-08-06 10:05:28,595] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00003198] [2018-08-06 10:05:28,596] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003198] [2018-08-06 10:05:28,615] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 12272 ----
  INFO root [0x00003198] [2018-08-06 10:05:28,616] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00003198] [2018-08-06 10:05:28,616] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003198] [2018-08-06 10:05:28,617] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003198] [2018-08-06 10:05:28,769] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003198] [2018-08-06 10:05:28,770] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003198] [2018-08-06 10:05:28,771] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003198] [2018-08-06 10:05:28,775] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003198] [2018-08-06 10:05:28,775] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003198] [2018-08-06 10:05:28,775] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003198] [2018-08-06 10:05:28,776] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003198] [2018-08-06 10:05:28,847] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003198] [2018-08-06 10:05:28,914] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00003198] [2018-08-06 10:05:28,914] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003198] [2018-08-06 10:05:28,959] - loaded entity-script:Account(1).
 DEBUG root [0x00003198] [2018-08-06 10:05:28,962] - loaded entity-script:Avatar(2).
 DEBUG root [0x00003198] [2018-08-06 10:05:28,975] - loaded entity-script:Spaces(3).
 DEBUG root [0x00003198] [2018-08-06 10:05:28,976] - loaded entity-script:Space(4).
 DEBUG root [0x00003198] [2018-08-06 10:05:28,989] - loaded entity-script:Equipment(5).
 DEBUG root [0x00003198] [2018-08-06 10:05:28,991] - loaded entity-script:Chat(6).
  INFO root [0x00003198] [2018-08-06 10:05:28,991] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003198] [2018-08-06 10:05:28,992] - TelnetServer server is running on port 40000
  INFO root [0x00003198] [2018-08-06 10:05:29,630] - ---- baseapp is running ----
 DEBUG root [0x00003198] [2018-08-06 10:05:29,630] - Components::process(): Request for the process of identity...
  WARN root [0x00003198] [2018-08-06 10:05:35,947] - Forwarding logs to logger[10.139.66.192:10649/0/0/0]...
 ERROR root [0x00003198] [2018-08-06 10:12:06,126] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003198] [2018-08-06 10:12:06,127] - The following logs sent to logger failed:
  WARN root [0x00003198] [2018-08-06 10:12:06,128] - ==> [2018-08-06 10:12:06 126] TCPPacketReceiver::processPendingEvents(10.139.66.192:10649): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003198] [2018-08-06 10:12:06,128] - ==> [2018-08-06 10:12:06 127] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003198] [2018-08-06 10:12:06,277] - TCPPacketReceiver::processPendingEvents(10.139.66.192:10650): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003198] [2018-08-06 10:12:06,287] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003198] [2018-08-06 10:12:06,295] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003198] [2018-08-06 10:12:06,296] - onBaseAppShutDown: state=0
  INFO root [0x00003198] [2018-08-06 10:12:06,297] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003198] [2018-08-06 10:12:06,298] - onBaseAppShutDown: state=1
  INFO root [0x00003198] [2018-08-06 10:12:06,298] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003198] [2018-08-06 10:12:06,299] - onBaseAppShutDown: state=2
 ERROR root [0x00003198] [2018-08-06 10:12:06,326] - Account::onCellWriteToDBCompleted(10): not found dbmgr!
 ERROR root [0x00003198] [2018-08-06 10:12:06,330] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003198] [2018-08-06 10:12:06,333] - Avatar::onCellWriteToDBCompleted(11): not found dbmgr!
 ERROR root [0x00003198] [2018-08-06 10:12:06,336] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003198] [2018-08-06 10:12:06,337] - Account::~Account(): 10
 DEBUG root [0x00003198] [2018-08-06 10:12:06,337] - Space::~Space(): 4
 DEBUG root [0x00003198] [2018-08-06 10:12:06,338] - Space::~Space(): 5
 DEBUG root [0x00003198] [2018-08-06 10:12:06,338] - Space::~Space(): 6
 DEBUG root [0x00003198] [2018-08-06 10:12:06,338] - Space::~Space(): 7
 DEBUG root [0x00003198] [2018-08-06 10:12:06,338] - Space::~Space(): 8
 DEBUG root [0x00003198] [2018-08-06 10:12:06,338] - Space::~Space(): 9
 DEBUG root [0x00003198] [2018-08-06 10:12:06,338] - Avatar::~Avatar(): 11
 DEBUG root [0x00003198] [2018-08-06 10:12:06,339] - Chat::~Chat(): 2
 DEBUG root [0x00003198] [2018-08-06 10:12:06,339] - Spaces::~Spaces(): 3
 DEBUG root [0x00003198] [2018-08-06 10:12:06,340] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003198] [2018-08-06 10:12:06,341] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003198] [2018-08-06 10:12:06,341] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003198] [2018-08-06 10:12:06,341] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003198] [2018-08-06 10:12:06,341] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003198] [2018-08-06 10:12:06,341] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003198] [2018-08-06 10:12:06,341] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003198] [2018-08-06 10:12:06,342] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003198] [2018-08-06 10:12:06,365] - Script::uninstall(): is successfully!
 DEBUG root [0x00003198] [2018-08-06 10:12:06,365] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003198] [2018-08-06 10:12:06,666] - ThreadPool::destroy(): waiting for thread(2)[0x1a89eb8,0x1a89f88,], try=1
  INFO root [0x000035f0] [2018-08-06 10:12:09,926] - 
  INFO root [0x000035f0] [2018-08-06 10:12:09,926] - -----------------------------------------------------------------------------------------


  INFO root [0x000035f0] [2018-08-06 10:12:09,928] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000035f0] [2018-08-06 10:12:09,928] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x000035f0] [2018-08-06 10:12:09,928] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000035f0] [2018-08-06 10:12:09,945] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x000035f0] [2018-08-06 10:12:09,945] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x000035f0] [2018-08-06 10:12:09,962] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:12101 )
  INFO root [0x000035f0] [2018-08-06 10:12:09,962] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:12101, SOMAXCONN=128.
  INFO root [0x000035f0] [2018-08-06 10:12:09,962] - server-configs:
  INFO root [0x000035f0] [2018-08-06 10:12:09,962] - 	gameUpdateHertz : 10
  INFO root [0x000035f0] [2018-08-06 10:12:09,963] - 	entryScriptFile : kbemain
  INFO root [0x000035f0] [2018-08-06 10:12:09,963] - 	internalAddr : 10.139.66.192:12101
  INFO root [0x000035f0] [2018-08-06 10:12:09,963] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x000035f0] [2018-08-06 10:12:09,963] - 	componentID : 7001
  INFO root [0x000035f0] [2018-08-06 10:12:10,369] - Components::findLogger: found logger, addr:10.139.66.192:12093
  INFO root [0x000035f0] [2018-08-06 10:12:10,370] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000035f0] [2018-08-06 10:12:10,370] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000035f0] [2018-08-06 10:12:10,390] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 12876 ----
  INFO root [0x000035f0] [2018-08-06 10:12:10,391] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x000035f0] [2018-08-06 10:12:10,392] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000035f0] [2018-08-06 10:12:10,392] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,553] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,554] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,555] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,560] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,561] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,562] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,565] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,654] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000035f0] [2018-08-06 10:12:10,752] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x000035f0] [2018-08-06 10:12:10,753] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,842] - loaded entity-script:Account(1).
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,845] - loaded entity-script:Avatar(2).
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,862] - loaded entity-script:Spaces(3).
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,871] - loaded entity-script:Space(4).
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,893] - loaded entity-script:Equipment(5).
 DEBUG root [0x000035f0] [2018-08-06 10:12:10,899] - loaded entity-script:Chat(6).
  INFO root [0x000035f0] [2018-08-06 10:12:10,899] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000035f0] [2018-08-06 10:12:10,901] - TelnetServer server is running on port 40000
  INFO root [0x000035f0] [2018-08-06 10:12:11,889] - ---- baseapp is running ----
 DEBUG root [0x000035f0] [2018-08-06 10:12:11,890] - Components::process(): Request for the process of identity...
  WARN root [0x000035f0] [2018-08-06 10:12:12,224] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20184, errorno=10048
  WARN root [0x000035f0] [2018-08-06 10:12:18,557] - Forwarding logs to logger[10.139.66.192:12093/0/0/0]...
 ERROR root [0x000035f0] [2018-08-06 10:21:58,928] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000035f0] [2018-08-06 10:21:58,931] - The following logs sent to logger failed:
  WARN root [0x000035f0] [2018-08-06 10:21:58,931] - ==> [2018-08-06 10:21:58 928] TCPPacketReceiver::processPendingEvents(10.139.66.192:12093): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000035f0] [2018-08-06 10:21:58,931] - ==> [2018-08-06 10:21:58 929] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000035f0] [2018-08-06 10:21:59,033] - TCPPacketReceiver::processPendingEvents(10.139.66.192:12096): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000035f0] [2018-08-06 10:21:59,037] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000035f0] [2018-08-06 10:21:59,038] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000035f0] [2018-08-06 10:21:59,040] - onBaseAppShutDown: state=0
  INFO root [0x000035f0] [2018-08-06 10:21:59,040] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000035f0] [2018-08-06 10:21:59,040] - onBaseAppShutDown: state=1
  INFO root [0x000035f0] [2018-08-06 10:21:59,041] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000035f0] [2018-08-06 10:21:59,041] - onBaseAppShutDown: state=2
 ERROR root [0x000035f0] [2018-08-06 10:21:59,062] - Account::onCellWriteToDBCompleted(10): not found dbmgr!
 ERROR root [0x000035f0] [2018-08-06 10:21:59,063] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000035f0] [2018-08-06 10:21:59,064] - Avatar::onCellWriteToDBCompleted(11): not found dbmgr!
 ERROR root [0x000035f0] [2018-08-06 10:21:59,064] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,066] - Account::~Account(): 10
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,066] - Space::~Space(): 4
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,067] - Space::~Space(): 5
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,067] - Space::~Space(): 6
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,067] - Space::~Space(): 7
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,067] - Space::~Space(): 8
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,067] - Space::~Space(): 9
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,068] - Avatar::~Avatar(): 11
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,068] - Chat::~Chat(): 2
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,068] - Spaces::~Spaces(): 3
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,070] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,070] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,070] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,070] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,070] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,071] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,071] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,071] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000035f0] [2018-08-06 10:21:59,089] - Script::uninstall(): is successfully!
 DEBUG root [0x000035f0] [2018-08-06 10:21:59,089] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000376c] [2018-08-06 10:30:18,186] - 
  INFO root [0x0000376c] [2018-08-06 10:30:18,198] - -----------------------------------------------------------------------------------------


  INFO root [0x0000376c] [2018-08-06 10:30:18,205] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x0000376c] [2018-08-06 10:30:18,206] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x0000376c] [2018-08-06 10:30:18,206] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x0000376c] [2018-08-06 10:30:18,214] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20015 )
  INFO root [0x0000376c] [2018-08-06 10:30:18,215] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20015, SOMAXCONN=128.
  INFO root [0x0000376c] [2018-08-06 10:30:18,220] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:3444 )
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:3444, SOMAXCONN=128.
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - server-configs:
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - 	gameUpdateHertz : 10
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - 	entryScriptFile : kbemain
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - 	internalAddr : 10.139.89.70:3444
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - 	externalAddr : 10.139.89.70:20015
  INFO root [0x0000376c] [2018-08-06 10:30:18,221] - 	componentID : 7001
  INFO root [0x0000376c] [2018-08-06 10:30:18,668] - Components::findLogger: found logger, addr:10.139.89.70:3433
  INFO root [0x0000376c] [2018-08-06 10:30:18,669] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x0000376c] [2018-08-06 10:30:18,669] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000376c] [2018-08-06 10:30:18,678] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 77AC5AA4419ECB24CC821B049AB4EA32. Config: Debug X86. Built: 23:19:57 May 26 2018. AppID: 7001. UID: 21326. PID: 14704 ----
  INFO root [0x0000376c] [2018-08-06 10:30:18,678] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x0000376c] [2018-08-06 10:30:18,679] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000376c] [2018-08-06 10:30:18,679] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,936] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,951] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,965] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,970] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,971] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,971] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000376c] [2018-08-06 10:30:18,972] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000376c] [2018-08-06 10:30:19,020] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000376c] [2018-08-06 10:30:19,202] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000376c] [2018-08-06 10:30:19,203] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000376c] [2018-08-06 10:30:19,621] - loaded entity-script:Account(1).
 DEBUG root [0x0000376c] [2018-08-06 10:30:19,625] - loaded entity-script:Avatar(2).
 DEBUG root [0x0000376c] [2018-08-06 10:30:19,631] - loaded entity-script:Spaces(3).
 DEBUG root [0x0000376c] [2018-08-06 10:30:19,632] - loaded entity-script:Space(4).
 DEBUG root [0x0000376c] [2018-08-06 10:30:20,030] - loaded entity-script:Equipment(5).
 DEBUG root [0x0000376c] [2018-08-06 10:30:20,032] - loaded entity-script:Chat(6).
  INFO root [0x0000376c] [2018-08-06 10:30:20,032] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000376c] [2018-08-06 10:30:20,032] - TelnetServer server is running on port 40000
  INFO root [0x0000376c] [2018-08-06 10:30:20,380] - ---- baseapp is running ----
 DEBUG root [0x0000376c] [2018-08-06 10:30:20,380] - Components::process(): Request for the process of identity...
  WARN root [0x0000376c] [2018-08-06 10:30:26,560] - Forwarding logs to logger[10.139.89.70:3433/0/0/0]...
 ERROR root [0x0000376c] [2018-08-06 10:31:19,319] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000376c] [2018-08-06 10:31:19,326] - The following logs sent to logger failed:
  WARN root [0x0000376c] [2018-08-06 10:31:19,327] - ==> [2018-08-06 10:31:19 316] TCPPacketReceiver::processPendingEvents(10.139.89.70:3433): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000376c] [2018-08-06 10:31:19,328] - ==> [2018-08-06 10:31:19 319] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000376c] [2018-08-06 10:31:19,495] - TCPPacketReceiver::processPendingEvents(10.139.89.70:3435): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000376c] [2018-08-06 10:31:19,502] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000376c] [2018-08-06 10:31:19,522] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000376c] [2018-08-06 10:31:19,524] - onBaseAppShutDown: state=0
  INFO root [0x0000376c] [2018-08-06 10:31:19,525] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000376c] [2018-08-06 10:31:19,526] - onBaseAppShutDown: state=1
  INFO root [0x0000376c] [2018-08-06 10:31:19,527] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000376c] [2018-08-06 10:31:19,527] - onBaseAppShutDown: state=2
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,637] - Space::~Space(): 2004
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,640] - Space::~Space(): 2005
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,641] - Space::~Space(): 2006
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,642] - Space::~Space(): 2007
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,643] - Space::~Space(): 2008
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,643] - Space::~Space(): 2009
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,643] - Spaces::~Spaces(): 2003
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,643] - Chat::~Chat(): 2002
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,672] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,673] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,673] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,674] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,674] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,675] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,675] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,675] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000376c] [2018-08-06 10:31:19,725] - Script::uninstall(): is successfully!
 DEBUG root [0x0000376c] [2018-08-06 10:31:19,740] - ThreadPool::destroy(): starting size 2.
