  INFO root [0x00001424] [2018-08-03 17:11:53,688] - 
  INFO root [0x00001424] [2018-08-03 17:11:53,688] - -----------------------------------------------------------------------------------------


  INFO root [0x00001424] [2018-08-03 17:11:53,690] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001424] [2018-08-03 17:11:53,690] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00001424] [2018-08-03 17:11:53,690] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001424] [2018-08-03 17:11:53,698] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:3273 )
  INFO root [0x00001424] [2018-08-03 17:11:53,708] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:3273, SOMAXCONN=5.
  INFO root [0x00001424] [2018-08-03 17:11:53,708] - server-configs:
  INFO root [0x00001424] [2018-08-03 17:11:53,708] - 	gameUpdateHertz : 10
  INFO root [0x00001424] [2018-08-03 17:11:53,709] - 	defaultViewRadius : 80
  INFO root [0x00001424] [2018-08-03 17:11:53,709] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001424] [2018-08-03 17:11:53,709] - 	entryScriptFile : kbemain
  INFO root [0x00001424] [2018-08-03 17:11:53,709] - 	internalAddr : 10.139.66.192:3273
  INFO root [0x00001424] [2018-08-03 17:11:53,709] - 	componentID : 8001
  INFO root [0x00001424] [2018-08-03 17:11:53,816] - Components::findLogger: found logger, addr:10.139.66.192:3142
  INFO root [0x00001424] [2018-08-03 17:11:53,816] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00001424] [2018-08-03 17:11:53,817] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001424] [2018-08-03 17:11:53,830] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 16:28:54 Apr 30 2018. AppID: 8001. UID: 10103. PID: 12612 ----
  INFO root [0x00001424] [2018-08-03 17:11:53,830] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00001424] [2018-08-03 17:11:53,831] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001424] [2018-08-03 17:11:53,831] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001424] [2018-08-03 17:11:53,997] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001424] [2018-08-03 17:11:53,998] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001424] [2018-08-03 17:11:53,998] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001424] [2018-08-03 17:11:54,005] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001424] [2018-08-03 17:11:54,007] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001424] [2018-08-03 17:11:54,007] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001424] [2018-08-03 17:11:54,008] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001424] [2018-08-03 17:11:54,088] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001424] [2018-08-03 17:11:54,162] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00001424] [2018-08-03 17:11:54,162] - Script::install(): KBExtra is successfully!
  INFO root [0x00001424] [2018-08-03 17:11:54,436] - TelnetServer server is running on port 50000
  INFO root [0x00001424] [2018-08-03 17:11:55,077] - ---- cellapp is running ----
 DEBUG root [0x00001424] [2018-08-03 17:11:55,078] - Components::process(): Request for the process of identity...
  WARN root [0x00001424] [2018-08-03 17:12:01,317] - Forwarding logs to logger[10.139.66.192:3142/0/0/0]...
 ERROR root [0x00001424] [2018-08-03 17:12:35,001] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001424] [2018-08-03 17:12:35,003] - The following logs sent to logger failed:
  WARN root [0x00001424] [2018-08-03 17:12:35,004] - ==> [2018-08-03 17:12:34 998] TCPPacketReceiver::processPendingEvents(10.139.66.192:3142): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001424] [2018-08-03 17:12:35,004] - ==> [2018-08-03 17:12:35 002] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001424] [2018-08-03 17:12:35,678] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
 ERROR root [0x00001424] [2018-08-03 17:12:37,180] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00001424] [2018-08-03 17:12:37,190] - Components::findComponents: receive error!
  WARN root [0x00001424] [2018-08-03 17:12:37,191] - EntityApp::checkTickPeriod: tick took 1614% (1.61 seconds)!
  WARN root [0x00001424] [2018-08-03 17:12:38,192] - Components::findComponents: find dbmgr(18)...
delay time is too long, please check the dbmgr logs!
 ERROR root [0x00001424] [2018-08-03 17:12:39,695] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00001424] [2018-08-03 17:12:39,696] - Components::findComponents: receive error!
  WARN root [0x00001424] [2018-08-03 17:12:39,698] - EntityApp::checkTickPeriod: tick took 1520% (1.52 seconds)!
  WARN root [0x00001424] [2018-08-03 17:12:40,777] - Components::findComponents: find dbmgr(19)...
delay time is too long, please check the dbmgr logs!
  INFO root [0x00003598] [2018-08-03 17:12:45,833] - 
  INFO root [0x00003598] [2018-08-03 17:12:45,834] - -----------------------------------------------------------------------------------------


  INFO root [0x00003598] [2018-08-03 17:12:45,834] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003598] [2018-08-03 17:12:45,835] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00003598] [2018-08-03 17:12:45,835] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003598] [2018-08-03 17:12:45,842] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:3739 )
  INFO root [0x00003598] [2018-08-03 17:12:45,843] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:3739, SOMAXCONN=5.
  INFO root [0x00003598] [2018-08-03 17:12:45,843] - server-configs:
  INFO root [0x00003598] [2018-08-03 17:12:45,843] - 	gameUpdateHertz : 10
  INFO root [0x00003598] [2018-08-03 17:12:45,843] - 	defaultViewRadius : 80
  INFO root [0x00003598] [2018-08-03 17:12:45,843] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003598] [2018-08-03 17:12:45,843] - 	entryScriptFile : kbemain
  INFO root [0x00003598] [2018-08-03 17:12:45,844] - 	internalAddr : 10.139.66.192:3739
  INFO root [0x00003598] [2018-08-03 17:12:45,844] - 	componentID : 8001
  INFO root [0x00003598] [2018-08-03 17:12:45,912] - Components::findLogger: found logger, addr:10.139.66.192:3696
  INFO root [0x00003598] [2018-08-03 17:12:45,912] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00003598] [2018-08-03 17:12:45,913] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003598] [2018-08-03 17:12:45,920] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 16:28:54 Apr 30 2018. AppID: 8001. UID: 10103. PID: 2504 ----
  INFO root [0x00003598] [2018-08-03 17:12:45,920] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00003598] [2018-08-03 17:12:45,920] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003598] [2018-08-03 17:12:45,921] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003598] [2018-08-03 17:12:46,075] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003598] [2018-08-03 17:12:46,076] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003598] [2018-08-03 17:12:46,076] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003598] [2018-08-03 17:12:46,079] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003598] [2018-08-03 17:12:46,079] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003598] [2018-08-03 17:12:46,079] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003598] [2018-08-03 17:12:46,080] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003598] [2018-08-03 17:12:46,144] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003598] [2018-08-03 17:12:46,200] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00003598] [2018-08-03 17:12:46,201] - Script::install(): KBExtra is successfully!
  INFO root [0x00003598] [2018-08-03 17:12:46,249] - TelnetServer server is running on port 50000
  INFO root [0x00003598] [2018-08-03 17:12:46,791] - ---- cellapp is running ----
 DEBUG root [0x00003598] [2018-08-03 17:12:46,792] - Components::process(): Request for the process of identity...
  WARN root [0x00003598] [2018-08-03 17:12:53,010] - Forwarding logs to logger[10.139.66.192:3696/0/0/0]...
 ERROR root [0x00003598] [2018-08-03 17:13:57,969] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003598] [2018-08-03 17:13:57,973] - The following logs sent to logger failed:
  WARN root [0x00003598] [2018-08-03 17:13:57,974] - ==> [2018-08-03 17:13:57 969] TCPPacketReceiver::processPendingEvents(10.139.66.192:3696): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003598] [2018-08-03 17:13:57,974] - ==> [2018-08-03 17:13:57 970] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003598] [2018-08-03 17:13:58,107] - TCPPacketReceiver::processPendingEvents(10.139.66.192:3706): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003598] [2018-08-03 17:13:58,110] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003598] [2018-08-03 17:13:58,120] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003598] [2018-08-03 17:13:58,131] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003598] [2018-08-03 17:13:58,132] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003598] [2018-08-03 17:13:58,133] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003598] [2018-08-03 17:13:58,133] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003598] [2018-08-03 17:13:58,157] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003598] [2018-08-03 17:13:58,157] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003598] [2018-08-03 17:13:58,157] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003598] [2018-08-03 17:13:58,157] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003598] [2018-08-03 17:13:58,158] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003598] [2018-08-03 17:13:58,158] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003598] [2018-08-03 17:13:58,158] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003598] [2018-08-03 17:13:58,158] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003598] [2018-08-03 17:13:58,176] - Script::uninstall(): is successfully!
 DEBUG root [0x00003598] [2018-08-03 17:13:58,176] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003598] [2018-08-03 17:13:58,478] - ThreadPool::destroy(): waiting for thread(2)[0x1b78a58,0x1b78d98,], try=1
  INFO root [0x00003644] [2018-08-03 17:14:00,960] - 
  INFO root [0x00003644] [2018-08-03 17:14:00,961] - -----------------------------------------------------------------------------------------


  INFO root [0x00003644] [2018-08-03 17:14:00,963] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003644] [2018-08-03 17:14:00,963] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00003644] [2018-08-03 17:14:00,963] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003644] [2018-08-03 17:14:00,970] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:4377 )
  INFO root [0x00003644] [2018-08-03 17:14:00,970] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:4377, SOMAXCONN=5.
  INFO root [0x00003644] [2018-08-03 17:14:00,971] - server-configs:
  INFO root [0x00003644] [2018-08-03 17:14:00,971] - 	gameUpdateHertz : 10
  INFO root [0x00003644] [2018-08-03 17:14:00,971] - 	defaultViewRadius : 80
  INFO root [0x00003644] [2018-08-03 17:14:00,971] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003644] [2018-08-03 17:14:00,971] - 	entryScriptFile : kbemain
  INFO root [0x00003644] [2018-08-03 17:14:00,972] - 	internalAddr : 10.139.66.192:4377
  INFO root [0x00003644] [2018-08-03 17:14:00,972] - 	componentID : 8001
  INFO root [0x00003644] [2018-08-03 17:14:02,485] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 16:28:54 Apr 30 2018. AppID: 8001. UID: 10103. PID: 14320 ----
  INFO root [0x00003644] [2018-08-03 17:14:02,486] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00003644] [2018-08-03 17:14:02,487] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003644] [2018-08-03 17:14:02,487] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003644] [2018-08-03 17:14:02,637] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003644] [2018-08-03 17:14:02,638] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003644] [2018-08-03 17:14:02,638] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003644] [2018-08-03 17:14:02,644] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003644] [2018-08-03 17:14:02,645] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003644] [2018-08-03 17:14:02,645] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003644] [2018-08-03 17:14:02,646] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003644] [2018-08-03 17:14:02,708] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003644] [2018-08-03 17:14:02,772] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00003644] [2018-08-03 17:14:02,772] - Script::install(): KBExtra is successfully!
  INFO root [0x00003644] [2018-08-03 17:14:02,830] - TelnetServer server is running on port 50000
  INFO root [0x00003644] [2018-08-03 17:14:03,350] - ---- cellapp is running ----
 DEBUG root [0x00003644] [2018-08-03 17:14:03,351] - Components::process(): Request for the process of identity...
  WARN root [0x00003644] [2018-08-03 17:14:09,646] - EntityApp::checkTickPeriod: tick took 6296% (6.30 seconds)!
  INFO root [0x00003644] [2018-08-03 17:14:10,664] - Components::findComponents: find logger(1)...
  INFO root [0x00003644] [2018-08-03 17:14:10,756] - Components::findComponents: found logger, addr:10.139.66.192:4361
  INFO root [0x00003644] [2018-08-03 17:14:10,757] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00003644] [2018-08-03 17:14:10,758] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003644] [2018-08-03 17:14:10,760] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003644] [2018-08-03 17:14:10,862] - Components::findComponents: found dbmgr, addr:10.139.66.192:4365
  INFO root [0x00003644] [2018-08-03 17:14:10,862] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00003644] [2018-08-03 17:14:10,862] - Components::addComponent[dbmgr], uid=10103, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003644] [2018-08-03 17:14:10,862] - Components::findComponents: found dbmgr, addr:10.139.66.192:4365
  WARN root [0x00003644] [2018-08-03 17:14:11,863] - Forwarding logs to logger[10.139.66.192:4361/0/0/0]...
 ERROR root [0x00003644] [2018-08-03 17:16:05,266] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003644] [2018-08-03 17:16:05,272] - The following logs sent to logger failed:
  WARN root [0x00003644] [2018-08-03 17:16:05,273] - ==> [2018-08-03 17:16:05 266] TCPPacketReceiver::processPendingEvents(10.139.66.192:4361): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003644] [2018-08-03 17:16:05,273] - ==> [2018-08-03 17:16:05 267] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003644] [2018-08-03 17:16:05,399] - TCPPacketReceiver::processPendingEvents(10.139.66.192:4365): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003644] [2018-08-03 17:16:05,401] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003644] [2018-08-03 17:16:05,409] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003644] [2018-08-03 17:16:05,411] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003644] [2018-08-03 17:16:05,411] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003644] [2018-08-03 17:16:05,412] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003644] [2018-08-03 17:16:05,413] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003644] [2018-08-03 17:16:05,435] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003644] [2018-08-03 17:16:05,435] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003644] [2018-08-03 17:16:05,436] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003644] [2018-08-03 17:16:05,436] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003644] [2018-08-03 17:16:05,436] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003644] [2018-08-03 17:16:05,436] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003644] [2018-08-03 17:16:05,436] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003644] [2018-08-03 17:16:05,436] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003644] [2018-08-03 17:16:05,448] - Script::uninstall(): is successfully!
 DEBUG root [0x00003644] [2018-08-03 17:16:05,448] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003644] [2018-08-03 17:16:05,749] - ThreadPool::destroy(): waiting for thread(2)[0x1bf2c28,0x1bf1f90,], try=1
  INFO root [0x00003548] [2018-08-03 17:16:08,094] - 
  INFO root [0x00003548] [2018-08-03 17:16:08,098] - -----------------------------------------------------------------------------------------


  INFO root [0x00003548] [2018-08-03 17:16:08,102] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003548] [2018-08-03 17:16:08,103] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00003548] [2018-08-03 17:16:08,103] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003548] [2018-08-03 17:16:08,111] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:5499 )
  INFO root [0x00003548] [2018-08-03 17:16:08,111] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:5499, SOMAXCONN=5.
  INFO root [0x00003548] [2018-08-03 17:16:08,112] - server-configs:
  INFO root [0x00003548] [2018-08-03 17:16:08,112] - 	gameUpdateHertz : 10
  INFO root [0x00003548] [2018-08-03 17:16:08,112] - 	defaultViewRadius : 80
  INFO root [0x00003548] [2018-08-03 17:16:08,112] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003548] [2018-08-03 17:16:08,112] - 	entryScriptFile : kbemain
  INFO root [0x00003548] [2018-08-03 17:16:08,113] - 	internalAddr : 10.139.66.192:5499
  INFO root [0x00003548] [2018-08-03 17:16:08,113] - 	componentID : 8001
  INFO root [0x00003548] [2018-08-03 17:16:08,377] - Components::findLogger: found logger, addr:10.139.66.192:5485
  INFO root [0x00003548] [2018-08-03 17:16:08,378] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00003548] [2018-08-03 17:16:08,378] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003548] [2018-08-03 17:16:08,386] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 16:28:54 Apr 30 2018. AppID: 8001. UID: 10103. PID: 12508 ----
  INFO root [0x00003548] [2018-08-03 17:16:08,387] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00003548] [2018-08-03 17:16:08,387] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003548] [2018-08-03 17:16:08,388] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003548] [2018-08-03 17:16:08,538] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003548] [2018-08-03 17:16:08,539] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003548] [2018-08-03 17:16:08,539] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003548] [2018-08-03 17:16:08,542] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003548] [2018-08-03 17:16:08,542] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003548] [2018-08-03 17:16:08,542] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003548] [2018-08-03 17:16:08,543] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003548] [2018-08-03 17:16:08,625] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003548] [2018-08-03 17:16:08,702] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00003548] [2018-08-03 17:16:08,702] - Script::install(): KBExtra is successfully!
  INFO root [0x00003548] [2018-08-03 17:16:08,764] - TelnetServer server is running on port 50000
  INFO root [0x00003548] [2018-08-03 17:16:09,489] - ---- cellapp is running ----
 DEBUG root [0x00003548] [2018-08-03 17:16:09,491] - Components::process(): Request for the process of identity...
  WARN root [0x00003548] [2018-08-03 17:16:13,093] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20408, errorno=10048
  WARN root [0x00003548] [2018-08-03 17:16:16,192] - Forwarding logs to logger[10.139.66.192:5485/0/0/0]...
 ERROR root [0x00003548] [2018-08-03 17:16:50,334] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003548] [2018-08-03 17:16:50,338] - The following logs sent to logger failed:
  WARN root [0x00003548] [2018-08-03 17:16:50,339] - ==> [2018-08-03 17:16:50 332] TCPPacketReceiver::processPendingEvents(10.139.66.192:5485): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003548] [2018-08-03 17:16:50,339] - ==> [2018-08-03 17:16:50 335] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003548] [2018-08-03 17:16:50,432] - TCPPacketReceiver::processPendingEvents(10.139.66.192:5494): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003548] [2018-08-03 17:16:50,433] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003548] [2018-08-03 17:16:50,441] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003548] [2018-08-03 17:16:50,451] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003548] [2018-08-03 17:16:50,452] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003548] [2018-08-03 17:16:50,453] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003548] [2018-08-03 17:16:50,453] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003548] [2018-08-03 17:16:50,477] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003548] [2018-08-03 17:16:50,477] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003548] [2018-08-03 17:16:50,478] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003548] [2018-08-03 17:16:50,478] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003548] [2018-08-03 17:16:50,478] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003548] [2018-08-03 17:16:50,478] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003548] [2018-08-03 17:16:50,478] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003548] [2018-08-03 17:16:50,478] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003548] [2018-08-03 17:16:50,497] - Script::uninstall(): is successfully!
 DEBUG root [0x00003548] [2018-08-03 17:16:50,497] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003548] [2018-08-03 17:16:50,798] - ThreadPool::destroy(): waiting for thread(2)[0x1cf1d98,0x1cf1850,], try=1
  INFO root [0x00001f5c] [2018-08-03 17:23:23,523] - 
  INFO root [0x00001f5c] [2018-08-03 17:23:23,524] - -----------------------------------------------------------------------------------------


  INFO root [0x00001f5c] [2018-08-03 17:23:23,526] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001f5c] [2018-08-03 17:23:23,526] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00001f5c] [2018-08-03 17:23:23,527] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001f5c] [2018-08-03 17:23:23,536] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:8887 )
  INFO root [0x00001f5c] [2018-08-03 17:23:23,537] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:8887, SOMAXCONN=5.
  INFO root [0x00001f5c] [2018-08-03 17:23:23,537] - server-configs:
  INFO root [0x00001f5c] [2018-08-03 17:23:23,537] - 	gameUpdateHertz : 10
  INFO root [0x00001f5c] [2018-08-03 17:23:23,537] - 	defaultViewRadius : 80
  INFO root [0x00001f5c] [2018-08-03 17:23:23,537] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001f5c] [2018-08-03 17:23:23,538] - 	entryScriptFile : kbemain
  INFO root [0x00001f5c] [2018-08-03 17:23:23,538] - 	internalAddr : 10.139.66.192:8887
  INFO root [0x00001f5c] [2018-08-03 17:23:23,538] - 	componentID : 8001
  INFO root [0x00001f5c] [2018-08-03 17:23:23,825] - Components::findLogger: found logger, addr:10.139.66.192:8873
  INFO root [0x00001f5c] [2018-08-03 17:23:23,825] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00001f5c] [2018-08-03 17:23:23,825] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001f5c] [2018-08-03 17:23:23,835] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 16:28:54 Apr 30 2018. AppID: 8001. UID: 10103. PID: 10416 ----
  INFO root [0x00001f5c] [2018-08-03 17:23:23,835] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00001f5c] [2018-08-03 17:23:23,835] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001f5c] [2018-08-03 17:23:23,836] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,987] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,988] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,990] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,995] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,996] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,996] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f5c] [2018-08-03 17:23:23,997] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f5c] [2018-08-03 17:23:24,061] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f5c] [2018-08-03 17:23:24,116] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00001f5c] [2018-08-03 17:23:24,116] - Script::install(): KBExtra is successfully!
  INFO root [0x00001f5c] [2018-08-03 17:23:24,173] - TelnetServer server is running on port 50000
  INFO root [0x00001f5c] [2018-08-03 17:23:24,845] - ---- cellapp is running ----
 DEBUG root [0x00001f5c] [2018-08-03 17:23:24,846] - Components::process(): Request for the process of identity...
  WARN root [0x00001f5c] [2018-08-03 17:23:31,143] - Forwarding logs to logger[10.139.66.192:8873/0/0/0]...
 ERROR root [0x00001f5c] [2018-08-03 17:23:54,604] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001f5c] [2018-08-03 17:23:54,616] - The following logs sent to logger failed:
  WARN root [0x00001f5c] [2018-08-03 17:23:54,616] - ==> [2018-08-03 17:23:54 603] TCPPacketReceiver::processPendingEvents(10.139.66.192:8873): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f5c] [2018-08-03 17:23:54,616] - ==> [2018-08-03 17:23:54 605] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001f5c] [2018-08-03 17:23:54,733] - TCPPacketReceiver::processPendingEvents(10.139.66.192:8876): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f5c] [2018-08-03 17:23:54,735] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001f5c] [2018-08-03 17:23:54,749] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001f5c] [2018-08-03 17:23:54,752] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001f5c] [2018-08-03 17:23:54,753] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,754] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,754] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,783] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,784] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,784] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,785] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,785] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,785] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,785] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,786] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f5c] [2018-08-03 17:23:54,813] - Script::uninstall(): is successfully!
 DEBUG root [0x00001f5c] [2018-08-03 17:23:54,814] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001f5c] [2018-08-03 17:23:55,114] - ThreadPool::destroy(): waiting for thread(2)[0x1c42080,0x1c41f48,], try=1
  INFO root [0x000036bc] [2018-08-03 17:24:15,037] - 
  INFO root [0x000036bc] [2018-08-03 17:24:15,037] - -----------------------------------------------------------------------------------------


  INFO root [0x000036bc] [2018-08-03 17:24:15,039] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000036bc] [2018-08-03 17:24:15,039] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x000036bc] [2018-08-03 17:24:15,039] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000036bc] [2018-08-03 17:24:15,046] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:9443 )
  INFO root [0x000036bc] [2018-08-03 17:24:15,046] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:9443, SOMAXCONN=5.
  INFO root [0x000036bc] [2018-08-03 17:24:15,047] - server-configs:
  INFO root [0x000036bc] [2018-08-03 17:24:15,047] - 	gameUpdateHertz : 10
  INFO root [0x000036bc] [2018-08-03 17:24:15,047] - 	defaultViewRadius : 80
  INFO root [0x000036bc] [2018-08-03 17:24:15,047] - 	defaultViewHysteresisArea : 5
  INFO root [0x000036bc] [2018-08-03 17:24:15,048] - 	entryScriptFile : kbemain
  INFO root [0x000036bc] [2018-08-03 17:24:15,048] - 	internalAddr : 10.139.66.192:9443
  INFO root [0x000036bc] [2018-08-03 17:24:15,048] - 	componentID : 8001
  INFO root [0x000036bc] [2018-08-03 17:24:15,094] - Components::findLogger: found logger, addr:10.139.66.192:9420
  INFO root [0x000036bc] [2018-08-03 17:24:15,095] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000036bc] [2018-08-03 17:24:15,095] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000036bc] [2018-08-03 17:24:15,129] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 16:28:54 Apr 30 2018. AppID: 8001. UID: 10103. PID: 13528 ----
  INFO root [0x000036bc] [2018-08-03 17:24:15,131] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x000036bc] [2018-08-03 17:24:15,132] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000036bc] [2018-08-03 17:24:15,132] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,303] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,304] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,305] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,313] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,315] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,315] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,316] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000036bc] [2018-08-03 17:24:15,378] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000036bc] [2018-08-03 17:24:15,437] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x000036bc] [2018-08-03 17:24:15,437] - Script::install(): KBExtra is successfully!
  INFO root [0x000036bc] [2018-08-03 17:24:15,496] - TelnetServer server is running on port 50000
  INFO root [0x000036bc] [2018-08-03 17:24:16,148] - ---- cellapp is running ----
 DEBUG root [0x000036bc] [2018-08-03 17:24:16,148] - Components::process(): Request for the process of identity...
  WARN root [0x000036bc] [2018-08-03 17:24:22,426] - Forwarding logs to logger[10.139.66.192:9420/0/0/0]...
 ERROR root [0x000036bc] [2018-08-03 17:25:29,512] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000036bc] [2018-08-03 17:25:29,512] - The following logs sent to logger failed:
  WARN root [0x000036bc] [2018-08-03 17:25:29,512] - ==> [2018-08-03 17:25:29 522] TCPPacketReceiver::processPendingEvents(10.139.66.192:9420): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000036bc] [2018-08-03 17:25:29,512] - ==> [2018-08-03 17:25:29 526] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000036bc] [2018-08-03 17:25:29,605] - TCPPacketReceiver::processPendingEvents(10.139.66.192:9421): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000036bc] [2018-08-03 17:25:29,605] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000036bc] [2018-08-03 17:25:29,621] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000036bc] [2018-08-03 17:25:29,621] - Shutdowner::onShutdown: shutting down
  INFO root [0x000036bc] [2018-08-03 17:25:29,621] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,621] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,621] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000036bc] [2018-08-03 17:25:29,668] - Script::uninstall(): is successfully!
 DEBUG root [0x000036bc] [2018-08-03 17:25:29,668] - ThreadPool::destroy(): starting size 2.
