  INFO root [0x00001d50] [2018-08-10 11:39:07,165] - 
  INFO root [0x00001d50] [2018-08-10 11:39:07,170] - -----------------------------------------------------------------------------------------


  INFO root [0x00001d50] [2018-08-10 11:39:07,226] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00001d50] [2018-08-10 11:39:07,227] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00001d50] [2018-08-10 11:39:07,228] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00001d50] [2018-08-10 11:39:07,256] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:7926 )
  INFO root [0x00001d50] [2018-08-10 11:39:07,256] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:7926, SOMAXCONN=5.
  INFO root [0x00001d50] [2018-08-10 11:39:07,257] - server-configs:
  INFO root [0x00001d50] [2018-08-10 11:39:07,257] - 	gameUpdateHertz : 10
  INFO root [0x00001d50] [2018-08-10 11:39:07,262] - 	defaultViewRadius : 80
  INFO root [0x00001d50] [2018-08-10 11:39:07,263] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001d50] [2018-08-10 11:39:07,263] - 	entryScriptFile : kbemain
  INFO root [0x00001d50] [2018-08-10 11:39:07,263] - 	internalAddr : 10.139.89.70:7926
  INFO root [0x00001d50] [2018-08-10 11:39:07,263] - 	componentID : 8001
  INFO root [0x00001d50] [2018-08-10 11:39:07,326] - Components::findLogger: found logger, addr:10.139.89.70:7903
  INFO root [0x00001d50] [2018-08-10 11:39:07,326] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00001d50] [2018-08-10 11:39:07,329] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d50] [2018-08-10 11:39:07,357] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 13048 ----
  INFO root [0x00001d50] [2018-08-10 11:39:07,358] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00001d50] [2018-08-10 11:39:07,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001d50] [2018-08-10 11:39:07,363] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,576] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,594] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,603] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,648] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,649] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,650] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,651] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001d50] [2018-08-10 11:39:07,783] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001d50] [2018-08-10 11:39:07,876] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001d50] [2018-08-10 11:39:07,876] - Script::install(): KBExtra is successfully!
  INFO root [0x00001d50] [2018-08-10 11:39:07,987] - TelnetServer server is running on port 50000
  INFO root [0x00001d50] [2018-08-10 11:39:08,517] - ---- cellapp is running ----
 DEBUG root [0x00001d50] [2018-08-10 11:39:08,555] - Components::process(): Request for the process of identity...
  WARN root [0x00001d50] [2018-08-10 11:39:14,864] - Forwarding logs to logger[10.139.89.70:7903/0/0/0]...
 ERROR root [0x00001d50] [2018-08-10 14:01:00,732] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001d50] [2018-08-10 14:01:00,732] - The following logs sent to logger failed:
  WARN root [0x00001d50] [2018-08-10 14:01:00,732] - ==> [2018-08-10 14:01:00 727] TCPPacketReceiver::processPendingEvents(10.139.89.70:7903): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d50] [2018-08-10 14:01:00,732] - ==> [2018-08-10 14:01:00 733] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001d50] [2018-08-10 14:01:00,839] - TCPPacketReceiver::processPendingEvents(10.139.89.70:7905): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d50] [2018-08-10 14:01:00,839] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001d50] [2018-08-10 14:01:00,853] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001d50] [2018-08-10 14:01:00,853] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001d50] [2018-08-10 14:01:00,853] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,853] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,853] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,870] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,874] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001d50] [2018-08-10 14:01:00,893] - Script::uninstall(): is successfully!
 DEBUG root [0x00001d50] [2018-08-10 14:01:00,893] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001d50] [2018-08-10 14:01:01,199] - ThreadPool::destroy(): waiting for thread(2)[0x1f69fe0,0x1f6a458,], try=1
  INFO root [0x0000261c] [2018-08-10 14:04:48,150] - 
  INFO root [0x0000261c] [2018-08-10 14:04:48,172] - -----------------------------------------------------------------------------------------


  INFO root [0x0000261c] [2018-08-10 14:04:48,178] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x0000261c] [2018-08-10 14:04:48,178] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x0000261c] [2018-08-10 14:04:48,178] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x0000261c] [2018-08-10 14:04:48,190] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:9274 )
  INFO root [0x0000261c] [2018-08-10 14:04:48,190] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:9274, SOMAXCONN=5.
  INFO root [0x0000261c] [2018-08-10 14:04:48,190] - server-configs:
  INFO root [0x0000261c] [2018-08-10 14:04:48,192] - 	gameUpdateHertz : 10
  INFO root [0x0000261c] [2018-08-10 14:04:48,192] - 	defaultViewRadius : 80
  INFO root [0x0000261c] [2018-08-10 14:04:48,192] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000261c] [2018-08-10 14:04:48,192] - 	entryScriptFile : kbemain
  INFO root [0x0000261c] [2018-08-10 14:04:48,192] - 	internalAddr : 10.139.89.70:9274
  INFO root [0x0000261c] [2018-08-10 14:04:48,192] - 	componentID : 8001
  INFO root [0x0000261c] [2018-08-10 14:04:48,644] - Components::findLogger: found logger, addr:10.139.89.70:9270
  INFO root [0x0000261c] [2018-08-10 14:04:48,644] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x0000261c] [2018-08-10 14:04:48,644] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000261c] [2018-08-10 14:04:48,654] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 10000 ----
  INFO root [0x0000261c] [2018-08-10 14:04:48,661] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x0000261c] [2018-08-10 14:04:48,669] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000261c] [2018-08-10 14:04:48,669] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,821] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,821] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,828] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,833] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,833] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,833] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,836] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000261c] [2018-08-10 14:04:48,899] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000261c] [2018-08-10 14:04:48,943] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000261c] [2018-08-10 14:04:48,943] - Script::install(): KBExtra is successfully!
  INFO root [0x0000261c] [2018-08-10 14:04:49,001] - TelnetServer server is running on port 50000
  INFO root [0x0000261c] [2018-08-10 14:04:49,952] - ---- cellapp is running ----
 DEBUG root [0x0000261c] [2018-08-10 14:04:49,977] - Components::process(): Request for the process of identity...
  WARN root [0x0000261c] [2018-08-10 14:04:54,069] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20338, errorno=10048
  WARN root [0x0000261c] [2018-08-10 14:04:57,198] - Forwarding logs to logger[10.139.89.70:9270/0/0/0]...
 ERROR root [0x0000261c] [2018-08-10 14:47:31,356] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000261c] [2018-08-10 14:47:31,365] - The following logs sent to logger failed:
  WARN root [0x0000261c] [2018-08-10 14:47:31,365] - ==> [2018-08-10 14:47:31 352] TCPPacketReceiver::processPendingEvents(10.139.89.70:9270): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000261c] [2018-08-10 14:47:31,365] - ==> [2018-08-10 14:47:31 357] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000261c] [2018-08-10 14:47:31,499] - TCPPacketReceiver::processPendingEvents(10.139.89.70:9269): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000261c] [2018-08-10 14:47:31,508] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000261c] [2018-08-10 14:47:31,516] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000261c] [2018-08-10 14:47:31,516] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000261c] [2018-08-10 14:47:31,517] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,518] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,518] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,554] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,555] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,555] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,555] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,557] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,557] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,557] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,557] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000261c] [2018-08-10 14:47:31,603] - Script::uninstall(): is successfully!
 DEBUG root [0x0000261c] [2018-08-10 14:47:31,603] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000261c] [2018-08-10 14:47:31,904] - ThreadPool::destroy(): waiting for thread(2)[0x1d99568,0x1d993c8,], try=1
  INFO root [0x00001980] [2018-08-10 14:47:34,545] - 
  INFO root [0x00001980] [2018-08-10 14:47:34,616] - -----------------------------------------------------------------------------------------


  INFO root [0x00001980] [2018-08-10 14:47:34,617] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00001980] [2018-08-10 14:47:34,617] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00001980] [2018-08-10 14:47:34,617] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00001980] [2018-08-10 14:47:34,689] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10320 )
  INFO root [0x00001980] [2018-08-10 14:47:34,690] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10320, SOMAXCONN=5.
  INFO root [0x00001980] [2018-08-10 14:47:34,690] - server-configs:
  INFO root [0x00001980] [2018-08-10 14:47:34,690] - 	gameUpdateHertz : 10
  INFO root [0x00001980] [2018-08-10 14:47:34,690] - 	defaultViewRadius : 80
  INFO root [0x00001980] [2018-08-10 14:47:34,690] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001980] [2018-08-10 14:47:34,691] - 	entryScriptFile : kbemain
  INFO root [0x00001980] [2018-08-10 14:47:34,691] - 	internalAddr : 10.139.89.70:10320
  INFO root [0x00001980] [2018-08-10 14:47:34,691] - 	componentID : 8001
  INFO root [0x00001980] [2018-08-10 14:47:35,207] - Components::findLogger: found logger, addr:10.139.89.70:10314
  INFO root [0x00001980] [2018-08-10 14:47:35,207] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00001980] [2018-08-10 14:47:35,208] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001980] [2018-08-10 14:47:35,233] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 9100 ----
  INFO root [0x00001980] [2018-08-10 14:47:35,236] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00001980] [2018-08-10 14:47:35,236] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001980] [2018-08-10 14:47:35,237] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001980] [2018-08-10 14:47:35,378] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001980] [2018-08-10 14:47:35,379] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001980] [2018-08-10 14:47:35,379] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001980] [2018-08-10 14:47:35,383] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001980] [2018-08-10 14:47:35,383] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001980] [2018-08-10 14:47:35,383] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001980] [2018-08-10 14:47:35,384] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001980] [2018-08-10 14:47:35,444] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001980] [2018-08-10 14:47:35,503] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001980] [2018-08-10 14:47:35,504] - Script::install(): KBExtra is successfully!
 ERROR root [0x00001980] [2018-08-10 14:47:35,529] - ScriptDefModule::addBaseMethodDescription: [reqsendEquipment_ON] is exist!
 ERROR root [0x00001980] [2018-08-10 14:47:35,530] - EntityDef::loadAllDefDescription:loadDefBaseMethods[Avatar] is failed!
 ERROR root [0x00001980] [2018-08-10 14:47:35,530] - EntityDef::initialize: interface[Equipment] error!
 ERROR root [0x00001980] [2018-08-10 14:47:35,531] - EntityDef::loadDefInfo: failed to load entity:Avatar interface.
 ERROR root [0x00001980] [2018-08-10 14:47:35,531] - EntityDef::initialize: failed to load entity(Avatar) module!
 ERROR root [0x00001980] [2018-08-10 14:47:35,531] - app::initialize(): initialization failed!
 DEBUG root [0x00001980] [2018-08-10 14:47:35,532] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001980] [2018-08-10 14:47:35,532] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001980] [2018-08-10 14:47:35,533] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001980] [2018-08-10 14:47:35,533] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001980] [2018-08-10 14:47:35,533] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001980] [2018-08-10 14:47:35,533] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001980] [2018-08-10 14:47:35,534] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001980] [2018-08-10 14:47:35,534] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001980] [2018-08-10 14:47:35,534] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001980] [2018-08-10 14:47:35,534] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001980] [2018-08-10 14:47:35,548] - Script::uninstall(): is successfully!
 DEBUG root [0x00001980] [2018-08-10 14:47:35,548] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001980] [2018-08-10 14:47:35,849] - ThreadPool::destroy(): waiting for thread(2)[0x1f99728,0x1f99178,], try=1
 DEBUG root [0x00001980] [2018-08-10 14:47:36,251] - TPThread::~TPThread(): 0x1f99728
 DEBUG root [0x00001980] [2018-08-10 14:47:36,251] - TPThread::~TPThread(): 0x1f99178
 DEBUG root [0x00001980] [2018-08-10 14:47:36,251] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00001980] [2018-08-10 14:47:36,252] - Bundle::destroyObjPool(): size 12.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,252] - Channel::destroyObjPool(): size 15.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,253] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,253] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,253] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,253] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,253] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00001980] [2018-08-10 14:47:36,253] - UDPPacketReceiver::destroyObjPool(): size 0.
  WARN root [0x00001980] [2018-08-10 14:47:36,254] - Forwarding logs to logger[10.139.89.70:10314/0/0/0]...
  INFO root [0x00001980] [2018-08-10 14:47:42,826] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x000040c8] [2018-08-10 14:48:27,203] - 
  INFO root [0x000040c8] [2018-08-10 14:48:27,246] - -----------------------------------------------------------------------------------------


  INFO root [0x000040c8] [2018-08-10 14:48:27,248] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x000040c8] [2018-08-10 14:48:27,248] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x000040c8] [2018-08-10 14:48:27,248] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x000040c8] [2018-08-10 14:48:27,334] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10341 )
  INFO root [0x000040c8] [2018-08-10 14:48:27,334] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10341, SOMAXCONN=5.
  INFO root [0x000040c8] [2018-08-10 14:48:27,334] - server-configs:
  INFO root [0x000040c8] [2018-08-10 14:48:27,339] - 	gameUpdateHertz : 10
  INFO root [0x000040c8] [2018-08-10 14:48:27,340] - 	defaultViewRadius : 80
  INFO root [0x000040c8] [2018-08-10 14:48:27,340] - 	defaultViewHysteresisArea : 5
  INFO root [0x000040c8] [2018-08-10 14:48:27,340] - 	entryScriptFile : kbemain
  INFO root [0x000040c8] [2018-08-10 14:48:27,340] - 	internalAddr : 10.139.89.70:10341
  INFO root [0x000040c8] [2018-08-10 14:48:27,340] - 	componentID : 8001
  INFO root [0x000040c8] [2018-08-10 14:48:28,870] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 2588 ----
  INFO root [0x000040c8] [2018-08-10 14:48:28,871] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x000040c8] [2018-08-10 14:48:28,871] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000040c8] [2018-08-10 14:48:28,872] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,059] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,060] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,060] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,065] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,066] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,066] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,067] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,127] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000040c8] [2018-08-10 14:48:29,181] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000040c8] [2018-08-10 14:48:29,182] - Script::install(): KBExtra is successfully!
 ERROR root [0x000040c8] [2018-08-10 14:48:29,211] - ScriptDefModule::addBaseMethodDescription: [reqsendEquipment_ON] is exist!
 ERROR root [0x000040c8] [2018-08-10 14:48:29,211] - EntityDef::loadAllDefDescription:loadDefBaseMethods[Avatar] is failed!
 ERROR root [0x000040c8] [2018-08-10 14:48:29,212] - EntityDef::initialize: interface[Equipment] error!
 ERROR root [0x000040c8] [2018-08-10 14:48:29,213] - EntityDef::loadDefInfo: failed to load entity:Avatar interface.
 ERROR root [0x000040c8] [2018-08-10 14:48:29,214] - EntityDef::initialize: failed to load entity(Avatar) module!
 ERROR root [0x000040c8] [2018-08-10 14:48:29,214] - app::initialize(): initialization failed!
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,214] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,214] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,216] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,216] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,216] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,217] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,217] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,217] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,217] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,217] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000040c8] [2018-08-10 14:48:29,236] - Script::uninstall(): is successfully!
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,237] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000040c8] [2018-08-10 14:48:29,537] - ThreadPool::destroy(): waiting for thread(2)[0x1de9458,0x1de8fe0,], try=1
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,939] - TPThread::~TPThread(): 0x1de9458
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,939] - TPThread::~TPThread(): 0x1de8fe0
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,939] - ThreadPool::destroy(): successfully!
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,939] - Bundle::destroyObjPool(): size 15.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,939] - Channel::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,940] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,940] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,940] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,940] - Address::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,940] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x000040c8] [2018-08-10 14:48:29,940] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x000040c8] [2018-08-10 14:48:36,443] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x0000305c] [2018-08-10 14:49:24,611] - 
  INFO root [0x0000305c] [2018-08-10 14:49:24,620] - -----------------------------------------------------------------------------------------


  INFO root [0x0000305c] [2018-08-10 14:49:24,621] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x0000305c] [2018-08-10 14:49:24,622] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x0000305c] [2018-08-10 14:49:24,622] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x0000305c] [2018-08-10 14:49:24,659] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10354 )
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10354, SOMAXCONN=5.
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - server-configs:
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - 	gameUpdateHertz : 10
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - 	defaultViewRadius : 80
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - 	entryScriptFile : kbemain
  INFO root [0x0000305c] [2018-08-10 14:49:24,664] - 	internalAddr : 10.139.89.70:10354
  INFO root [0x0000305c] [2018-08-10 14:49:24,665] - 	componentID : 8001
  INFO root [0x0000305c] [2018-08-10 14:49:26,175] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 208 ----
  INFO root [0x0000305c] [2018-08-10 14:49:26,175] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x0000305c] [2018-08-10 14:49:26,176] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000305c] [2018-08-10 14:49:26,176] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,327] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,329] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,330] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,337] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,338] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,338] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,339] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,395] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000305c] [2018-08-10 14:49:26,452] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000305c] [2018-08-10 14:49:26,452] - Script::install(): KBExtra is successfully!
 ERROR root [0x0000305c] [2018-08-10 14:49:26,472] - ScriptDefModule::addBaseMethodDescription: [reqsendEquipment_ON] is exist!
 ERROR root [0x0000305c] [2018-08-10 14:49:26,472] - EntityDef::loadAllDefDescription:loadDefBaseMethods[Avatar] is failed!
 ERROR root [0x0000305c] [2018-08-10 14:49:26,473] - EntityDef::initialize: interface[Equipment] error!
 ERROR root [0x0000305c] [2018-08-10 14:49:26,473] - EntityDef::loadDefInfo: failed to load entity:Avatar interface.
 ERROR root [0x0000305c] [2018-08-10 14:49:26,473] - EntityDef::initialize: failed to load entity(Avatar) module!
 ERROR root [0x0000305c] [2018-08-10 14:49:26,474] - app::initialize(): initialization failed!
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,474] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,474] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,475] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,475] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,475] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,476] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,476] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,476] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,476] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,476] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000305c] [2018-08-10 14:49:26,490] - Script::uninstall(): is successfully!
 DEBUG root [0x0000305c] [2018-08-10 14:49:26,490] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000305c] [2018-08-10 14:49:26,792] - ThreadPool::destroy(): waiting for thread(2)[0x1f598c8,0x1f5a288,], try=1
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,198] - TPThread::~TPThread(): 0x1f598c8
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,198] - TPThread::~TPThread(): 0x1f5a288
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,198] - ThreadPool::destroy(): successfully!
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,199] - Bundle::destroyObjPool(): size 15.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,199] - Channel::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,200] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,200] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,200] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,200] - Address::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,200] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x0000305c] [2018-08-10 14:49:27,201] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x0000305c] [2018-08-10 14:49:33,705] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x00003fd0] [2018-08-10 14:50:56,713] - 
  INFO root [0x00003fd0] [2018-08-10 14:50:56,717] - -----------------------------------------------------------------------------------------


  INFO root [0x00003fd0] [2018-08-10 14:50:56,718] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00003fd0] [2018-08-10 14:50:56,719] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00003fd0] [2018-08-10 14:50:56,719] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00003fd0] [2018-08-10 14:50:56,884] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10373 )
  INFO root [0x00003fd0] [2018-08-10 14:50:56,885] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10373, SOMAXCONN=5.
  INFO root [0x00003fd0] [2018-08-10 14:50:56,885] - server-configs:
  INFO root [0x00003fd0] [2018-08-10 14:50:56,885] - 	gameUpdateHertz : 10
  INFO root [0x00003fd0] [2018-08-10 14:50:56,885] - 	defaultViewRadius : 80
  INFO root [0x00003fd0] [2018-08-10 14:50:56,886] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003fd0] [2018-08-10 14:50:56,886] - 	entryScriptFile : kbemain
  INFO root [0x00003fd0] [2018-08-10 14:50:56,886] - 	internalAddr : 10.139.89.70:10373
  INFO root [0x00003fd0] [2018-08-10 14:50:56,886] - 	componentID : 8001
  INFO root [0x00003fd0] [2018-08-10 14:50:58,405] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 16760 ----
  INFO root [0x00003fd0] [2018-08-10 14:50:58,411] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00003fd0] [2018-08-10 14:50:58,423] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003fd0] [2018-08-10 14:50:58,423] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,580] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,580] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,581] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,586] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,587] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,587] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,588] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003fd0] [2018-08-10 14:50:58,663] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003fd0] [2018-08-10 14:50:58,721] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003fd0] [2018-08-10 14:50:58,722] - Script::install(): KBExtra is successfully!
  INFO root [0x00003fd0] [2018-08-10 14:50:58,790] - TelnetServer server is running on port 50000
  INFO root [0x00003fd0] [2018-08-10 14:50:59,487] - ---- cellapp is running ----
 DEBUG root [0x00003fd0] [2018-08-10 14:50:59,488] - Components::process(): Request for the process of identity...
  WARN root [0x00003fd0] [2018-08-10 14:51:05,722] - EntityApp::checkTickPeriod: tick took 6234% (6.23 seconds)!
  INFO root [0x00003fd0] [2018-08-10 14:51:06,789] - Components::findComponents: find logger(1)...
  INFO root [0x00003fd0] [2018-08-10 14:51:06,837] - Components::findComponents: found logger, addr:10.139.89.70:10370
  INFO root [0x00003fd0] [2018-08-10 14:51:06,837] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003fd0] [2018-08-10 14:51:06,837] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003fd0] [2018-08-10 14:51:06,838] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003fd0] [2018-08-10 14:51:06,941] - Components::findComponents: found dbmgr, addr:10.139.89.70:10367
  INFO root [0x00003fd0] [2018-08-10 14:51:06,942] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003fd0] [2018-08-10 14:51:06,942] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003fd0] [2018-08-10 14:51:06,942] - Components::findComponents: found dbmgr, addr:10.139.89.70:10367
  WARN root [0x00003fd0] [2018-08-10 14:51:07,943] - EntityApp::checkTickPeriod: tick took 1253% (1.25 seconds)!
  WARN root [0x00003fd0] [2018-08-10 14:51:07,943] - Forwarding logs to logger[10.139.89.70:10370/0/0/0]...
 ERROR root [0x00003fd0] [2018-08-10 14:51:21,616] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003fd0] [2018-08-10 14:51:21,621] - The following logs sent to logger failed:
  WARN root [0x00003fd0] [2018-08-10 14:51:21,622] - ==> [2018-08-10 14:51:21 610] TCPPacketReceiver::processPendingEvents(10.139.89.70:10370): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003fd0] [2018-08-10 14:51:21,622] - ==> [2018-08-10 14:51:21 618] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003fd0] [2018-08-10 14:51:21,769] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10367): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003fd0] [2018-08-10 14:51:21,773] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003fd0] [2018-08-10 14:51:21,778] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003fd0] [2018-08-10 14:51:21,778] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003fd0] [2018-08-10 14:51:21,779] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,779] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,780] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,805] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,805] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,806] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,806] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,806] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,806] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,806] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,806] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003fd0] [2018-08-10 14:51:21,834] - Script::uninstall(): is successfully!
 DEBUG root [0x00003fd0] [2018-08-10 14:51:21,835] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003fd0] [2018-08-10 14:51:22,135] - ThreadPool::destroy(): waiting for thread(2)[0x20599a8,0x20592c0,], try=1
  INFO root [0x00004028] [2018-08-10 14:53:19,559] - 
  INFO root [0x00004028] [2018-08-10 14:53:19,577] - -----------------------------------------------------------------------------------------


  INFO root [0x00004028] [2018-08-10 14:53:19,578] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00004028] [2018-08-10 14:53:19,579] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00004028] [2018-08-10 14:53:19,579] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00004028] [2018-08-10 14:53:19,681] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10440 )
  INFO root [0x00004028] [2018-08-10 14:53:19,682] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10440, SOMAXCONN=5.
  INFO root [0x00004028] [2018-08-10 14:53:19,682] - server-configs:
  INFO root [0x00004028] [2018-08-10 14:53:19,682] - 	gameUpdateHertz : 10
  INFO root [0x00004028] [2018-08-10 14:53:19,682] - 	defaultViewRadius : 80
  INFO root [0x00004028] [2018-08-10 14:53:19,683] - 	defaultViewHysteresisArea : 5
  INFO root [0x00004028] [2018-08-10 14:53:19,683] - 	entryScriptFile : kbemain
  INFO root [0x00004028] [2018-08-10 14:53:19,683] - 	internalAddr : 10.139.89.70:10440
  INFO root [0x00004028] [2018-08-10 14:53:19,683] - 	componentID : 8001
  INFO root [0x00004028] [2018-08-10 14:53:21,221] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 14812 ----
  INFO root [0x00004028] [2018-08-10 14:53:21,222] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00004028] [2018-08-10 14:53:21,222] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004028] [2018-08-10 14:53:21,222] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00004028] [2018-08-10 14:53:21,375] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004028] [2018-08-10 14:53:21,376] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00004028] [2018-08-10 14:53:21,377] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00004028] [2018-08-10 14:53:21,385] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004028] [2018-08-10 14:53:21,386] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00004028] [2018-08-10 14:53:21,386] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004028] [2018-08-10 14:53:21,387] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004028] [2018-08-10 14:53:21,450] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00004028] [2018-08-10 14:53:21,530] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00004028] [2018-08-10 14:53:21,531] - Script::install(): KBExtra is successfully!
  INFO root [0x00004028] [2018-08-10 14:53:21,589] - TelnetServer server is running on port 50000
  INFO root [0x00004028] [2018-08-10 14:53:22,078] - ---- cellapp is running ----
 DEBUG root [0x00004028] [2018-08-10 14:53:22,079] - Components::process(): Request for the process of identity...
  WARN root [0x00004028] [2018-08-10 14:53:22,437] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20963, errorno=10048
  WARN root [0x00004028] [2018-08-10 14:53:28,801] - EntityApp::checkTickPeriod: tick took 6722% (6.72 seconds)!
  INFO root [0x00004028] [2018-08-10 14:53:29,847] - Components::findComponents: find logger(1)...
  INFO root [0x00004028] [2018-08-10 14:53:29,917] - Components::findComponents: found logger, addr:10.139.89.70:10435
  INFO root [0x00004028] [2018-08-10 14:53:29,917] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00004028] [2018-08-10 14:53:29,917] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004028] [2018-08-10 14:53:29,918] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00004028] [2018-08-10 14:53:30,023] - Components::findComponents: found dbmgr, addr:10.139.89.70:10436
  INFO root [0x00004028] [2018-08-10 14:53:30,023] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00004028] [2018-08-10 14:53:30,024] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004028] [2018-08-10 14:53:30,024] - Components::findComponents: found dbmgr, addr:10.139.89.70:10436
  WARN root [0x00004028] [2018-08-10 14:53:31,024] - Forwarding logs to logger[10.139.89.70:10435/0/0/0]...
 ERROR root [0x00004028] [2018-08-10 14:53:33,777] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00004028] [2018-08-10 14:53:33,779] - The following logs sent to logger failed:
  WARN root [0x00004028] [2018-08-10 14:53:33,779] - ==> [2018-08-10 14:53:33 775] TCPPacketReceiver::processPendingEvents(10.139.89.70:10435): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004028] [2018-08-10 14:53:33,780] - ==> [2018-08-10 14:53:33 778] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00004028] [2018-08-10 14:53:34,079] - Components::findComponents: find baseappmgr(1)...
  INFO root [0x00004020] [2018-08-10 14:54:40,465] - 
  INFO root [0x00004020] [2018-08-10 14:54:40,501] - -----------------------------------------------------------------------------------------


  INFO root [0x00004020] [2018-08-10 14:54:40,507] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00004020] [2018-08-10 14:54:40,507] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00004020] [2018-08-10 14:54:40,508] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00004020] [2018-08-10 14:54:40,645] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10498 )
  INFO root [0x00004020] [2018-08-10 14:54:40,645] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10498, SOMAXCONN=5.
  INFO root [0x00004020] [2018-08-10 14:54:40,645] - server-configs:
  INFO root [0x00004020] [2018-08-10 14:54:40,645] - 	gameUpdateHertz : 10
  INFO root [0x00004020] [2018-08-10 14:54:40,645] - 	defaultViewRadius : 80
  INFO root [0x00004020] [2018-08-10 14:54:40,646] - 	defaultViewHysteresisArea : 5
  INFO root [0x00004020] [2018-08-10 14:54:40,646] - 	entryScriptFile : kbemain
  INFO root [0x00004020] [2018-08-10 14:54:40,646] - 	internalAddr : 10.139.89.70:10498
  INFO root [0x00004020] [2018-08-10 14:54:40,646] - 	componentID : 8001
  INFO root [0x00004020] [2018-08-10 14:54:40,993] - Components::findLogger: found logger, addr:10.139.89.70:10493
  INFO root [0x00004020] [2018-08-10 14:54:40,993] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00004020] [2018-08-10 14:54:40,994] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004020] [2018-08-10 14:54:41,010] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 15656 ----
  INFO root [0x00004020] [2018-08-10 14:54:41,039] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00004020] [2018-08-10 14:54:41,076] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004020] [2018-08-10 14:54:41,076] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00004020] [2018-08-10 14:54:41,312] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004020] [2018-08-10 14:54:41,312] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00004020] [2018-08-10 14:54:41,318] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00004020] [2018-08-10 14:54:41,325] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004020] [2018-08-10 14:54:41,326] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00004020] [2018-08-10 14:54:41,326] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004020] [2018-08-10 14:54:41,327] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004020] [2018-08-10 14:54:41,397] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00004020] [2018-08-10 14:54:41,467] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00004020] [2018-08-10 14:54:41,468] - Script::install(): KBExtra is successfully!
  INFO root [0x00004020] [2018-08-10 14:54:41,550] - TelnetServer server is running on port 50000
  INFO root [0x00004020] [2018-08-10 14:54:42,479] - ---- cellapp is running ----
 DEBUG root [0x00004020] [2018-08-10 14:54:42,499] - Components::process(): Request for the process of identity...
  WARN root [0x00004020] [2018-08-10 14:54:48,838] - Forwarding logs to logger[10.139.89.70:10493/0/0/0]...
 ERROR root [0x00004020] [2018-08-10 15:01:08,052] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00004020] [2018-08-10 15:01:08,055] - The following logs sent to logger failed:
  WARN root [0x00004020] [2018-08-10 15:01:08,056] - ==> [2018-08-10 15:01:08 047] TCPPacketReceiver::processPendingEvents(10.139.89.70:10493): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004020] [2018-08-10 15:01:08,056] - ==> [2018-08-10 15:01:08 053] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00004020] [2018-08-10 15:01:08,179] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10494): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004020] [2018-08-10 15:01:08,182] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00004020] [2018-08-10 15:01:08,184] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00004020] [2018-08-10 15:01:08,185] - Shutdowner::onShutdown: shutting down
  INFO root [0x00004020] [2018-08-10 15:01:08,185] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00004020] [2018-08-10 15:01:08,186] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00004020] [2018-08-10 15:01:08,186] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00004020] [2018-08-10 15:01:08,215] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004020] [2018-08-10 15:01:08,215] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00004020] [2018-08-10 15:01:08,215] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00004020] [2018-08-10 15:01:08,215] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004020] [2018-08-10 15:01:08,215] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00004020] [2018-08-10 15:01:08,215] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004020] [2018-08-10 15:01:08,217] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004020] [2018-08-10 15:01:08,217] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00004020] [2018-08-10 15:01:08,251] - Script::uninstall(): is successfully!
 DEBUG root [0x00004020] [2018-08-10 15:01:08,251] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00004020] [2018-08-10 15:01:08,552] - ThreadPool::destroy(): waiting for thread(2)[0x1fe9628,0x1fe9d10,], try=1
  INFO root [0x00003568] [2018-08-10 15:01:11,832] - 
  INFO root [0x00003568] [2018-08-10 15:01:11,845] - -----------------------------------------------------------------------------------------


  INFO root [0x00003568] [2018-08-10 15:01:11,846] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00003568] [2018-08-10 15:01:11,846] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00003568] [2018-08-10 15:01:11,847] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00003568] [2018-08-10 15:01:11,988] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10652 )
  INFO root [0x00003568] [2018-08-10 15:01:11,989] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10652, SOMAXCONN=5.
  INFO root [0x00003568] [2018-08-10 15:01:11,989] - server-configs:
  INFO root [0x00003568] [2018-08-10 15:01:11,989] - 	gameUpdateHertz : 10
  INFO root [0x00003568] [2018-08-10 15:01:11,989] - 	defaultViewRadius : 80
  INFO root [0x00003568] [2018-08-10 15:01:11,989] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003568] [2018-08-10 15:01:11,990] - 	entryScriptFile : kbemain
  INFO root [0x00003568] [2018-08-10 15:01:11,991] - 	internalAddr : 10.139.89.70:10652
  INFO root [0x00003568] [2018-08-10 15:01:11,991] - 	componentID : 8001
  INFO root [0x00003568] [2018-08-10 15:01:13,531] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 16336 ----
  INFO root [0x00003568] [2018-08-10 15:01:13,599] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00003568] [2018-08-10 15:01:13,640] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003568] [2018-08-10 15:01:13,640] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003568] [2018-08-10 15:01:14,000] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003568] [2018-08-10 15:01:14,001] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003568] [2018-08-10 15:01:14,002] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003568] [2018-08-10 15:01:14,007] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003568] [2018-08-10 15:01:14,007] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003568] [2018-08-10 15:01:14,008] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003568] [2018-08-10 15:01:14,009] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003568] [2018-08-10 15:01:14,104] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003568] [2018-08-10 15:01:14,181] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003568] [2018-08-10 15:01:14,182] - Script::install(): KBExtra is successfully!
  INFO root [0x00003568] [2018-08-10 15:01:14,274] - TelnetServer server is running on port 50000
  INFO root [0x00003568] [2018-08-10 15:01:14,990] - ---- cellapp is running ----
 DEBUG root [0x00003568] [2018-08-10 15:01:14,991] - Components::process(): Request for the process of identity...
  WARN root [0x00003568] [2018-08-10 15:01:21,270] - EntityApp::checkTickPeriod: tick took 6280% (6.28 seconds)!
  INFO root [0x00003568] [2018-08-10 15:01:22,282] - Components::findComponents: find logger(1)...
  INFO root [0x00003568] [2018-08-10 15:01:22,342] - Components::findComponents: found logger, addr:10.139.89.70:10647
  INFO root [0x00003568] [2018-08-10 15:01:22,342] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003568] [2018-08-10 15:01:22,342] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003568] [2018-08-10 15:01:22,343] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003568] [2018-08-10 15:01:22,448] - Components::findComponents: found dbmgr, addr:10.139.89.70:10648
  INFO root [0x00003568] [2018-08-10 15:01:22,448] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003568] [2018-08-10 15:01:22,449] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003568] [2018-08-10 15:01:22,449] - Components::findComponents: found dbmgr, addr:10.139.89.70:10648
  WARN root [0x00003568] [2018-08-10 15:01:23,450] - Forwarding logs to logger[10.139.89.70:10647/0/0/0]...
 ERROR root [0x00003568] [2018-08-10 15:04:37,768] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003568] [2018-08-10 15:04:37,772] - The following logs sent to logger failed:
  WARN root [0x00003568] [2018-08-10 15:04:37,772] - ==> [2018-08-10 15:04:37 758] TCPPacketReceiver::processPendingEvents(10.139.89.70:10647): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003568] [2018-08-10 15:04:37,772] - ==> [2018-08-10 15:04:37 769] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003568] [2018-08-10 15:04:37,955] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10648): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003568] [2018-08-10 15:04:37,965] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003568] [2018-08-10 15:04:37,975] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003568] [2018-08-10 15:04:37,975] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003568] [2018-08-10 15:04:37,976] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003568] [2018-08-10 15:04:37,976] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003568] [2018-08-10 15:04:37,976] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,001] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003568] [2018-08-10 15:04:38,002] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003568] [2018-08-10 15:04:38,002] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003568] [2018-08-10 15:04:38,002] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003568] [2018-08-10 15:04:38,002] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003568] [2018-08-10 15:04:38,003] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003568] [2018-08-10 15:04:38,003] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003568] [2018-08-10 15:04:38,003] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003568] [2018-08-10 15:04:38,034] - Script::uninstall(): is successfully!
 DEBUG root [0x00003568] [2018-08-10 15:04:38,034] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003568] [2018-08-10 15:04:38,337] - ThreadPool::destroy(): waiting for thread(2)[0x2029690,0x2029148,], try=1
 DEBUG root [0x00003568] [2018-08-10 15:04:38,743] - TPThread::~TPThread(): 0x2029690
 DEBUG root [0x00003568] [2018-08-10 15:04:38,743] - TPThread::~TPThread(): 0x2029148
 DEBUG root [0x00003568] [2018-08-10 15:04:38,743] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00003568] [2018-08-10 15:04:38,743] - Bundle::destroyObjPool(): size 27.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,744] - Channel::destroyObjPool(): size 12.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,744] - TCPPacket::destroyObjPool(): size 10.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,745] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,745] - EndPoint::destroyObjPool(): size 12.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,745] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,745] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00003568] [2018-08-10 15:04:38,746] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x00003568] [2018-08-10 15:04:38,747] - cellapp(8001) has shut down.
  INFO root [0x0000138c] [2018-08-10 15:04:41,461] - 
  INFO root [0x0000138c] [2018-08-10 15:04:41,498] - -----------------------------------------------------------------------------------------


  INFO root [0x0000138c] [2018-08-10 15:04:41,500] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x0000138c] [2018-08-10 15:04:41,501] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x0000138c] [2018-08-10 15:04:41,501] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x0000138c] [2018-08-10 15:04:41,676] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10782 )
  INFO root [0x0000138c] [2018-08-10 15:04:41,676] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10782, SOMAXCONN=5.
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - server-configs:
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - 	gameUpdateHertz : 10
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - 	defaultViewRadius : 80
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - 	entryScriptFile : kbemain
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - 	internalAddr : 10.139.89.70:10782
  INFO root [0x0000138c] [2018-08-10 15:04:41,677] - 	componentID : 8001
  INFO root [0x0000138c] [2018-08-10 15:04:42,032] - Components::findLogger: found logger, addr:10.139.89.70:10777
  INFO root [0x0000138c] [2018-08-10 15:04:42,032] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x0000138c] [2018-08-10 15:04:42,033] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000138c] [2018-08-10 15:04:42,070] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 16396 ----
  INFO root [0x0000138c] [2018-08-10 15:04:42,102] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x0000138c] [2018-08-10 15:04:42,107] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000138c] [2018-08-10 15:04:42,108] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,304] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,305] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,306] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,314] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,314] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,314] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,315] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000138c] [2018-08-10 15:04:42,388] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000138c] [2018-08-10 15:04:42,450] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000138c] [2018-08-10 15:04:42,451] - Script::install(): KBExtra is successfully!
  INFO root [0x0000138c] [2018-08-10 15:04:42,517] - TelnetServer server is running on port 50000
  INFO root [0x0000138c] [2018-08-10 15:04:43,327] - ---- cellapp is running ----
 DEBUG root [0x0000138c] [2018-08-10 15:04:43,358] - Components::process(): Request for the process of identity...
  WARN root [0x0000138c] [2018-08-10 15:04:49,684] - Forwarding logs to logger[10.139.89.70:10777/0/0/0]...
 ERROR root [0x0000138c] [2018-08-10 15:05:17,133] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000138c] [2018-08-10 15:05:17,134] - The following logs sent to logger failed:
  WARN root [0x0000138c] [2018-08-10 15:05:17,135] - ==> [2018-08-10 15:05:17 131] TCPPacketReceiver::processPendingEvents(10.139.89.70:10777): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000138c] [2018-08-10 15:05:17,135] - ==> [2018-08-10 15:05:17 134] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000138c] [2018-08-10 15:05:17,270] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10778): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000138c] [2018-08-10 15:05:17,281] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000138c] [2018-08-10 15:05:17,284] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000138c] [2018-08-10 15:05:17,285] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000138c] [2018-08-10 15:05:17,285] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,286] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,286] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,306] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,306] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,306] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,306] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,307] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,307] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,307] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,307] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000138c] [2018-08-10 15:05:17,328] - Script::uninstall(): is successfully!
 DEBUG root [0x0000138c] [2018-08-10 15:05:17,328] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000138c] [2018-08-10 15:05:17,630] - ThreadPool::destroy(): waiting for thread(2)[0x1f290e8,0x1f29428,], try=1
  INFO root [0x00003060] [2018-08-10 15:05:20,449] - 
  INFO root [0x00003060] [2018-08-10 15:05:20,450] - -----------------------------------------------------------------------------------------


  INFO root [0x00003060] [2018-08-10 15:05:20,452] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00003060] [2018-08-10 15:05:20,452] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00003060] [2018-08-10 15:05:20,452] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00003060] [2018-08-10 15:05:20,463] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10815 )
  INFO root [0x00003060] [2018-08-10 15:05:20,463] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10815, SOMAXCONN=5.
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - server-configs:
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - 	gameUpdateHertz : 10
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - 	defaultViewRadius : 80
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - 	entryScriptFile : kbemain
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - 	internalAddr : 10.139.89.70:10815
  INFO root [0x00003060] [2018-08-10 15:05:20,464] - 	componentID : 8001
  INFO root [0x00003060] [2018-08-10 15:05:21,975] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 10484 ----
  INFO root [0x00003060] [2018-08-10 15:05:21,982] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00003060] [2018-08-10 15:05:21,983] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003060] [2018-08-10 15:05:21,983] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003060] [2018-08-10 15:05:22,218] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003060] [2018-08-10 15:05:22,219] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003060] [2018-08-10 15:05:22,220] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003060] [2018-08-10 15:05:22,245] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003060] [2018-08-10 15:05:22,246] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003060] [2018-08-10 15:05:22,246] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003060] [2018-08-10 15:05:22,247] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003060] [2018-08-10 15:05:22,325] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003060] [2018-08-10 15:05:22,418] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003060] [2018-08-10 15:05:22,419] - Script::install(): KBExtra is successfully!
  INFO root [0x00003060] [2018-08-10 15:05:22,531] - TelnetServer server is running on port 50000
  INFO root [0x00003060] [2018-08-10 15:05:23,416] - ---- cellapp is running ----
 DEBUG root [0x00003060] [2018-08-10 15:05:23,416] - Components::process(): Request for the process of identity...
  WARN root [0x00003060] [2018-08-10 15:05:29,803] - EntityApp::checkTickPeriod: tick took 6387% (6.39 seconds)!
  INFO root [0x00003060] [2018-08-10 15:05:30,857] - Components::findComponents: find logger(1)...
  INFO root [0x00003060] [2018-08-10 15:05:30,902] - Components::findComponents: found logger, addr:10.139.89.70:10810
  INFO root [0x00003060] [2018-08-10 15:05:30,902] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003060] [2018-08-10 15:05:30,903] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003060] [2018-08-10 15:05:30,904] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003060] [2018-08-10 15:05:31,008] - Components::findComponents: found dbmgr, addr:10.139.89.70:10811
  INFO root [0x00003060] [2018-08-10 15:05:31,008] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003060] [2018-08-10 15:05:31,009] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003060] [2018-08-10 15:05:31,009] - Components::findComponents: found dbmgr, addr:10.139.89.70:10811
  WARN root [0x00003060] [2018-08-10 15:05:32,009] - Forwarding logs to logger[10.139.89.70:10810/0/0/0]...
 ERROR root [0x00003060] [2018-08-10 15:06:42,212] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003060] [2018-08-10 15:06:42,219] - The following logs sent to logger failed:
  WARN root [0x00003060] [2018-08-10 15:06:42,220] - ==> [2018-08-10 15:06:42 206] TCPPacketReceiver::processPendingEvents(10.139.89.70:10810): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003060] [2018-08-10 15:06:42,221] - ==> [2018-08-10 15:06:42 214] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003060] [2018-08-10 15:06:42,386] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10811): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003060] [2018-08-10 15:06:42,390] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003060] [2018-08-10 15:06:42,395] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003060] [2018-08-10 15:06:42,396] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003060] [2018-08-10 15:06:42,397] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003060] [2018-08-10 15:06:42,400] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003060] [2018-08-10 15:06:42,400] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003060] [2018-08-10 15:06:42,425] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003060] [2018-08-10 15:06:42,425] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003060] [2018-08-10 15:06:42,426] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003060] [2018-08-10 15:06:42,426] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003060] [2018-08-10 15:06:42,426] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003060] [2018-08-10 15:06:42,426] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003060] [2018-08-10 15:06:42,427] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003060] [2018-08-10 15:06:42,427] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003060] [2018-08-10 15:06:42,462] - Script::uninstall(): is successfully!
 DEBUG root [0x00003060] [2018-08-10 15:06:42,463] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003060] [2018-08-10 15:06:42,765] - ThreadPool::destroy(): waiting for thread(2)[0x1d89b70,0x1d89ca8,], try=1
 DEBUG root [0x00003060] [2018-08-10 15:06:43,169] - TPThread::~TPThread(): 0x1d89b70
 DEBUG root [0x00003060] [2018-08-10 15:06:43,169] - TPThread::~TPThread(): 0x1d89ca8
 DEBUG root [0x00003060] [2018-08-10 15:06:43,169] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00003060] [2018-08-10 15:06:43,170] - Bundle::destroyObjPool(): size 27.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,170] - Channel::destroyObjPool(): size 12.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,170] - TCPPacket::destroyObjPool(): size 10.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,170] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,170] - EndPoint::destroyObjPool(): size 12.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,171] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,171] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00003060] [2018-08-10 15:06:43,171] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x00003060] [2018-08-10 15:06:43,171] - cellapp(8001) has shut down.
  INFO root [0x000024f0] [2018-08-10 15:07:41,147] - 
  INFO root [0x000024f0] [2018-08-10 15:07:41,152] - -----------------------------------------------------------------------------------------


  INFO root [0x000024f0] [2018-08-10 15:07:41,154] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x000024f0] [2018-08-10 15:07:41,155] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x000024f0] [2018-08-10 15:07:41,155] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x000024f0] [2018-08-10 15:07:41,165] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10928 )
  INFO root [0x000024f0] [2018-08-10 15:07:41,165] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10928, SOMAXCONN=5.
  INFO root [0x000024f0] [2018-08-10 15:07:41,165] - server-configs:
  INFO root [0x000024f0] [2018-08-10 15:07:41,165] - 	gameUpdateHertz : 10
  INFO root [0x000024f0] [2018-08-10 15:07:41,166] - 	defaultViewRadius : 80
  INFO root [0x000024f0] [2018-08-10 15:07:41,166] - 	defaultViewHysteresisArea : 5
  INFO root [0x000024f0] [2018-08-10 15:07:41,166] - 	entryScriptFile : kbemain
  INFO root [0x000024f0] [2018-08-10 15:07:41,166] - 	internalAddr : 10.139.89.70:10928
  INFO root [0x000024f0] [2018-08-10 15:07:41,166] - 	componentID : 8001
  INFO root [0x000024f0] [2018-08-10 15:07:42,676] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 8868 ----
  INFO root [0x000024f0] [2018-08-10 15:07:42,685] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x000024f0] [2018-08-10 15:07:42,686] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000024f0] [2018-08-10 15:07:42,686] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000024f0] [2018-08-10 15:07:42,996] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000024f0] [2018-08-10 15:07:42,997] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000024f0] [2018-08-10 15:07:42,997] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000024f0] [2018-08-10 15:07:43,010] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000024f0] [2018-08-10 15:07:43,010] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000024f0] [2018-08-10 15:07:43,011] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000024f0] [2018-08-10 15:07:43,011] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000024f0] [2018-08-10 15:07:43,093] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000024f0] [2018-08-10 15:07:43,194] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000024f0] [2018-08-10 15:07:43,194] - Script::install(): KBExtra is successfully!
  INFO root [0x000024f0] [2018-08-10 15:07:43,303] - TelnetServer server is running on port 50000
  INFO root [0x000024f0] [2018-08-10 15:07:44,046] - ---- cellapp is running ----
 DEBUG root [0x000024f0] [2018-08-10 15:07:44,047] - Components::process(): Request for the process of identity...
  WARN root [0x000024f0] [2018-08-10 15:07:50,313] - EntityApp::checkTickPeriod: tick took 6266% (6.27 seconds)!
  INFO root [0x000024f0] [2018-08-10 15:07:51,347] - Components::findComponents: find logger(1)...
  INFO root [0x000024f0] [2018-08-10 15:07:51,375] - Components::findComponents: found logger, addr:10.139.89.70:10922
  INFO root [0x000024f0] [2018-08-10 15:07:51,376] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000024f0] [2018-08-10 15:07:51,376] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000024f0] [2018-08-10 15:07:51,377] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000024f0] [2018-08-10 15:07:51,481] - Components::findComponents: found dbmgr, addr:10.139.89.70:10924
  INFO root [0x000024f0] [2018-08-10 15:07:51,482] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000024f0] [2018-08-10 15:07:51,482] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000024f0] [2018-08-10 15:07:51,482] - Components::findComponents: found dbmgr, addr:10.139.89.70:10924
  WARN root [0x000024f0] [2018-08-10 15:07:52,482] - EntityApp::checkTickPeriod: tick took 1235% (1.24 seconds)!
  WARN root [0x000024f0] [2018-08-10 15:07:52,482] - Forwarding logs to logger[10.139.89.70:10922/0/0/0]...
 ERROR root [0x000024f0] [2018-08-10 15:24:04,827] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000024f0] [2018-08-10 15:24:04,830] - The following logs sent to logger failed:
  WARN root [0x000024f0] [2018-08-10 15:24:04,830] - ==> [2018-08-10 15:24:04 824] TCPPacketReceiver::processPendingEvents(10.139.89.70:10922): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000024f0] [2018-08-10 15:24:04,830] - ==> [2018-08-10 15:24:04 827] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000024f0] [2018-08-10 15:24:04,944] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10924): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000024f0] [2018-08-10 15:24:04,949] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000024f0] [2018-08-10 15:24:04,954] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000024f0] [2018-08-10 15:24:04,955] - Shutdowner::onShutdown: shutting down
  INFO root [0x000024f0] [2018-08-10 15:24:04,955] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,956] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,956] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,976] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,977] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,978] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,978] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,978] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,978] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,978] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000024f0] [2018-08-10 15:24:04,978] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000024f0] [2018-08-10 15:24:05,005] - Script::uninstall(): is successfully!
 DEBUG root [0x000024f0] [2018-08-10 15:24:05,005] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000024f0] [2018-08-10 15:24:05,306] - ThreadPool::destroy(): waiting for thread(2)[0x1fda258,0x1fda120,], try=1
  INFO root [0x00003d08] [2018-08-10 15:24:08,215] - 
  INFO root [0x00003d08] [2018-08-10 15:24:08,257] - -----------------------------------------------------------------------------------------


  INFO root [0x00003d08] [2018-08-10 15:24:08,259] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00003d08] [2018-08-10 15:24:08,259] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00003d08] [2018-08-10 15:24:08,259] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00003d08] [2018-08-10 15:24:08,381] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:11452 )
  INFO root [0x00003d08] [2018-08-10 15:24:08,381] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:11452, SOMAXCONN=5.
  INFO root [0x00003d08] [2018-08-10 15:24:08,381] - server-configs:
  INFO root [0x00003d08] [2018-08-10 15:24:08,381] - 	gameUpdateHertz : 10
  INFO root [0x00003d08] [2018-08-10 15:24:08,382] - 	defaultViewRadius : 80
  INFO root [0x00003d08] [2018-08-10 15:24:08,382] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003d08] [2018-08-10 15:24:08,382] - 	entryScriptFile : kbemain
  INFO root [0x00003d08] [2018-08-10 15:24:08,382] - 	internalAddr : 10.139.89.70:11452
  INFO root [0x00003d08] [2018-08-10 15:24:08,382] - 	componentID : 8001
  INFO root [0x00003d08] [2018-08-10 15:24:08,697] - Components::findLogger: found logger, addr:10.139.89.70:11446
  INFO root [0x00003d08] [2018-08-10 15:24:08,698] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003d08] [2018-08-10 15:24:08,698] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d08] [2018-08-10 15:24:08,710] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 17840 ----
  INFO root [0x00003d08] [2018-08-10 15:24:08,711] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00003d08] [2018-08-10 15:24:08,711] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003d08] [2018-08-10 15:24:08,712] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,865] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,865] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,866] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,871] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,872] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,872] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,873] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003d08] [2018-08-10 15:24:08,935] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003d08] [2018-08-10 15:24:09,000] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003d08] [2018-08-10 15:24:09,001] - Script::install(): KBExtra is successfully!
  INFO root [0x00003d08] [2018-08-10 15:24:09,066] - TelnetServer server is running on port 50000
  INFO root [0x00003d08] [2018-08-10 15:24:09,929] - ---- cellapp is running ----
 DEBUG root [0x00003d08] [2018-08-10 15:24:09,954] - Components::process(): Request for the process of identity...
  WARN root [0x00003d08] [2018-08-10 15:24:10,436] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20086, errorno=10048
  WARN root [0x00003d08] [2018-08-10 15:24:16,739] - Forwarding logs to logger[10.139.89.70:11446/0/0/0]...
 ERROR root [0x00003d08] [2018-08-10 15:31:02,453] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003d08] [2018-08-10 15:31:02,455] - The following logs sent to logger failed:
  WARN root [0x00003d08] [2018-08-10 15:31:02,455] - ==> [2018-08-10 15:31:02 445] TCPPacketReceiver::processPendingEvents(10.139.89.70:11446): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d08] [2018-08-10 15:31:02,455] - ==> [2018-08-10 15:31:02 454] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003d08] [2018-08-10 15:31:02,653] - TCPPacketReceiver::processPendingEvents(10.139.89.70:11447): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d08] [2018-08-10 15:31:02,654] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003d08] [2018-08-10 15:31:02,659] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003d08] [2018-08-10 15:31:02,664] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003d08] [2018-08-10 15:31:02,665] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,667] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,668] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,690] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,690] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,690] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,691] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,691] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,691] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,691] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,691] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003d08] [2018-08-10 15:31:02,719] - Script::uninstall(): is successfully!
 DEBUG root [0x00003d08] [2018-08-10 15:31:02,720] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003d08] [2018-08-10 15:31:03,023] - ThreadPool::destroy(): waiting for thread(2)[0x20d9928,0x20d9990,], try=1
  INFO root [0x000044e8] [2018-08-10 15:31:06,187] - 
  INFO root [0x000044e8] [2018-08-10 15:31:06,199] - -----------------------------------------------------------------------------------------


  INFO root [0x000044e8] [2018-08-10 15:31:06,201] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x000044e8] [2018-08-10 15:31:06,201] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x000044e8] [2018-08-10 15:31:06,202] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x000044e8] [2018-08-10 15:31:06,267] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:11592 )
  INFO root [0x000044e8] [2018-08-10 15:31:06,267] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:11592, SOMAXCONN=5.
  INFO root [0x000044e8] [2018-08-10 15:31:06,267] - server-configs:
  INFO root [0x000044e8] [2018-08-10 15:31:06,268] - 	gameUpdateHertz : 10
  INFO root [0x000044e8] [2018-08-10 15:31:06,268] - 	defaultViewRadius : 80
  INFO root [0x000044e8] [2018-08-10 15:31:06,268] - 	defaultViewHysteresisArea : 5
  INFO root [0x000044e8] [2018-08-10 15:31:06,268] - 	entryScriptFile : kbemain
  INFO root [0x000044e8] [2018-08-10 15:31:06,268] - 	internalAddr : 10.139.89.70:11592
  INFO root [0x000044e8] [2018-08-10 15:31:06,268] - 	componentID : 8001
  INFO root [0x000044e8] [2018-08-10 15:31:07,809] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 14736 ----
  INFO root [0x000044e8] [2018-08-10 15:31:07,816] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x000044e8] [2018-08-10 15:31:07,829] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000044e8] [2018-08-10 15:31:07,830] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,029] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,030] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,031] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,036] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,036] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,037] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,038] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,109] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000044e8] [2018-08-10 15:31:08,186] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000044e8] [2018-08-10 15:31:08,187] - Script::install(): KBExtra is successfully!
  INFO root [0x000044e8] [2018-08-10 15:31:08,255] - TelnetServer server is running on port 50000
  INFO root [0x000044e8] [2018-08-10 15:31:08,765] - ---- cellapp is running ----
 DEBUG root [0x000044e8] [2018-08-10 15:31:08,766] - Components::process(): Request for the process of identity...
  WARN root [0x000044e8] [2018-08-10 15:31:14,997] - EntityApp::checkTickPeriod: tick took 6231% (6.23 seconds)!
  INFO root [0x000044e8] [2018-08-10 15:31:16,061] - Components::findComponents: find logger(1)...
  INFO root [0x000044e8] [2018-08-10 15:31:16,147] - Components::findComponents: found logger, addr:10.139.89.70:11586
  INFO root [0x000044e8] [2018-08-10 15:31:16,147] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000044e8] [2018-08-10 15:31:16,147] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000044e8] [2018-08-10 15:31:16,148] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000044e8] [2018-08-10 15:31:16,252] - Components::findComponents: found dbmgr, addr:10.139.89.70:11588
  INFO root [0x000044e8] [2018-08-10 15:31:16,252] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000044e8] [2018-08-10 15:31:16,252] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000044e8] [2018-08-10 15:31:16,252] - Components::findComponents: found dbmgr, addr:10.139.89.70:11588
  WARN root [0x000044e8] [2018-08-10 15:31:17,253] - Forwarding logs to logger[10.139.89.70:11586/0/0/0]...
 ERROR root [0x000044e8] [2018-08-10 15:49:03,487] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000044e8] [2018-08-10 15:49:03,498] - The following logs sent to logger failed:
  WARN root [0x000044e8] [2018-08-10 15:49:03,499] - ==> [2018-08-10 15:49:03 487] TCPPacketReceiver::processPendingEvents(10.139.89.70:11586): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000044e8] [2018-08-10 15:49:03,499] - ==> [2018-08-10 15:49:03 489] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000044e8] [2018-08-10 15:49:03,683] - TCPPacketReceiver::processPendingEvents(10.139.89.70:11588): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000044e8] [2018-08-10 15:49:03,688] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000044e8] [2018-08-10 15:49:03,742] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000044e8] [2018-08-10 15:49:03,745] - Shutdowner::onShutdown: shutting down
  INFO root [0x000044e8] [2018-08-10 15:49:03,746] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,748] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,749] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,784] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,784] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,784] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,784] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,784] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,785] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,786] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,786] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000044e8] [2018-08-10 15:49:03,839] - Script::uninstall(): is successfully!
 DEBUG root [0x000044e8] [2018-08-10 15:49:03,843] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000044e8] [2018-08-10 15:49:04,152] - ThreadPool::destroy(): waiting for thread(2)[0x2039350,0x2039690,], try=1
  INFO root [0x000041fc] [2018-08-10 15:49:07,023] - 
  INFO root [0x000041fc] [2018-08-10 15:49:07,077] - -----------------------------------------------------------------------------------------


  INFO root [0x000041fc] [2018-08-10 15:49:07,078] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x000041fc] [2018-08-10 15:49:07,079] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x000041fc] [2018-08-10 15:49:07,079] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x000041fc] [2018-08-10 15:49:07,220] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:11810 )
  INFO root [0x000041fc] [2018-08-10 15:49:07,222] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:11810, SOMAXCONN=5.
  INFO root [0x000041fc] [2018-08-10 15:49:07,222] - server-configs:
  INFO root [0x000041fc] [2018-08-10 15:49:07,222] - 	gameUpdateHertz : 10
  INFO root [0x000041fc] [2018-08-10 15:49:07,222] - 	defaultViewRadius : 80
  INFO root [0x000041fc] [2018-08-10 15:49:07,222] - 	defaultViewHysteresisArea : 5
  INFO root [0x000041fc] [2018-08-10 15:49:07,222] - 	entryScriptFile : kbemain
  INFO root [0x000041fc] [2018-08-10 15:49:07,223] - 	internalAddr : 10.139.89.70:11810
  INFO root [0x000041fc] [2018-08-10 15:49:07,223] - 	componentID : 8001
  INFO root [0x000041fc] [2018-08-10 15:49:08,790] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 14576 ----
  INFO root [0x000041fc] [2018-08-10 15:49:08,828] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x000041fc] [2018-08-10 15:49:08,894] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000041fc] [2018-08-10 15:49:08,895] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,244] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,245] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,248] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,254] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,255] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,255] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,257] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,332] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000041fc] [2018-08-10 15:49:09,398] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000041fc] [2018-08-10 15:49:09,399] - Script::install(): KBExtra is successfully!
  INFO root [0x000041fc] [2018-08-10 15:49:09,459] - TelnetServer server is running on port 50000
  INFO root [0x000041fc] [2018-08-10 15:49:09,886] - ---- cellapp is running ----
 DEBUG root [0x000041fc] [2018-08-10 15:49:09,887] - Components::process(): Request for the process of identity...
  WARN root [0x000041fc] [2018-08-10 15:49:16,129] - EntityApp::checkTickPeriod: tick took 6242% (6.24 seconds)!
  INFO root [0x000041fc] [2018-08-10 15:49:17,214] - Components::findComponents: find logger(1)...
  INFO root [0x000041fc] [2018-08-10 15:49:17,227] - Components::findComponents: found logger, addr:10.139.89.70:11806
  INFO root [0x000041fc] [2018-08-10 15:49:17,228] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000041fc] [2018-08-10 15:49:17,228] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000041fc] [2018-08-10 15:49:17,229] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000041fc] [2018-08-10 15:49:17,332] - Components::findComponents: found dbmgr, addr:10.139.89.70:11805
  INFO root [0x000041fc] [2018-08-10 15:49:17,332] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000041fc] [2018-08-10 15:49:17,333] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000041fc] [2018-08-10 15:49:17,333] - Components::findComponents: found dbmgr, addr:10.139.89.70:11805
  WARN root [0x000041fc] [2018-08-10 15:49:18,333] - Forwarding logs to logger[10.139.89.70:11806/0/0/0]...
 ERROR root [0x000041fc] [2018-08-10 16:19:40,343] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000041fc] [2018-08-10 16:19:40,355] - The following logs sent to logger failed:
  WARN root [0x000041fc] [2018-08-10 16:19:40,356] - ==> [2018-08-10 16:19:40 338] TCPPacketReceiver::processPendingEvents(10.139.89.70:11806): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000041fc] [2018-08-10 16:19:40,356] - ==> [2018-08-10 16:19:40 344] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000041fc] [2018-08-10 16:19:40,550] - TCPPacketReceiver::processPendingEvents(10.139.89.70:11805): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000041fc] [2018-08-10 16:19:40,556] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000041fc] [2018-08-10 16:19:40,564] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000041fc] [2018-08-10 16:19:40,565] - Shutdowner::onShutdown: shutting down
  INFO root [0x000041fc] [2018-08-10 16:19:40,566] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,567] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,567] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,590] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,591] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,591] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,591] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,591] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,592] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,593] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,594] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000041fc] [2018-08-10 16:19:40,634] - Script::uninstall(): is successfully!
 DEBUG root [0x000041fc] [2018-08-10 16:19:40,634] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000041fc] [2018-08-10 16:19:40,935] - ThreadPool::destroy(): waiting for thread(2)[0x20429a0,0x2042730,], try=1
  INFO root [0x00001d00] [2018-08-10 16:19:43,489] - 
  INFO root [0x00001d00] [2018-08-10 16:19:43,501] - -----------------------------------------------------------------------------------------


  INFO root [0x00001d00] [2018-08-10 16:19:43,503] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00001d00] [2018-08-10 16:19:43,503] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00001d00] [2018-08-10 16:19:43,503] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00001d00] [2018-08-10 16:19:43,547] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12438 )
  INFO root [0x00001d00] [2018-08-10 16:19:43,548] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12438, SOMAXCONN=5.
  INFO root [0x00001d00] [2018-08-10 16:19:43,548] - server-configs:
  INFO root [0x00001d00] [2018-08-10 16:19:43,548] - 	gameUpdateHertz : 10
  INFO root [0x00001d00] [2018-08-10 16:19:43,548] - 	defaultViewRadius : 80
  INFO root [0x00001d00] [2018-08-10 16:19:43,548] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001d00] [2018-08-10 16:19:43,549] - 	entryScriptFile : kbemain
  INFO root [0x00001d00] [2018-08-10 16:19:43,549] - 	internalAddr : 10.139.89.70:12438
  INFO root [0x00001d00] [2018-08-10 16:19:43,549] - 	componentID : 8001
  INFO root [0x00001d00] [2018-08-10 16:19:45,060] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 15436 ----
  INFO root [0x00001d00] [2018-08-10 16:19:45,061] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00001d00] [2018-08-10 16:19:45,061] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001d00] [2018-08-10 16:19:45,061] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,222] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,223] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,223] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,234] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,234] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,235] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,236] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001d00] [2018-08-10 16:19:45,305] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001d00] [2018-08-10 16:19:45,364] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001d00] [2018-08-10 16:19:45,364] - Script::install(): KBExtra is successfully!
  INFO root [0x00001d00] [2018-08-10 16:19:45,434] - TelnetServer server is running on port 50000
  INFO root [0x00001d00] [2018-08-10 16:19:46,159] - ---- cellapp is running ----
 DEBUG root [0x00001d00] [2018-08-10 16:19:46,160] - Components::process(): Request for the process of identity...
  WARN root [0x00001d00] [2018-08-10 16:19:52,467] - EntityApp::checkTickPeriod: tick took 6307% (6.31 seconds)!
  INFO root [0x00001d00] [2018-08-10 16:19:53,530] - Components::findComponents: find logger(1)...
  INFO root [0x00001d00] [2018-08-10 16:19:53,603] - Components::findComponents: found logger, addr:10.139.89.70:12437
  INFO root [0x00001d00] [2018-08-10 16:19:53,604] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00001d00] [2018-08-10 16:19:53,604] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d00] [2018-08-10 16:19:53,605] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001d00] [2018-08-10 16:19:53,708] - Components::findComponents: found dbmgr, addr:10.139.89.70:12436
  INFO root [0x00001d00] [2018-08-10 16:19:53,709] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00001d00] [2018-08-10 16:19:53,709] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d00] [2018-08-10 16:19:53,709] - Components::findComponents: found dbmgr, addr:10.139.89.70:12436
  WARN root [0x00001d00] [2018-08-10 16:19:54,709] - Forwarding logs to logger[10.139.89.70:12437/0/0/0]...
 ERROR root [0x00001d00] [2018-08-10 16:43:18,972] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001d00] [2018-08-10 16:43:18,975] - The following logs sent to logger failed:
  WARN root [0x00001d00] [2018-08-10 16:43:18,976] - ==> [2018-08-10 16:43:18 963] TCPPacketReceiver::processPendingEvents(10.139.89.70:12437): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d00] [2018-08-10 16:43:18,976] - ==> [2018-08-10 16:43:18 972] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001d00] [2018-08-10 16:43:19,137] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12436): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d00] [2018-08-10 16:43:19,141] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001d00] [2018-08-10 16:43:19,144] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001d00] [2018-08-10 16:43:19,145] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001d00] [2018-08-10 16:43:19,145] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,146] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,146] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,174] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,174] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,175] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,175] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,175] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,175] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,175] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,175] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001d00] [2018-08-10 16:43:19,221] - Script::uninstall(): is successfully!
 DEBUG root [0x00001d00] [2018-08-10 16:43:19,221] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001d00] [2018-08-10 16:43:19,523] - ThreadPool::destroy(): waiting for thread(2)[0x1ec90b0,0x1ec9458,], try=1
  INFO root [0x00003dd8] [2018-08-10 16:43:22,426] - 
  INFO root [0x00003dd8] [2018-08-10 16:43:22,447] - -----------------------------------------------------------------------------------------


  INFO root [0x00003dd8] [2018-08-10 16:43:22,448] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00003dd8] [2018-08-10 16:43:22,449] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00003dd8] [2018-08-10 16:43:22,449] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00003dd8] [2018-08-10 16:43:22,506] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12763 )
  INFO root [0x00003dd8] [2018-08-10 16:43:22,506] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12763, SOMAXCONN=5.
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - server-configs:
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - 	gameUpdateHertz : 10
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - 	defaultViewRadius : 80
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - 	entryScriptFile : kbemain
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - 	internalAddr : 10.139.89.70:12763
  INFO root [0x00003dd8] [2018-08-10 16:43:22,507] - 	componentID : 8001
  INFO root [0x00003dd8] [2018-08-10 16:43:24,022] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 17920 ----
  INFO root [0x00003dd8] [2018-08-10 16:43:24,040] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00003dd8] [2018-08-10 16:43:24,041] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003dd8] [2018-08-10 16:43:24,041] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,321] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,321] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,322] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,344] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,345] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,346] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,346] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003dd8] [2018-08-10 16:43:24,433] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003dd8] [2018-08-10 16:43:24,521] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003dd8] [2018-08-10 16:43:24,521] - Script::install(): KBExtra is successfully!
  INFO root [0x00003dd8] [2018-08-10 16:43:24,616] - TelnetServer server is running on port 50000
  INFO root [0x00003dd8] [2018-08-10 16:43:25,429] - ---- cellapp is running ----
 DEBUG root [0x00003dd8] [2018-08-10 16:43:25,430] - Components::process(): Request for the process of identity...
  WARN root [0x00003dd8] [2018-08-10 16:43:31,650] - EntityApp::checkTickPeriod: tick took 6220% (6.22 seconds)!
  INFO root [0x00003dd8] [2018-08-10 16:43:32,731] - Components::findComponents: find logger(1)...
  INFO root [0x00003dd8] [2018-08-10 16:43:32,828] - Components::findComponents: found logger, addr:10.139.89.70:12758
  INFO root [0x00003dd8] [2018-08-10 16:43:32,829] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003dd8] [2018-08-10 16:43:32,829] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003dd8] [2018-08-10 16:43:32,831] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003dd8] [2018-08-10 16:43:32,936] - Components::findComponents: found dbmgr, addr:10.139.89.70:12759
  INFO root [0x00003dd8] [2018-08-10 16:43:32,937] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003dd8] [2018-08-10 16:43:32,937] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003dd8] [2018-08-10 16:43:32,937] - Components::findComponents: found dbmgr, addr:10.139.89.70:12759
  WARN root [0x00003dd8] [2018-08-10 16:43:33,937] - EntityApp::checkTickPeriod: tick took 1306% (1.31 seconds)!
  WARN root [0x00003dd8] [2018-08-10 16:43:33,937] - Forwarding logs to logger[10.139.89.70:12758/0/0/0]...
 ERROR root [0x00003dd8] [2018-08-10 16:50:03,556] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003dd8] [2018-08-10 16:50:03,563] - The following logs sent to logger failed:
  WARN root [0x00003dd8] [2018-08-10 16:50:03,565] - ==> [2018-08-10 16:50:03 548] TCPPacketReceiver::processPendingEvents(10.139.89.70:12758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003dd8] [2018-08-10 16:50:03,566] - ==> [2018-08-10 16:50:03 557] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003dd8] [2018-08-10 16:50:03,756] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12759): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003dd8] [2018-08-10 16:50:03,767] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003dd8] [2018-08-10 16:50:03,781] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003dd8] [2018-08-10 16:50:03,788] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003dd8] [2018-08-10 16:50:03,788] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,789] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,789] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,813] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,815] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,815] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,815] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,815] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,816] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,816] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,816] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003dd8] [2018-08-10 16:50:03,844] - Script::uninstall(): is successfully!
 DEBUG root [0x00003dd8] [2018-08-10 16:50:03,846] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003dd8] [2018-08-10 16:50:04,146] - ThreadPool::destroy(): waiting for thread(2)[0x1f49cb0,0x1f49700,], try=1
  INFO root [0x00003a70] [2018-08-10 16:50:07,176] - 
  INFO root [0x00003a70] [2018-08-10 16:50:07,213] - -----------------------------------------------------------------------------------------


  INFO root [0x00003a70] [2018-08-10 16:50:07,214] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00003a70] [2018-08-10 16:50:07,214] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00003a70] [2018-08-10 16:50:07,215] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00003a70] [2018-08-10 16:50:07,284] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12973 )
  INFO root [0x00003a70] [2018-08-10 16:50:07,284] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12973, SOMAXCONN=5.
  INFO root [0x00003a70] [2018-08-10 16:50:07,285] - server-configs:
  INFO root [0x00003a70] [2018-08-10 16:50:07,285] - 	gameUpdateHertz : 10
  INFO root [0x00003a70] [2018-08-10 16:50:07,285] - 	defaultViewRadius : 80
  INFO root [0x00003a70] [2018-08-10 16:50:07,285] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003a70] [2018-08-10 16:50:07,285] - 	entryScriptFile : kbemain
  INFO root [0x00003a70] [2018-08-10 16:50:07,285] - 	internalAddr : 10.139.89.70:12973
  INFO root [0x00003a70] [2018-08-10 16:50:07,286] - 	componentID : 8001
  INFO root [0x00003a70] [2018-08-10 16:50:07,604] - Components::findLogger: found logger, addr:10.139.89.70:12968
  INFO root [0x00003a70] [2018-08-10 16:50:07,604] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00003a70] [2018-08-10 16:50:07,604] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003a70] [2018-08-10 16:50:07,622] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 17088 ----
  INFO root [0x00003a70] [2018-08-10 16:50:07,624] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00003a70] [2018-08-10 16:50:07,624] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003a70] [2018-08-10 16:50:07,624] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,803] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,804] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,804] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,810] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,811] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,811] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,812] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003a70] [2018-08-10 16:50:07,891] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003a70] [2018-08-10 16:50:07,979] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003a70] [2018-08-10 16:50:07,979] - Script::install(): KBExtra is successfully!
  INFO root [0x00003a70] [2018-08-10 16:50:08,049] - TelnetServer server is running on port 50000
  INFO root [0x00003a70] [2018-08-10 16:50:08,760] - ---- cellapp is running ----
 DEBUG root [0x00003a70] [2018-08-10 16:50:08,793] - Components::process(): Request for the process of identity...
  WARN root [0x00003a70] [2018-08-10 16:50:15,218] - Forwarding logs to logger[10.139.89.70:12968/0/0/0]...
 ERROR root [0x00003a70] [2018-08-10 16:51:52,844] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003a70] [2018-08-10 16:51:52,846] - The following logs sent to logger failed:
  WARN root [0x00003a70] [2018-08-10 16:51:52,846] - ==> [2018-08-10 16:51:52 829] TCPPacketReceiver::processPendingEvents(10.139.89.70:12968): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a70] [2018-08-10 16:51:52,847] - ==> [2018-08-10 16:51:52 844] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003a70] [2018-08-10 16:51:53,104] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12969): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a70] [2018-08-10 16:51:53,123] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003a70] [2018-08-10 16:51:53,143] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003a70] [2018-08-10 16:51:53,143] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003a70] [2018-08-10 16:51:53,144] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,144] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,145] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,174] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,175] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,175] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,175] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,175] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,175] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,175] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,176] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003a70] [2018-08-10 16:51:53,207] - Script::uninstall(): is successfully!
 DEBUG root [0x00003a70] [2018-08-10 16:51:53,207] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003a70] [2018-08-10 16:51:53,508] - ThreadPool::destroy(): waiting for thread(2)[0x1eda128,0x1ed99d8,], try=1
  INFO root [0x000033fc] [2018-08-10 16:51:56,939] - 
  INFO root [0x000033fc] [2018-08-10 16:51:56,969] - -----------------------------------------------------------------------------------------


  INFO root [0x000033fc] [2018-08-10 16:51:56,971] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x000033fc] [2018-08-10 16:51:56,972] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x000033fc] [2018-08-10 16:51:56,972] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x000033fc] [2018-08-10 16:51:57,037] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:13054 )
  INFO root [0x000033fc] [2018-08-10 16:51:57,038] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:13054, SOMAXCONN=5.
  INFO root [0x000033fc] [2018-08-10 16:51:57,038] - server-configs:
  INFO root [0x000033fc] [2018-08-10 16:51:57,038] - 	gameUpdateHertz : 10
  INFO root [0x000033fc] [2018-08-10 16:51:57,038] - 	defaultViewRadius : 80
  INFO root [0x000033fc] [2018-08-10 16:51:57,038] - 	defaultViewHysteresisArea : 5
  INFO root [0x000033fc] [2018-08-10 16:51:57,039] - 	entryScriptFile : kbemain
  INFO root [0x000033fc] [2018-08-10 16:51:57,039] - 	internalAddr : 10.139.89.70:13054
  INFO root [0x000033fc] [2018-08-10 16:51:57,039] - 	componentID : 8001
  INFO root [0x000033fc] [2018-08-10 16:51:58,565] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 2104 ----
  INFO root [0x000033fc] [2018-08-10 16:51:58,568] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x000033fc] [2018-08-10 16:51:58,574] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000033fc] [2018-08-10 16:51:58,574] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,835] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,835] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,836] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,874] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,875] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,875] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,876] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000033fc] [2018-08-10 16:51:58,973] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000033fc] [2018-08-10 16:51:59,073] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000033fc] [2018-08-10 16:51:59,073] - Script::install(): KBExtra is successfully!
  INFO root [0x000033fc] [2018-08-10 16:51:59,170] - TelnetServer server is running on port 50000
  INFO root [0x000033fc] [2018-08-10 16:51:59,921] - ---- cellapp is running ----
 DEBUG root [0x000033fc] [2018-08-10 16:51:59,921] - Components::process(): Request for the process of identity...
  WARN root [0x000033fc] [2018-08-10 16:52:06,213] - EntityApp::checkTickPeriod: tick took 6292% (6.29 seconds)!
  INFO root [0x000033fc] [2018-08-10 16:52:07,222] - Components::findComponents: find logger(1)...
  INFO root [0x000033fc] [2018-08-10 16:52:07,314] - Components::findComponents: found logger, addr:10.139.89.70:13049
  INFO root [0x000033fc] [2018-08-10 16:52:07,314] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000033fc] [2018-08-10 16:52:07,314] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000033fc] [2018-08-10 16:52:07,315] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000033fc] [2018-08-10 16:52:07,421] - Components::findComponents: found dbmgr, addr:10.139.89.70:13051
  INFO root [0x000033fc] [2018-08-10 16:52:07,421] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x000033fc] [2018-08-10 16:52:07,421] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000033fc] [2018-08-10 16:52:07,421] - Components::findComponents: found dbmgr, addr:10.139.89.70:13051
  WARN root [0x000033fc] [2018-08-10 16:52:08,421] - EntityApp::checkTickPeriod: tick took 1299% (1.30 seconds)!
  WARN root [0x000033fc] [2018-08-10 16:52:08,421] - Forwarding logs to logger[10.139.89.70:13049/0/0/0]...
 ERROR root [0x000033fc] [2018-08-10 16:54:25,249] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000033fc] [2018-08-10 16:54:25,253] - The following logs sent to logger failed:
  WARN root [0x000033fc] [2018-08-10 16:54:25,254] - ==> [2018-08-10 16:54:25 238] TCPPacketReceiver::processPendingEvents(10.139.89.70:13049): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000033fc] [2018-08-10 16:54:25,254] - ==> [2018-08-10 16:54:25 251] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000033fc] [2018-08-10 16:54:25,468] - TCPPacketReceiver::processPendingEvents(10.139.89.70:13051): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000033fc] [2018-08-10 16:54:25,480] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000033fc] [2018-08-10 16:54:25,490] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000033fc] [2018-08-10 16:54:25,490] - Shutdowner::onShutdown: shutting down
  INFO root [0x000033fc] [2018-08-10 16:54:25,490] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,491] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,491] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,517] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,518] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,518] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,518] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,518] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,519] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,519] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,519] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000033fc] [2018-08-10 16:54:25,551] - Script::uninstall(): is successfully!
 DEBUG root [0x000033fc] [2018-08-10 16:54:25,551] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000033fc] [2018-08-10 16:54:25,856] - ThreadPool::destroy(): waiting for thread(2)[0x1fe97f8,0x1fe8f08,], try=1
  INFO root [0x00000c70] [2018-08-10 16:54:29,063] - 
  INFO root [0x00000c70] [2018-08-10 16:54:29,081] - -----------------------------------------------------------------------------------------


  INFO root [0x00000c70] [2018-08-10 16:54:29,083] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [0x00000c70] [2018-08-10 16:54:29,083] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [0x00000c70] [2018-08-10 16:54:29,083] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [0x00000c70] [2018-08-10 16:54:29,151] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:13133 )
  INFO root [0x00000c70] [2018-08-10 16:54:29,151] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:13133, SOMAXCONN=5.
  INFO root [0x00000c70] [2018-08-10 16:54:29,151] - server-configs:
  INFO root [0x00000c70] [2018-08-10 16:54:29,151] - 	gameUpdateHertz : 10
  INFO root [0x00000c70] [2018-08-10 16:54:29,152] - 	defaultViewRadius : 80
  INFO root [0x00000c70] [2018-08-10 16:54:29,152] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000c70] [2018-08-10 16:54:29,152] - 	entryScriptFile : kbemain
  INFO root [0x00000c70] [2018-08-10 16:54:29,152] - 	internalAddr : 10.139.89.70:13133
  INFO root [0x00000c70] [2018-08-10 16:54:29,152] - 	componentID : 8001
  INFO root [0x00000c70] [2018-08-10 16:54:29,526] - Components::findLogger: found logger, addr:10.139.89.70:13128
  INFO root [0x00000c70] [2018-08-10 16:54:29,527] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [0x00000c70] [2018-08-10 16:54:29,527] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000c70] [2018-08-10 16:54:29,537] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 84A43618D0FDA160D09DFF78C6735F0A. Config: Debug X86. Built: 23:21:46 May 26 2018. AppID: 8001. UID: 21326. PID: 15904 ----
  INFO root [0x00000c70] [2018-08-10 16:54:29,538] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [0x00000c70] [2018-08-10 16:54:29,538] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000c70] [2018-08-10 16:54:29,539] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,699] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,700] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,700] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,707] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,707] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,708] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,709] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000c70] [2018-08-10 16:54:29,768] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000c70] [2018-08-10 16:54:29,873] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:59) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000c70] [2018-08-10 16:54:29,873] - Script::install(): KBExtra is successfully!
  INFO root [0x00000c70] [2018-08-10 16:54:29,986] - TelnetServer server is running on port 50000
  INFO root [0x00000c70] [2018-08-10 16:54:30,827] - ---- cellapp is running ----
 DEBUG root [0x00000c70] [2018-08-10 16:54:30,871] - Components::process(): Request for the process of identity...
  WARN root [0x00000c70] [2018-08-10 16:54:37,524] - Forwarding logs to logger[10.139.89.70:13128/0/0/0]...
 ERROR root [0x00000c70] [2018-08-10 17:15:11,081] - Components::removeComponentByChannel: baseappmgr : 5000, Abnormal exit! errorno=10054
 ERROR root [0x00000c70] [2018-08-10 17:15:11,164] - 10.139.89.70:13130: TCPPacketSender::processSend(): Exception occurred: REASON_CLIENT_DISCONNECTED , errno: 10054
 ERROR root [0x00000c70] [2018-08-10 17:15:11,175] - Components::removeComponentByChannel: cellappmgr : 6000, Abnormal exit! errorno=10054
  INFO root [0x00000c70] [2018-08-10 17:15:11,211] - The following logs sent to logger failed:
  WARN root [0x00000c70] [2018-08-10 17:15:11,211] - ==> [2018-08-10 17:15:11 208] TCPPacketReceiver::processPendingEvents(10.139.89.70:13128): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x00000c70] [2018-08-10 17:15:11,212] - ==> [2018-08-10 17:15:11 210] Components::removeComponentByChannel: logger : 2000, Normal exit!
  WARN root [0x00000c70] [2018-08-10 17:15:11,213] - TCPPacketReceiver::processPendingEvents(10.139.89.70:13158): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  WARN root [0x00000c70] [2018-08-10 17:15:11,228] - TCPPacketReceiver::processPendingEvents(10.139.89.70:13129): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x00000c70] [2018-08-10 17:15:11,230] - Components::removeComponentByChannel: dbmgr : 4000, Normal exit!
  WARN root [0x00000c70] [2018-08-10 17:15:11,230] - ServerApp::shutDown:  In shuttingdown!
  WARN root [0x00000c70] [2018-08-10 17:15:11,231] - TCPPacketReceiver::processPendingEvents(10.139.89.70:13131): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x00000c70] [2018-08-10 17:15:11,233] - Components::removeComponentByChannel: baseapp : 7001, Normal exit!
  INFO root [0x00000c70] [2018-08-10 17:15:12,204] - Shutdowner::onShutdown: shutting down
  INFO root [0x00000c70] [2018-08-10 17:15:13,205] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,205] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,205] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,222] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000c70] [2018-08-10 17:15:13,231] - Script::uninstall(): is successfully!
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,231] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00000c70] [2018-08-10 17:15:13,532] - ThreadPool::destroy(): waiting for thread(2)[0x1c7a528,0x1c7ac10,], try=1
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,934] - TPThread::~TPThread(): 0x1c7a528
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,934] - TPThread::~TPThread(): 0x1c7ac10
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,934] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,935] - Bundle::destroyObjPool(): size 8.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,935] - Channel::destroyObjPool(): size 16.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,935] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,935] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,936] - EndPoint::destroyObjPool(): size 16.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,936] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,936] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00000c70] [2018-08-10 17:15:13,936] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x00000c70] [2018-08-10 17:15:13,936] - cellapp(8001) has shut down.
  INFO root [0x00000c70] [2018-08-10 17:15:14,937] - EventDispatcher()::~EventDispatcher: Num timers = 1
