 ERROR root [0x00001a14] [2018-05-11 00:07:57,504] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001a14] [2018-05-11 00:07:57,567] - The following logs sent to logger failed:
  WARN root [0x00001a14] [2018-05-11 00:07:57,568] - ==> [2018-05-11 00:07:57 499] TCPPacketReceiver::processPendingEvents(10.1.9.9:30870): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001a14] [2018-05-11 00:07:57,568] - ==> [2018-05-11 00:07:57 566] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001a14] [2018-05-11 00:07:57,657] - TCPPacketReceiver::processPendingEvents(10.1.9.9:30873): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001a14] [2018-05-11 00:07:57,660] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001a14] [2018-05-11 00:07:57,663] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001a14] [2018-05-11 00:07:57,664] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001a14] [2018-05-11 00:07:57,664] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,666] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,666] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,702] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,702] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,703] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,703] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,703] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,704] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,704] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,704] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001a14] [2018-05-11 00:07:57,739] - Script::uninstall(): is successfully!
 DEBUG root [0x00001a14] [2018-05-11 00:07:57,739] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001a14] [2018-05-11 00:07:58,044] - ThreadPool::destroy(): waiting for thread(2)[0x466d4b0,0x466d650,], try=1
