  INFO root [2018-08-07 14:31:05,747] - 
  INFO root [2018-08-07 14:31:05,748] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 14:31:05,749] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 14:31:05,749] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 14:31:05,750] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 14:31:05,757] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 14:31:05,757] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 14:31:05,762] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:9322 )
  INFO root [2018-08-07 14:31:05,762] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:9322, SOMAXCONN=128.
  INFO root [2018-08-07 14:31:05,762] - server-configs:
  INFO root [2018-08-07 14:31:05,762] - 	internalAddr : 10.139.89.70:9322
  INFO root [2018-08-07 14:31:05,763] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 14:31:05,763] - 	componentID : 9000
  INFO root [2018-08-07 14:31:06,126] - Components::findLogger: found logger, addr:10.139.89.70:9259
  INFO root [2018-08-07 14:31:06,127] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:31:06,127] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:31:06,133] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 18664 ----
  INFO root [2018-08-07 14:31:06,133] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 14:31:06,134] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 14:31:06,134] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 14:31:06,268] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:31:06,268] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:31:06,268] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:31:06,272] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:31:06,272] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:31:06,273] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:31:06,273] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:31:06,313] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:31:06,355] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 14:31:06,356] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 14:31:06,387] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 14:31:06,387] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 14:31:06,702] - ---- loginapp is running ----
 DEBUG root [2018-08-07 14:31:06,702] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 14:31:12,955] - Forwarding logs to logger[10.139.89.70:9259/0/0/0]...
  INFO root [2018-08-07 14:49:51,353] - 
  INFO root [2018-08-07 14:49:51,396] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 14:49:51,399] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 14:49:51,399] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 14:49:51,400] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 14:49:51,457] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 14:49:51,458] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 14:49:51,468] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:9925 )
  INFO root [2018-08-07 14:49:51,468] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:9925, SOMAXCONN=128.
  INFO root [2018-08-07 14:49:51,468] - server-configs:
  INFO root [2018-08-07 14:49:51,468] - 	internalAddr : 10.139.89.70:9925
  INFO root [2018-08-07 14:49:51,468] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 14:49:51,469] - 	componentID : 9000
  WARN root [2018-08-07 14:49:52,234] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20710, errorno=10048
  INFO root [2018-08-07 14:49:52,238] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 11776 ----
  INFO root [2018-08-07 14:49:52,239] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 14:49:52,239] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 14:49:52,239] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 14:49:52,368] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:49:52,368] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:49:52,369] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:49:52,372] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:49:52,372] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:49:52,372] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:49:52,373] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:49:52,406] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:49:52,440] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 14:49:52,440] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 14:49:52,442] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 14:49:52,443] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 14:49:52,744] - ---- loginapp is running ----
 DEBUG root [2018-08-07 14:49:52,744] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 14:49:59,923] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 14:49:59,996] - Components::findComponents: found logger, addr:10.139.89.70:9921
  INFO root [2018-08-07 14:49:59,996] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:49:59,996] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:49:59,997] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 14:50:00,100] - Components::findComponents: found dbmgr, addr:10.139.89.70:9927
  INFO root [2018-08-07 14:50:00,101] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:50:00,101] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:50:00,101] - Components::findComponents: found dbmgr, addr:10.139.89.70:9927
  WARN root [2018-08-07 14:50:01,102] - Forwarding logs to logger[10.139.89.70:9921/0/0/0]...
 ERROR root [2018-08-07 14:51:03,532] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 14:51:03,553] - The following logs sent to logger failed:
  WARN root [2018-08-07 14:51:03,554] - ==> [2018-08-07 14:51:03 532] TCPPacketReceiver::processPendingEvents(10.139.89.70:9921): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 14:51:03,554] - ==> [2018-08-07 14:51:03 533] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 14:51:03,726] - TCPPacketReceiver::processPendingEvents(10.139.89.70:9927): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 14:51:03,736] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 14:51:03,743] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 14:51:03,743] - onLoginAppShutDown()
  INFO root [2018-08-07 14:51:03,743] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 14:51:03,743] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 14:51:03,744] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:51:03,744] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:51:03,744] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:51:03,744] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:51:03,745] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:51:03,745] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:51:03,745] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:51:03,745] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:51:03,775] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 14:51:03,779] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 14:51:04,080] - ThreadPool::destroy(): waiting for thread(2)[0x129aa8,0x1292f0,], try=1
  INFO root [2018-08-07 14:51:24,467] - 
  INFO root [2018-08-07 14:51:24,521] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 14:51:24,526] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 14:51:24,527] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 14:51:24,527] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 14:51:24,603] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 14:51:24,603] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 14:51:24,616] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10037 )
  INFO root [2018-08-07 14:51:24,617] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10037, SOMAXCONN=128.
  INFO root [2018-08-07 14:51:24,617] - server-configs:
  INFO root [2018-08-07 14:51:24,617] - 	internalAddr : 10.139.89.70:10037
  INFO root [2018-08-07 14:51:24,617] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 14:51:24,617] - 	componentID : 9000
  INFO root [2018-08-07 14:51:26,525] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 12352 ----
  INFO root [2018-08-07 14:51:26,526] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 14:51:26,526] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 14:51:26,526] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 14:51:26,675] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:51:26,675] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:51:26,676] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:51:26,681] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:51:26,682] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:51:26,682] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:51:26,683] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:51:26,742] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:51:26,803] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 14:51:26,804] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 14:51:26,808] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 14:51:26,808] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 14:51:27,384] - ---- loginapp is running ----
 DEBUG root [2018-08-07 14:51:27,385] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 14:51:30,879] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20918, errorno=10048
  INFO root [2018-08-07 14:51:34,968] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 14:51:35,032] - Components::findComponents: found logger, addr:10.139.89.70:10043
  INFO root [2018-08-07 14:51:35,032] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:51:35,032] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:51:35,034] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-08-07 14:51:36,137] - Forwarding logs to logger[10.139.89.70:10043/0/0/0]...
 ERROR root [2018-08-07 14:52:06,660] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 14:52:06,662] - The following logs sent to logger failed:
  WARN root [2018-08-07 14:52:06,662] - ==> [2018-08-07 14:52:06 660] TCPPacketReceiver::processPendingEvents(10.139.89.70:10043): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 14:52:06,663] - ==> [2018-08-07 14:52:06 661] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 14:53:24,713] - 
  INFO root [2018-08-07 14:53:24,744] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 14:53:24,747] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 14:53:24,747] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 14:53:24,748] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 14:53:24,909] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 14:53:24,909] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 14:53:24,944] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10123 )
  INFO root [2018-08-07 14:53:24,945] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10123, SOMAXCONN=128.
  INFO root [2018-08-07 14:53:24,945] - server-configs:
  INFO root [2018-08-07 14:53:24,945] - 	internalAddr : 10.139.89.70:10123
  INFO root [2018-08-07 14:53:24,946] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 14:53:24,946] - 	componentID : 9000
  INFO root [2018-08-07 14:53:25,649] - Components::findLogger: found logger, addr:10.139.89.70:10121
  INFO root [2018-08-07 14:53:25,649] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:53:25,649] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:53:25,655] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13968 ----
  INFO root [2018-08-07 14:53:25,656] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 14:53:25,656] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 14:53:25,656] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 14:53:25,790] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:53:25,791] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:53:25,792] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:53:25,796] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:53:25,796] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:53:25,797] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:53:25,797] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:53:25,831] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:53:25,867] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 14:53:25,867] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 14:53:25,869] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 14:53:25,869] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 14:53:26,189] - ---- loginapp is running ----
 DEBUG root [2018-08-07 14:53:26,190] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 14:53:32,347] - Forwarding logs to logger[10.139.89.70:10121/0/0/0]...
 ERROR root [2018-08-07 14:58:00,619] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 14:58:00,630] - The following logs sent to logger failed:
  WARN root [2018-08-07 14:58:00,630] - ==> [2018-08-07 14:58:00 618] TCPPacketReceiver::processPendingEvents(10.139.89.70:10121): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 14:58:00,631] - ==> [2018-08-07 14:58:00 620] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 14:58:00,751] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10122): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 14:58:00,760] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 14:58:00,767] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 14:58:00,768] - onLoginAppShutDown()
  INFO root [2018-08-07 14:58:00,769] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 14:58:00,769] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 14:58:00,769] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:58:00,770] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:58:00,770] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:58:00,770] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:58:00,770] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:58:00,770] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:58:00,771] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:58:00,771] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:58:00,803] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 14:58:00,803] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 14:58:01,104] - ThreadPool::destroy(): waiting for thread(2)[0x2539968,0x2539bd8,], try=1
  INFO root [2018-08-07 14:58:08,151] - 
  INFO root [2018-08-07 14:58:08,152] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 14:58:08,153] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 14:58:08,153] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 14:58:08,153] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 14:58:08,161] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 14:58:08,162] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 14:58:08,167] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10224 )
  INFO root [2018-08-07 14:58:08,167] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10224, SOMAXCONN=128.
  INFO root [2018-08-07 14:58:08,167] - server-configs:
  INFO root [2018-08-07 14:58:08,167] - 	internalAddr : 10.139.89.70:10224
  INFO root [2018-08-07 14:58:08,167] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 14:58:08,168] - 	componentID : 9000
  INFO root [2018-08-07 14:58:10,062] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 9076 ----
  INFO root [2018-08-07 14:58:10,063] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 14:58:10,064] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 14:58:10,064] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 14:58:10,212] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 14:58:10,213] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 14:58:10,213] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 14:58:10,219] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 14:58:10,220] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 14:58:10,220] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 14:58:10,221] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 14:58:10,316] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 14:58:10,388] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 14:58:10,388] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 14:58:10,392] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 14:58:10,393] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 14:58:11,195] - ---- loginapp is running ----
 DEBUG root [2018-08-07 14:58:11,195] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 14:58:18,412] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 14:58:18,443] - Components::findComponents: found logger, addr:10.139.89.70:10231
  INFO root [2018-08-07 14:58:18,443] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:58:18,443] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:58:18,444] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 14:58:18,548] - Components::findComponents: found dbmgr, addr:10.139.89.70:10228
  INFO root [2018-08-07 14:58:18,548] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 14:58:18,548] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 14:58:18,548] - Components::findComponents: found dbmgr, addr:10.139.89.70:10228
  WARN root [2018-08-07 14:58:19,548] - Forwarding logs to logger[10.139.89.70:10231/0/0/0]...
 ERROR root [2018-08-07 15:02:52,803] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:02:52,805] - The following logs sent to logger failed:
  WARN root [2018-08-07 15:02:52,806] - ==> [2018-08-07 15:02:52 797] TCPPacketReceiver::processPendingEvents(10.139.89.70:10231): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:02:52,806] - ==> [2018-08-07 15:02:52 803] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 15:02:52,971] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10228): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:02:52,990] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:02:52,993] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 15:02:52,993] - onLoginAppShutDown()
  INFO root [2018-08-07 15:02:52,994] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 15:02:52,994] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 15:02:52,994] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:02:52,995] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:02:52,995] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:02:52,995] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:02:52,995] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:02:52,995] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:02:52,995] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:02:52,996] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:02:53,030] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 15:02:53,031] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 15:02:53,332] - ThreadPool::destroy(): waiting for thread(2)[0x2179d10,0x2179078,], try=1
 DEBUG root [2018-08-07 15:02:53,736] - TPThread::~TPThread(): 0x2179d10
 DEBUG root [2018-08-07 15:02:53,736] - TPThread::~TPThread(): 0x2179078
 DEBUG root [2018-08-07 15:02:53,736] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-07 15:02:53,759] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-07 15:02:53,759] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-07 15:02:53,759] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-07 15:02:53,759] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:02:53,760] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-07 15:02:53,760] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:02:53,760] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:02:53,760] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-07 15:02:53,760] - loginapp(9000) has shut down.
  INFO root [2018-08-07 15:04:28,748] - 
  INFO root [2018-08-07 15:04:28,772] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 15:04:28,784] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 15:04:28,784] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 15:04:28,785] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 15:04:28,930] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 15:04:28,946] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 15:04:28,968] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10330 )
  INFO root [2018-08-07 15:04:28,968] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10330, SOMAXCONN=128.
  INFO root [2018-08-07 15:04:28,968] - server-configs:
  INFO root [2018-08-07 15:04:28,969] - 	internalAddr : 10.139.89.70:10330
  INFO root [2018-08-07 15:04:28,969] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 15:04:28,969] - 	componentID : 9000
  INFO root [2018-08-07 15:04:31,034] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14364 ----
  INFO root [2018-08-07 15:04:31,034] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 15:04:31,035] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 15:04:31,035] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 15:04:31,195] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:04:31,196] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:04:31,196] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:04:31,203] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:04:31,203] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:04:31,204] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:04:31,205] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:04:31,263] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:04:31,326] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 15:04:31,326] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 15:04:31,330] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 15:04:31,330] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 15:04:31,878] - ---- loginapp is running ----
 DEBUG root [2018-08-07 15:04:31,878] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 15:04:39,130] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 15:04:39,154] - Components::findComponents: found logger, addr:10.139.89.70:10333
  INFO root [2018-08-07 15:04:39,154] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:04:39,155] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:04:39,156] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 15:04:39,259] - Components::findComponents: found dbmgr, addr:10.139.89.70:10328
  INFO root [2018-08-07 15:04:39,259] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:04:39,259] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:04:39,260] - Components::findComponents: found dbmgr, addr:10.139.89.70:10328
  WARN root [2018-08-07 15:04:40,260] - Forwarding logs to logger[10.139.89.70:10333/0/0/0]...
 ERROR root [2018-08-07 15:14:01,803] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:14:01,805] - The following logs sent to logger failed:
  WARN root [2018-08-07 15:14:01,805] - ==> [2018-08-07 15:14:01 782] TCPPacketReceiver::processPendingEvents(10.139.89.70:10333): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:14:01,806] - ==> [2018-08-07 15:14:01 804] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 15:14:02,032] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10328): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:14:02,050] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:14:02,068] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 15:14:02,114] - onLoginAppShutDown()
  INFO root [2018-08-07 15:14:02,115] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 15:14:02,115] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 15:14:02,116] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:14:02,117] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:14:02,117] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:14:02,117] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:14:02,118] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:14:02,118] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:14:02,118] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:14:02,118] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:14:02,200] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 15:14:02,201] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 15:14:02,503] - ThreadPool::destroy(): waiting for thread(2)[0x23d26d8,0x23d2398,], try=1
 DEBUG root [2018-08-07 15:14:02,930] - TPThread::~TPThread(): 0x23d26d8
 DEBUG root [2018-08-07 15:14:02,936] - TPThread::~TPThread(): 0x23d2398
 DEBUG root [2018-08-07 15:14:02,937] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-07 15:14:02,985] - Bundle::destroyObjPool(): size 12.
 DEBUG root [2018-08-07 15:14:02,985] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-07 15:14:02,986] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-07 15:14:02,986] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:14:02,986] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-07 15:14:02,986] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:14:02,986] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:14:02,987] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-07 15:14:02,987] - loginapp(9000) has shut down.
  INFO root [2018-08-07 15:14:06,204] - 
  INFO root [2018-08-07 15:14:06,206] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 15:14:06,208] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 15:14:06,208] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 15:14:06,208] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 15:14:06,217] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 15:14:06,217] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 15:14:06,233] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10596 )
  INFO root [2018-08-07 15:14:06,234] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10596, SOMAXCONN=128.
  INFO root [2018-08-07 15:14:06,234] - server-configs:
  INFO root [2018-08-07 15:14:06,234] - 	internalAddr : 10.139.89.70:10596
  INFO root [2018-08-07 15:14:06,234] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 15:14:06,234] - 	componentID : 9000
  INFO root [2018-08-07 15:14:08,263] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 17440 ----
  INFO root [2018-08-07 15:14:08,263] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 15:14:08,264] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 15:14:08,264] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 15:14:08,453] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:14:08,454] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:14:08,454] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:14:08,464] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:14:08,464] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:14:08,464] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:14:08,465] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:14:08,533] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:14:08,605] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 15:14:08,606] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 15:14:08,610] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 15:14:08,611] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 15:14:09,076] - ---- loginapp is running ----
 DEBUG root [2018-08-07 15:14:09,077] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 15:14:16,291] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 15:14:16,308] - Components::findComponents: found logger, addr:10.139.89.70:10599
  INFO root [2018-08-07 15:14:16,309] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:14:16,309] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:14:16,310] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 15:14:16,413] - Components::findComponents: found dbmgr, addr:10.139.89.70:10595
  INFO root [2018-08-07 15:14:16,413] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:14:16,413] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:14:16,414] - Components::findComponents: found dbmgr, addr:10.139.89.70:10595
  WARN root [2018-08-07 15:14:17,415] - Forwarding logs to logger[10.139.89.70:10599/0/0/0]...
 ERROR root [2018-08-07 15:17:33,094] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:17:33,101] - The following logs sent to logger failed:
  WARN root [2018-08-07 15:17:33,101] - ==> [2018-08-07 15:17:33 094] TCPPacketReceiver::processPendingEvents(10.139.89.70:10599): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:17:33,102] - ==> [2018-08-07 15:17:33 095] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 15:17:33,343] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10595): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:17:33,358] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:17:33,365] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 15:17:33,370] - onLoginAppShutDown()
  INFO root [2018-08-07 15:17:33,370] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 15:17:33,371] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 15:17:33,372] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:17:33,372] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:17:33,373] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:17:33,373] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:17:33,373] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:17:33,373] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:17:33,373] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:17:33,374] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:17:33,403] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 15:17:33,405] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 15:17:33,705] - ThreadPool::destroy(): waiting for thread(2)[0x740308,0x740780,], try=1
 DEBUG root [2018-08-07 15:17:34,108] - TPThread::~TPThread(): 0x740308
 DEBUG root [2018-08-07 15:17:34,108] - TPThread::~TPThread(): 0x740780
 DEBUG root [2018-08-07 15:17:34,108] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-07 15:17:34,141] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-07 15:17:34,142] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-07 15:17:34,142] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-07 15:17:34,142] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:17:34,143] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-07 15:17:34,143] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:17:34,143] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:17:34,143] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-07 15:17:34,143] - loginapp(9000) has shut down.
  INFO root [2018-08-07 15:17:36,679] - 
  INFO root [2018-08-07 15:17:36,680] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 15:17:36,682] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 15:17:36,682] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 15:17:36,682] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 15:17:36,690] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 15:17:36,691] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 15:17:36,696] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10762 )
  INFO root [2018-08-07 15:17:36,696] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10762, SOMAXCONN=128.
  INFO root [2018-08-07 15:17:36,696] - server-configs:
  INFO root [2018-08-07 15:17:36,696] - 	internalAddr : 10.139.89.70:10762
  INFO root [2018-08-07 15:17:36,697] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 15:17:36,697] - 	componentID : 9000
  WARN root [2018-08-07 15:17:37,538] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20381, errorno=10048
  INFO root [2018-08-07 15:17:37,546] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 12044 ----
  INFO root [2018-08-07 15:17:37,548] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 15:17:37,548] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 15:17:37,548] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 15:17:37,700] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:17:37,701] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:17:37,701] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:17:37,706] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:17:37,707] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:17:37,707] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:17:37,708] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:17:37,786] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:17:37,844] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 15:17:37,844] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 15:17:37,848] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 15:17:37,849] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 15:17:38,565] - ---- loginapp is running ----
 DEBUG root [2018-08-07 15:17:38,593] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 15:17:45,968] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 15:17:46,059] - Components::findComponents: found logger, addr:10.139.89.70:10766
  INFO root [2018-08-07 15:17:46,060] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:17:46,060] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:17:46,062] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 15:17:46,164] - Components::findComponents: found dbmgr, addr:10.139.89.70:10758
  INFO root [2018-08-07 15:17:46,165] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:17:46,165] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:17:46,165] - Components::findComponents: found dbmgr, addr:10.139.89.70:10758
  WARN root [2018-08-07 15:17:47,166] - Forwarding logs to logger[10.139.89.70:10766/0/0/0]...
 ERROR root [2018-08-07 15:22:05,346] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:22:05,349] - The following logs sent to logger failed:
  WARN root [2018-08-07 15:22:05,350] - ==> [2018-08-07 15:22:05 344] TCPPacketReceiver::processPendingEvents(10.139.89.70:10766): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:22:05,350] - ==> [2018-08-07 15:22:05 347] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 15:22:05,491] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:22:05,493] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:22:05,509] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 15:22:05,513] - onLoginAppShutDown()
  INFO root [2018-08-07 15:22:05,514] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 15:22:05,514] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 15:22:05,514] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:22:05,515] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:22:05,515] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:22:05,515] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:22:05,515] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:22:05,516] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:22:05,516] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:22:05,516] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:22:05,547] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 15:22:05,547] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 15:22:05,857] - ThreadPool::destroy(): waiting for thread(2)[0x2149908,0x2149970,], try=1
  INFO root [2018-08-07 15:22:08,742] - 
  INFO root [2018-08-07 15:22:08,757] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 15:22:08,760] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 15:22:08,760] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 15:22:08,760] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 15:22:08,829] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 15:22:08,830] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 15:22:08,851] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10856 )
  INFO root [2018-08-07 15:22:08,852] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10856, SOMAXCONN=128.
  INFO root [2018-08-07 15:22:08,852] - server-configs:
  INFO root [2018-08-07 15:22:08,852] - 	internalAddr : 10.139.89.70:10856
  INFO root [2018-08-07 15:22:08,852] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 15:22:08,852] - 	componentID : 9000
  INFO root [2018-08-07 15:22:10,898] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 3640 ----
  INFO root [2018-08-07 15:22:10,899] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 15:22:10,901] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 15:22:10,901] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 15:22:11,046] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:22:11,053] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:22:11,054] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:22:11,073] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:22:11,074] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:22:11,075] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:22:11,077] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:22:11,189] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:22:11,324] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 15:22:11,324] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 15:22:11,328] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 15:22:11,329] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 15:22:11,883] - ---- loginapp is running ----
 DEBUG root [2018-08-07 15:22:11,883] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 15:22:19,149] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 15:22:19,178] - Components::findComponents: found logger, addr:10.139.89.70:10851
  INFO root [2018-08-07 15:22:19,179] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:22:19,179] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:22:19,180] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 15:22:19,285] - Components::findComponents: found dbmgr, addr:10.139.89.70:10855
  INFO root [2018-08-07 15:22:19,285] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:22:19,285] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:22:19,285] - Components::findComponents: found dbmgr, addr:10.139.89.70:10855
  WARN root [2018-08-07 15:22:20,285] - Forwarding logs to logger[10.139.89.70:10851/0/0/0]...
 ERROR root [2018-08-07 15:24:38,336] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:24:38,346] - The following logs sent to logger failed:
  WARN root [2018-08-07 15:24:38,346] - ==> [2018-08-07 15:24:38 327] TCPPacketReceiver::processPendingEvents(10.139.89.70:10851): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:24:38,347] - ==> [2018-08-07 15:24:38 338] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 15:24:38,473] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10855): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:24:38,478] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:24:38,482] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 15:24:38,487] - onLoginAppShutDown()
  INFO root [2018-08-07 15:24:38,487] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 15:24:38,488] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 15:24:38,491] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:24:38,492] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:24:38,492] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:24:38,493] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:24:38,493] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:24:38,494] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:24:38,494] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:24:38,494] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:24:38,534] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 15:24:38,535] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 15:24:38,836] - ThreadPool::destroy(): waiting for thread(2)[0x22a92e8,0x22a9aa0,], try=1
 DEBUG root [2018-08-07 15:24:39,237] - TPThread::~TPThread(): 0x22a92e8
 DEBUG root [2018-08-07 15:24:39,237] - TPThread::~TPThread(): 0x22a9aa0
 DEBUG root [2018-08-07 15:24:39,237] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-07 15:24:39,261] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-07 15:24:39,261] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-07 15:24:39,271] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-07 15:24:39,271] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:24:39,272] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-07 15:24:39,272] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:24:39,272] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:24:39,272] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-07 15:24:39,272] - loginapp(9000) has shut down.
  INFO root [2018-08-07 15:24:42,098] - 
  INFO root [2018-08-07 15:24:42,121] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 15:24:42,123] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 15:24:42,124] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 15:24:42,124] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 15:24:42,159] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 15:24:42,160] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 15:24:42,166] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:10984 )
  INFO root [2018-08-07 15:24:42,167] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:10984, SOMAXCONN=128.
  INFO root [2018-08-07 15:24:42,167] - server-configs:
  INFO root [2018-08-07 15:24:42,167] - 	internalAddr : 10.139.89.70:10984
  INFO root [2018-08-07 15:24:42,167] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 15:24:42,167] - 	componentID : 9000
  INFO root [2018-08-07 15:24:44,144] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 17900 ----
  INFO root [2018-08-07 15:24:44,145] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 15:24:44,147] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 15:24:44,147] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 15:24:44,305] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:24:44,305] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:24:44,307] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:24:44,313] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:24:44,314] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:24:44,314] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:24:44,315] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:24:44,376] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:24:44,436] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 15:24:44,436] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 15:24:44,442] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 15:24:44,442] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 15:24:45,102] - ---- loginapp is running ----
 DEBUG root [2018-08-07 15:24:45,103] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 15:24:52,322] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 15:24:52,431] - Components::findComponents: found logger, addr:10.139.89.70:10980
  INFO root [2018-08-07 15:24:52,431] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:24:52,431] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:24:52,433] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 15:24:52,538] - Components::findComponents: found dbmgr, addr:10.139.89.70:10977
  INFO root [2018-08-07 15:24:52,539] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:24:52,539] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:24:52,539] - Components::findComponents: found dbmgr, addr:10.139.89.70:10977
  WARN root [2018-08-07 15:24:53,539] - Forwarding logs to logger[10.139.89.70:10980/0/0/0]...
 ERROR root [2018-08-07 15:30:51,636] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:30:51,644] - The following logs sent to logger failed:
  WARN root [2018-08-07 15:30:51,644] - ==> [2018-08-07 15:30:51 621] TCPPacketReceiver::processPendingEvents(10.139.89.70:10980): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:30:51,644] - ==> [2018-08-07 15:30:51 638] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 15:30:51,834] - TCPPacketReceiver::processPendingEvents(10.139.89.70:10977): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 15:30:51,838] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 15:30:51,849] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 15:30:51,850] - onLoginAppShutDown()
  INFO root [2018-08-07 15:30:51,850] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 15:30:51,850] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 15:30:51,851] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:30:51,851] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:30:51,851] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:30:51,852] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:30:51,852] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:30:51,852] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:30:51,852] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:30:51,852] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:30:51,882] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 15:30:51,883] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 15:30:52,184] - ThreadPool::destroy(): waiting for thread(2)[0x89578,0x89440,], try=1
 DEBUG root [2018-08-07 15:30:52,587] - TPThread::~TPThread(): 0x89578
 DEBUG root [2018-08-07 15:30:52,588] - TPThread::~TPThread(): 0x89440
 DEBUG root [2018-08-07 15:30:52,590] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-07 15:30:52,611] - Bundle::destroyObjPool(): size 12.
 DEBUG root [2018-08-07 15:30:52,612] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-07 15:30:52,612] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-07 15:30:52,612] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:30:52,612] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-07 15:30:52,612] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:30:52,612] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 15:30:52,612] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-07 15:30:52,613] - loginapp(9000) has shut down.
  INFO root [2018-08-07 15:37:13,468] - 
  INFO root [2018-08-07 15:37:13,478] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 15:37:13,479] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 15:37:13,482] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 15:37:13,483] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 15:37:13,492] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 15:37:13,492] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 15:37:13,498] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:11138 )
  INFO root [2018-08-07 15:37:13,498] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:11138, SOMAXCONN=128.
  INFO root [2018-08-07 15:37:13,498] - server-configs:
  INFO root [2018-08-07 15:37:13,499] - 	internalAddr : 10.139.89.70:11138
  INFO root [2018-08-07 15:37:13,499] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 15:37:13,499] - 	componentID : 9000
  INFO root [2018-08-07 15:37:15,720] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 18748 ----
  INFO root [2018-08-07 15:37:15,721] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 15:37:15,721] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 15:37:15,721] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 15:37:15,871] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 15:37:15,872] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 15:37:15,873] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 15:37:15,878] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 15:37:15,879] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 15:37:15,879] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 15:37:15,880] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 15:37:15,936] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 15:37:15,997] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 15:37:15,997] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 15:37:16,002] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 15:37:16,002] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 15:37:16,758] - ---- loginapp is running ----
 DEBUG root [2018-08-07 15:37:16,789] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 15:37:24,182] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 15:37:24,232] - Components::findComponents: found logger, addr:10.139.89.70:11140
  INFO root [2018-08-07 15:37:24,232] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:37:24,233] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:37:24,234] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 15:37:24,340] - Components::findComponents: found dbmgr, addr:10.139.89.70:11136
  INFO root [2018-08-07 15:37:24,340] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 15:37:24,340] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 15:37:24,341] - Components::findComponents: found dbmgr, addr:10.139.89.70:11136
  WARN root [2018-08-07 15:37:25,342] - Forwarding logs to logger[10.139.89.70:11140/0/0/0]...
 ERROR root [2018-08-07 16:03:00,289] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:03:00,298] - The following logs sent to logger failed:
  WARN root [2018-08-07 16:03:00,299] - ==> [2018-08-07 16:03:00 286] TCPPacketReceiver::processPendingEvents(10.139.89.70:11140): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:03:00,300] - ==> [2018-08-07 16:03:00 290] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 16:03:00,449] - TCPPacketReceiver::processPendingEvents(10.139.89.70:11136): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:03:00,449] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:03:00,450] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 16:03:00,454] - onLoginAppShutDown()
  INFO root [2018-08-07 16:03:00,454] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 16:03:00,454] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 16:03:00,454] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:03:00,455] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:03:00,455] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:03:00,455] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:03:00,455] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:03:00,455] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:03:00,455] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:03:00,456] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:03:00,502] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 16:03:00,502] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 16:03:00,803] - ThreadPool::destroy(): waiting for thread(2)[0x2409920,0x2409988,], try=1
  INFO root [2018-08-07 16:07:33,034] - 
  INFO root [2018-08-07 16:07:33,045] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 16:07:33,047] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 16:07:33,047] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 16:07:33,047] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 16:07:33,163] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 16:07:33,163] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 16:07:33,207] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:11835 )
  INFO root [2018-08-07 16:07:33,208] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:11835, SOMAXCONN=128.
  INFO root [2018-08-07 16:07:33,208] - server-configs:
  INFO root [2018-08-07 16:07:33,208] - 	internalAddr : 10.139.89.70:11835
  INFO root [2018-08-07 16:07:33,208] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 16:07:33,208] - 	componentID : 9000
  INFO root [2018-08-07 16:07:35,076] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 4416 ----
  INFO root [2018-08-07 16:07:35,076] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 16:07:35,076] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 16:07:35,077] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 16:07:35,212] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:07:35,212] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:07:35,213] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:07:35,217] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:07:35,218] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:07:35,218] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:07:35,219] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:07:35,264] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:07:35,302] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 16:07:35,302] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 16:07:35,305] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 16:07:35,305] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 16:07:35,889] - ---- loginapp is running ----
 DEBUG root [2018-08-07 16:07:35,891] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 16:07:43,206] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 16:07:43,299] - Components::findComponents: found logger, addr:10.139.89.70:11841
  INFO root [2018-08-07 16:07:43,299] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:07:43,299] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:07:43,300] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 16:07:43,405] - Components::findComponents: found dbmgr, addr:10.139.89.70:11836
  INFO root [2018-08-07 16:07:43,406] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:07:43,406] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:07:43,406] - Components::findComponents: found dbmgr, addr:10.139.89.70:11836
  WARN root [2018-08-07 16:07:44,406] - Forwarding logs to logger[10.139.89.70:11841/0/0/0]...
 ERROR root [2018-08-07 16:36:41,543] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:36:41,556] - The following logs sent to logger failed:
  WARN root [2018-08-07 16:36:41,558] - ==> [2018-08-07 16:36:41 526] TCPPacketReceiver::processPendingEvents(10.139.89.70:11841): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:36:41,559] - ==> [2018-08-07 16:36:41 545] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 16:36:41,676] - TCPPacketReceiver::processPendingEvents(10.139.89.70:11836): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:36:41,676] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:36:41,688] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 16:36:41,691] - onLoginAppShutDown()
  INFO root [2018-08-07 16:36:41,691] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 16:36:41,691] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 16:36:41,691] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:36:41,693] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:36:41,693] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:36:41,693] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:36:41,694] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:36:41,694] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:36:41,694] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:36:41,694] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:36:41,732] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 16:36:41,732] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 16:36:42,039] - ThreadPool::destroy(): waiting for thread(2)[0x9e8960,0x9e89c8,], try=1
  INFO root [2018-08-07 16:36:44,676] - 
  INFO root [2018-08-07 16:36:44,678] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 16:36:44,679] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 16:36:44,680] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 16:36:44,681] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 16:36:44,695] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 16:36:44,696] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 16:36:44,706] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12238 )
  INFO root [2018-08-07 16:36:44,707] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12238, SOMAXCONN=128.
  INFO root [2018-08-07 16:36:44,707] - server-configs:
  INFO root [2018-08-07 16:36:44,707] - 	internalAddr : 10.139.89.70:12238
  INFO root [2018-08-07 16:36:44,707] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 16:36:44,707] - 	componentID : 9000
  INFO root [2018-08-07 16:36:45,249] - Components::findLogger: found logger, addr:10.139.89.70:12233
  INFO root [2018-08-07 16:36:45,250] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:36:45,250] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:36:45,255] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 18028 ----
  INFO root [2018-08-07 16:36:45,256] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 16:36:45,256] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 16:36:45,256] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 16:36:45,399] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:36:45,400] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:36:45,400] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:36:45,403] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:36:45,404] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:36:45,404] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:36:45,404] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:36:45,449] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:36:45,494] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 16:36:45,494] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 16:36:45,499] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 16:36:45,499] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 16:36:46,165] - ---- loginapp is running ----
 DEBUG root [2018-08-07 16:36:46,196] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 16:36:52,507] - Forwarding logs to logger[10.139.89.70:12233/0/0/0]...
 ERROR root [2018-08-07 16:51:11,165] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:51:11,167] - The following logs sent to logger failed:
  WARN root [2018-08-07 16:51:11,168] - ==> [2018-08-07 16:51:11 159] TCPPacketReceiver::processPendingEvents(10.139.89.70:12233): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:51:11,168] - ==> [2018-08-07 16:51:11 167] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 16:51:11,274] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12237): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:51:11,279] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:51:11,281] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 16:51:11,282] - onLoginAppShutDown()
  INFO root [2018-08-07 16:51:11,282] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 16:51:11,282] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 16:51:11,283] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:51:11,283] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:51:11,283] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:51:11,284] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:51:11,284] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:51:11,284] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:51:11,284] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:51:11,284] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:51:11,302] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 16:51:11,303] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 16:51:11,604] - ThreadPool::destroy(): waiting for thread(2)[0x23e9148,0x23e9c40,], try=1
  INFO root [2018-08-07 16:51:13,992] - 
  INFO root [2018-08-07 16:51:13,995] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 16:51:14,013] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 16:51:14,013] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 16:51:14,014] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 16:51:14,050] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 16:51:14,051] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 16:51:14,062] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12438 )
  INFO root [2018-08-07 16:51:14,062] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12438, SOMAXCONN=128.
  INFO root [2018-08-07 16:51:14,062] - server-configs:
  INFO root [2018-08-07 16:51:14,062] - 	internalAddr : 10.139.89.70:12438
  INFO root [2018-08-07 16:51:14,062] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 16:51:14,063] - 	componentID : 9000
  INFO root [2018-08-07 16:51:16,025] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 10192 ----
  INFO root [2018-08-07 16:51:16,027] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 16:51:16,028] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 16:51:16,028] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 16:51:16,190] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:51:16,190] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:51:16,191] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:51:16,196] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:51:16,196] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:51:16,196] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:51:16,197] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:51:16,254] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:51:16,328] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 16:51:16,330] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 16:51:16,334] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 16:51:16,334] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 16:51:16,962] - ---- loginapp is running ----
 DEBUG root [2018-08-07 16:51:16,963] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 16:51:24,254] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 16:51:24,353] - Components::findComponents: found logger, addr:10.139.89.70:12445
  INFO root [2018-08-07 16:51:24,353] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:51:24,354] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:51:24,355] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 16:51:24,458] - Components::findComponents: found dbmgr, addr:10.139.89.70:12442
  INFO root [2018-08-07 16:51:24,459] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:51:24,459] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:51:24,459] - Components::findComponents: found dbmgr, addr:10.139.89.70:12442
  WARN root [2018-08-07 16:51:25,459] - Forwarding logs to logger[10.139.89.70:12445/0/0/0]...
 ERROR root [2018-08-07 16:55:17,032] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:55:17,033] - The following logs sent to logger failed:
  WARN root [2018-08-07 16:55:17,033] - ==> [2018-08-07 16:55:17 020] TCPPacketReceiver::processPendingEvents(10.139.89.70:12445): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:55:17,033] - ==> [2018-08-07 16:55:17 033] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 16:55:17,174] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12442): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 16:55:17,179] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 16:55:17,184] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 16:55:17,184] - onLoginAppShutDown()
  INFO root [2018-08-07 16:55:17,184] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 16:55:17,185] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 16:55:17,185] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:55:17,185] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:55:17,185] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:55:17,186] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:55:17,186] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:55:17,186] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:55:17,186] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:55:17,186] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:55:17,208] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 16:55:17,209] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 16:55:17,510] - ThreadPool::destroy(): waiting for thread(2)[0x225a130,0x2259a48,], try=1
  INFO root [2018-08-07 16:55:20,239] - 
  INFO root [2018-08-07 16:55:20,240] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 16:55:20,242] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 16:55:20,242] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 16:55:20,242] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 16:55:20,276] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 16:55:20,277] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 16:55:20,286] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12562 )
  INFO root [2018-08-07 16:55:20,287] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12562, SOMAXCONN=128.
  INFO root [2018-08-07 16:55:20,287] - server-configs:
  INFO root [2018-08-07 16:55:20,287] - 	internalAddr : 10.139.89.70:12562
  INFO root [2018-08-07 16:55:20,287] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 16:55:20,287] - 	componentID : 9000
  INFO root [2018-08-07 16:55:22,280] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 3436 ----
  INFO root [2018-08-07 16:55:22,281] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 16:55:22,281] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 16:55:22,282] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 16:55:22,438] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 16:55:22,439] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 16:55:22,440] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 16:55:22,449] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 16:55:22,450] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 16:55:22,450] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 16:55:22,454] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 16:55:22,516] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 16:55:22,594] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 16:55:22,594] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 16:55:22,598] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 16:55:22,599] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 16:55:23,184] - ---- loginapp is running ----
 DEBUG root [2018-08-07 16:55:23,186] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 16:55:30,397] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 16:55:30,458] - Components::findComponents: found logger, addr:10.139.89.70:12561
  INFO root [2018-08-07 16:55:30,458] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:55:30,458] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:55:30,459] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 16:55:30,564] - Components::findComponents: found dbmgr, addr:10.139.89.70:12555
  INFO root [2018-08-07 16:55:30,564] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 16:55:30,564] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 16:55:30,564] - Components::findComponents: found dbmgr, addr:10.139.89.70:12555
  WARN root [2018-08-07 16:55:31,566] - Forwarding logs to logger[10.139.89.70:12561/0/0/0]...
 ERROR root [2018-08-07 17:03:49,349] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:03:49,352] - The following logs sent to logger failed:
  WARN root [2018-08-07 17:03:49,353] - ==> [2018-08-07 17:03:49 348] TCPPacketReceiver::processPendingEvents(10.139.89.70:12561): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:03:49,353] - ==> [2018-08-07 17:03:49 350] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 17:03:49,471] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12555): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:03:49,473] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:03:49,474] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 17:03:49,475] - onLoginAppShutDown()
  INFO root [2018-08-07 17:03:49,475] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 17:03:49,476] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 17:03:49,476] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:03:49,476] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:03:49,476] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:03:49,476] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:03:49,477] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:03:49,477] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:03:49,477] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:03:49,477] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:03:49,494] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 17:03:49,494] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 17:03:49,795] - ThreadPool::destroy(): waiting for thread(2)[0x7c9968,0x7c9d10,], try=1
  INFO root [2018-08-07 17:03:52,529] - 
  INFO root [2018-08-07 17:03:52,546] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 17:03:52,547] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 17:03:52,547] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 17:03:52,548] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 17:03:52,694] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 17:03:52,695] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 17:03:52,702] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12700 )
  INFO root [2018-08-07 17:03:52,703] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12700, SOMAXCONN=128.
  INFO root [2018-08-07 17:03:52,703] - server-configs:
  INFO root [2018-08-07 17:03:52,704] - 	internalAddr : 10.139.89.70:12700
  INFO root [2018-08-07 17:03:52,704] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 17:03:52,704] - 	componentID : 9000
  INFO root [2018-08-07 17:03:54,771] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 15884 ----
  INFO root [2018-08-07 17:03:54,772] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 17:03:54,773] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 17:03:54,773] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 17:03:54,919] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:03:54,920] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:03:54,920] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:03:54,926] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:03:54,926] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:03:54,928] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:03:54,930] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:03:54,994] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:03:55,066] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 17:03:55,067] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 17:03:55,070] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 17:03:55,071] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 17:03:55,501] - ---- loginapp is running ----
 DEBUG root [2018-08-07 17:03:55,501] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 17:04:02,711] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 17:04:02,788] - Components::findComponents: found logger, addr:10.139.89.70:12704
  INFO root [2018-08-07 17:04:02,788] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:04:02,788] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:04:02,790] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 17:04:02,893] - Components::findComponents: found dbmgr, addr:10.139.89.70:12702
  INFO root [2018-08-07 17:04:02,894] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:04:02,894] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:04:02,894] - Components::findComponents: found dbmgr, addr:10.139.89.70:12702
  WARN root [2018-08-07 17:04:03,894] - Forwarding logs to logger[10.139.89.70:12704/0/0/0]...
 ERROR root [2018-08-07 17:04:12,474] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:04:12,478] - The following logs sent to logger failed:
  INFO root [2018-08-07 17:04:12,479] - ==> [2018-08-07 17:04:11 251] Loginapp::onDbmgrInitCompleted:startGlobalOrder=3, startGroupOrder=1, digest=C48E6C6F36258F6425C9C54E4A42300E.
  INFO root [2018-08-07 17:04:12,479] - ==> [2018-08-07 17:04:12 467] HTTPCBHandler::bind: 10.139.89.70:21103
  WARN root [2018-08-07 17:04:12,479] - ==> [2018-08-07 17:04:12 467] d:\kbe\kbengine-2.0.0-preview3\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 1.22 seconds
  WARN root [2018-08-07 17:04:12,479] - ==> [2018-08-07 17:04:12 472] TCPPacketReceiver::processPendingEvents(10.139.89.70:12704): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:04:12,480] - ==> [2018-08-07 17:04:12 476] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 17:04:12,596] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12702): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:04:12,603] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:04:12,609] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 17:04:12,609] - onLoginAppShutDown()
  INFO root [2018-08-07 17:04:12,609] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 17:04:12,609] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 17:04:12,610] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:04:12,610] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:04:12,610] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:04:12,610] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:04:12,611] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:04:12,611] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:04:12,611] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:04:12,611] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:04:12,645] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 17:04:12,645] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 17:04:12,946] - ThreadPool::destroy(): waiting for thread(2)[0x24b9398,0x24b9400,], try=1
  INFO root [2018-08-07 17:04:15,442] - 
  INFO root [2018-08-07 17:04:15,442] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 17:04:15,443] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 17:04:15,443] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 17:04:15,443] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 17:04:15,452] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 17:04:15,452] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 17:04:15,456] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12733 )
  INFO root [2018-08-07 17:04:15,456] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12733, SOMAXCONN=128.
  INFO root [2018-08-07 17:04:15,456] - server-configs:
  INFO root [2018-08-07 17:04:15,457] - 	internalAddr : 10.139.89.70:12733
  INFO root [2018-08-07 17:04:15,457] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 17:04:15,457] - 	componentID : 9000
  INFO root [2018-08-07 17:04:17,457] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 17368 ----
  INFO root [2018-08-07 17:04:17,461] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 17:04:17,462] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 17:04:17,462] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 17:04:17,793] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:04:17,794] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:04:17,795] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:04:17,813] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:04:17,814] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:04:17,824] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:04:17,825] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:04:17,968] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:04:18,080] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 17:04:18,081] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 17:04:18,086] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 17:04:18,086] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 17:04:18,857] - ---- loginapp is running ----
 DEBUG root [2018-08-07 17:04:18,858] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 17:04:26,105] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 17:04:26,177] - Components::findComponents: found logger, addr:10.139.89.70:12737
  INFO root [2018-08-07 17:04:26,178] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:04:26,178] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:04:26,179] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 17:04:26,283] - Components::findComponents: found dbmgr, addr:10.139.89.70:12731
  INFO root [2018-08-07 17:04:26,283] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:04:26,283] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:04:26,283] - Components::findComponents: found dbmgr, addr:10.139.89.70:12731
  WARN root [2018-08-07 17:04:27,283] - Forwarding logs to logger[10.139.89.70:12737/0/0/0]...
 ERROR root [2018-08-07 17:06:26,272] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:06:26,280] - The following logs sent to logger failed:
  WARN root [2018-08-07 17:06:26,280] - ==> [2018-08-07 17:06:26 271] TCPPacketReceiver::processPendingEvents(10.139.89.70:12737): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:06:26,280] - ==> [2018-08-07 17:06:26 272] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 17:06:26,394] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12731): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:06:26,398] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:06:26,401] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 17:06:26,402] - onLoginAppShutDown()
  INFO root [2018-08-07 17:06:26,402] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 17:06:26,402] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 17:06:26,403] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:06:26,404] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:06:26,404] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:06:26,404] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:06:26,404] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:06:26,405] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:06:26,405] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:06:26,405] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:06:26,429] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 17:06:26,429] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 17:06:26,730] - ThreadPool::destroy(): waiting for thread(2)[0x23b9a10,0x23b9b48,], try=1
  INFO root [2018-08-07 17:06:29,634] - 
  INFO root [2018-08-07 17:06:29,635] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 17:06:29,636] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 17:06:29,636] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 17:06:29,637] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 17:06:29,643] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 17:06:29,644] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 17:06:29,648] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12808 )
  INFO root [2018-08-07 17:06:29,649] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12808, SOMAXCONN=128.
  INFO root [2018-08-07 17:06:29,649] - server-configs:
  INFO root [2018-08-07 17:06:29,649] - 	internalAddr : 10.139.89.70:12808
  INFO root [2018-08-07 17:06:29,649] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 17:06:29,650] - 	componentID : 9000
  INFO root [2018-08-07 17:06:30,120] - Components::findLogger: found logger, addr:10.139.89.70:12801
  INFO root [2018-08-07 17:06:30,120] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:06:30,120] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:06:30,125] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13816 ----
  INFO root [2018-08-07 17:06:30,126] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 17:06:30,126] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 17:06:30,126] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 17:06:30,311] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:06:30,312] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:06:30,313] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:06:30,328] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:06:30,329] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:06:30,329] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:06:30,330] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:06:30,398] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:06:30,496] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 17:06:30,497] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 17:06:30,513] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 17:06:30,514] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 17:06:31,659] - ---- loginapp is running ----
 DEBUG root [2018-08-07 17:06:31,676] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 17:06:38,086] - Forwarding logs to logger[10.139.89.70:12801/0/0/0]...
 ERROR root [2018-08-07 17:07:50,764] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:07:50,772] - The following logs sent to logger failed:
  WARN root [2018-08-07 17:07:50,772] - ==> [2018-08-07 17:07:50 750] TCPPacketReceiver::processPendingEvents(10.139.89.70:12801): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:07:50,772] - ==> [2018-08-07 17:07:50 765] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 17:07:50,888] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12806): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:07:50,897] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:07:50,900] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 17:07:50,901] - onLoginAppShutDown()
  INFO root [2018-08-07 17:07:50,901] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 17:07:50,902] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 17:07:50,903] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:07:50,903] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:07:50,903] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:07:50,903] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:07:50,903] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:07:50,903] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:07:50,904] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:07:50,904] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:07:50,919] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 17:07:50,920] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 17:07:51,220] - ThreadPool::destroy(): waiting for thread(2)[0x1e79078,0x1e79c40,], try=1
  INFO root [2018-08-07 17:07:53,121] - 
  INFO root [2018-08-07 17:07:53,123] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 17:07:53,127] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 17:07:53,128] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 17:07:53,128] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 17:07:53,168] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 17:07:53,168] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 17:07:53,181] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:12919 )
  INFO root [2018-08-07 17:07:53,181] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:12919, SOMAXCONN=128.
  INFO root [2018-08-07 17:07:53,181] - server-configs:
  INFO root [2018-08-07 17:07:53,181] - 	internalAddr : 10.139.89.70:12919
  INFO root [2018-08-07 17:07:53,182] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 17:07:53,182] - 	componentID : 9000
  INFO root [2018-08-07 17:07:55,321] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 104 ----
  INFO root [2018-08-07 17:07:55,321] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 17:07:55,322] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 17:07:55,322] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 17:07:55,492] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:07:55,493] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:07:55,494] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:07:55,501] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:07:55,502] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:07:55,502] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:07:55,503] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:07:55,566] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:07:55,643] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 17:07:55,643] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 17:07:55,646] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 17:07:55,647] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 17:07:56,285] - ---- loginapp is running ----
 DEBUG root [2018-08-07 17:07:56,285] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 17:08:03,607] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 17:08:03,648] - Components::findComponents: found logger, addr:10.139.89.70:12926
  INFO root [2018-08-07 17:08:03,648] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:08:03,648] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:08:03,649] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 17:08:03,753] - Components::findComponents: found dbmgr, addr:10.139.89.70:12922
  INFO root [2018-08-07 17:08:03,753] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:08:03,753] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:08:03,753] - Components::findComponents: found dbmgr, addr:10.139.89.70:12922
  WARN root [2018-08-07 17:08:04,754] - Forwarding logs to logger[10.139.89.70:12926/0/0/0]...
 ERROR root [2018-08-07 17:19:14,521] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:19:14,523] - The following logs sent to logger failed:
  WARN root [2018-08-07 17:19:14,523] - ==> [2018-08-07 17:19:14 516] TCPPacketReceiver::processPendingEvents(10.139.89.70:12926): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:19:14,523] - ==> [2018-08-07 17:19:14 521] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 17:19:14,662] - TCPPacketReceiver::processPendingEvents(10.139.89.70:12922): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:19:14,665] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:19:14,666] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 17:19:14,667] - onLoginAppShutDown()
  INFO root [2018-08-07 17:19:14,667] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 17:19:14,667] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 17:19:14,667] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:19:14,667] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:19:14,668] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:19:14,668] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:19:14,668] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:19:14,668] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:19:14,668] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:19:14,668] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:19:14,693] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 17:19:14,694] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 17:19:14,995] - ThreadPool::destroy(): waiting for thread(2)[0x1d59a58,0x1d58e28,], try=1
  INFO root [2018-08-07 17:19:17,424] - 
  INFO root [2018-08-07 17:19:17,425] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 17:19:17,426] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 17:19:17,426] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 17:19:17,426] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 17:19:17,432] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-07 17:19:17,433] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-07 17:19:17,438] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:13067 )
  INFO root [2018-08-07 17:19:17,438] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:13067, SOMAXCONN=128.
  INFO root [2018-08-07 17:19:17,438] - server-configs:
  INFO root [2018-08-07 17:19:17,439] - 	internalAddr : 10.139.89.70:13067
  INFO root [2018-08-07 17:19:17,439] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-07 17:19:17,439] - 	componentID : 9000
  INFO root [2018-08-07 17:19:19,354] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13044 ----
  INFO root [2018-08-07 17:19:19,360] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 17:19:19,368] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 17:19:19,368] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 17:19:19,514] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:19:19,515] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:19:19,515] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:19:19,520] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:19:19,521] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:19:19,521] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:19:19,522] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:19:19,573] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:19:19,627] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 17:19:19,627] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 17:19:19,631] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 17:19:19,631] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 17:19:20,189] - ---- loginapp is running ----
 DEBUG root [2018-08-07 17:19:20,190] - Components::process(): Request for the process of identity...
  INFO root [2018-08-07 17:19:27,427] - Components::findComponents: find logger(1)...
  INFO root [2018-08-07 17:19:27,478] - Components::findComponents: found logger, addr:10.139.89.70:13071
  INFO root [2018-08-07 17:19:27,478] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:19:27,478] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:19:27,480] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-07 17:19:27,584] - Components::findComponents: found dbmgr, addr:10.139.89.70:13068
  INFO root [2018-08-07 17:19:27,585] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 17:19:27,585] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 17:19:27,585] - Components::findComponents: found dbmgr, addr:10.139.89.70:13068
  WARN root [2018-08-07 17:19:28,586] - Forwarding logs to logger[10.139.89.70:13071/0/0/0]...
 ERROR root [2018-08-07 17:24:01,265] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:24:01,337] - The following logs sent to logger failed:
  WARN root [2018-08-07 17:24:01,337] - ==> [2018-08-07 17:24:01 252] TCPPacketReceiver::processPendingEvents(10.139.89.70:13071): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:24:01,337] - ==> [2018-08-07 17:24:01 266] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 17:24:09,992] - TCPPacketReceiver::processPendingEvents(10.139.89.70:13068): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 17:24:10,021] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 17:24:10,028] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 17:24:10,048] - onLoginAppShutDown()
  INFO root [2018-08-07 17:24:10,048] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 17:24:10,048] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 17:24:10,049] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 17:24:10,049] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 17:24:10,049] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 17:24:10,049] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 17:24:10,050] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 17:24:10,050] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 17:24:10,050] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 17:24:10,050] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 17:24:10,081] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 17:24:10,082] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 17:24:10,383] - ThreadPool::destroy(): waiting for thread(2)[0x9693d0,0x968c18,], try=1
 DEBUG root [2018-08-07 17:24:10,785] - TPThread::~TPThread(): 0x9693d0
 DEBUG root [2018-08-07 17:24:10,785] - TPThread::~TPThread(): 0x968c18
 DEBUG root [2018-08-07 17:24:10,785] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-07 17:24:10,794] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-07 17:24:10,795] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-08-07 17:24:10,795] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-07 17:24:10,795] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 17:24:10,795] - EndPoint::destroyObjPool(): size 14.
 DEBUG root [2018-08-07 17:24:10,795] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 17:24:10,795] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-07 17:24:10,795] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-07 17:24:10,795] - loginapp(9000) has shut down.
  INFO root [2018-08-07 21:07:58,855] - 
  INFO root [2018-08-07 21:07:58,887] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 21:07:58,888] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 21:07:58,889] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 21:07:58,889] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 21:07:58,897] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.104 ( 192.168.1.104:20013 )
  INFO root [2018-08-07 21:07:58,898] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.104:20013, SOMAXCONN=128.
  INFO root [2018-08-07 21:07:58,909] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.104 ( 192.168.1.104:2865 )
  INFO root [2018-08-07 21:07:58,909] - NetworkInterface::initialize(INTERNAL): address 192.168.1.104:2865, SOMAXCONN=128.
  INFO root [2018-08-07 21:07:58,909] - server-configs:
  INFO root [2018-08-07 21:07:58,910] - 	internalAddr : 192.168.1.104:2865
  INFO root [2018-08-07 21:07:58,910] - 	externalAddr : 192.168.1.104:20013
  INFO root [2018-08-07 21:07:58,910] - 	componentID : 9000
  INFO root [2018-08-07 21:07:59,434] - Components::findLogger: found logger, addr:192.168.1.104:2850
  INFO root [2018-08-07 21:07:59,434] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 21:07:59,435] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 21:07:59,454] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 7332 ----
  INFO root [2018-08-07 21:07:59,459] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 21:07:59,467] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 21:07:59,468] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 21:07:59,650] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 21:07:59,650] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 21:07:59,651] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 21:07:59,656] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 21:07:59,656] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 21:07:59,656] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 21:07:59,657] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 21:07:59,724] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 21:07:59,791] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 21:07:59,791] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 21:07:59,795] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 21:07:59,796] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 21:08:00,330] - ---- loginapp is running ----
 DEBUG root [2018-08-07 21:08:00,330] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 21:08:06,521] - Forwarding logs to logger[192.168.1.104:2850/0/0/0]...
 ERROR root [2018-08-07 21:16:46,727] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 21:16:46,730] - The following logs sent to logger failed:
  WARN root [2018-08-07 21:16:46,730] - ==> [2018-08-07 21:16:46 725] TCPPacketReceiver::processPendingEvents(192.168.1.104:2850): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 21:16:46,731] - ==> [2018-08-07 21:16:46 729] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 21:16:46,835] - TCPPacketReceiver::processPendingEvents(192.168.1.104:2852): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 21:16:46,840] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 21:16:46,842] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 21:16:46,842] - onLoginAppShutDown()
  INFO root [2018-08-07 21:16:46,843] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 21:16:46,843] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 21:16:46,844] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 21:16:46,844] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 21:16:46,845] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 21:16:46,845] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 21:16:46,845] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 21:16:46,845] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 21:16:46,845] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 21:16:46,845] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 21:16:46,864] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 21:16:46,865] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 21:16:47,166] - ThreadPool::destroy(): waiting for thread(2)[0x1d42a80,0x1d42b50,], try=1
  INFO root [2018-08-07 21:16:50,317] - 
  INFO root [2018-08-07 21:16:50,318] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-07 21:16:50,319] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-07 21:16:50,319] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-07 21:16:50,319] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-07 21:16:50,333] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.104 ( 192.168.1.104:20013 )
  INFO root [2018-08-07 21:16:50,333] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.104:20013, SOMAXCONN=128.
  INFO root [2018-08-07 21:16:50,338] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.104 ( 192.168.1.104:3190 )
  INFO root [2018-08-07 21:16:50,339] - NetworkInterface::initialize(INTERNAL): address 192.168.1.104:3190, SOMAXCONN=128.
  INFO root [2018-08-07 21:16:50,339] - server-configs:
  INFO root [2018-08-07 21:16:50,339] - 	internalAddr : 192.168.1.104:3190
  INFO root [2018-08-07 21:16:50,339] - 	externalAddr : 192.168.1.104:20013
  INFO root [2018-08-07 21:16:50,339] - 	componentID : 9000
  INFO root [2018-08-07 21:16:50,936] - Components::findLogger: found logger, addr:192.168.1.104:3183
  INFO root [2018-08-07 21:16:50,936] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-07 21:16:50,936] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-07 21:16:50,947] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13952 ----
  INFO root [2018-08-07 21:16:50,954] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-07 21:16:50,955] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-07 21:16:50,955] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-07 21:16:51,239] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 21:16:51,240] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 21:16:51,240] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 21:16:51,254] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 21:16:51,254] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 21:16:51,254] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 21:16:51,255] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 21:16:51,337] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 21:16:51,446] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-07 21:16:51,446] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-07 21:16:51,449] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-07 21:16:51,450] - TelnetServer server is running on port 31000
  INFO root [2018-08-07 21:16:52,393] - ---- loginapp is running ----
 DEBUG root [2018-08-07 21:16:52,397] - Components::process(): Request for the process of identity...
  WARN root [2018-08-07 21:16:58,624] - Forwarding logs to logger[192.168.1.104:3183/0/0/0]...
 ERROR root [2018-08-07 21:51:43,095] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 21:51:43,098] - The following logs sent to logger failed:
  WARN root [2018-08-07 21:51:43,099] - ==> [2018-08-07 21:51:43 092] TCPPacketReceiver::processPendingEvents(192.168.1.104:3183): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 21:51:43,099] - ==> [2018-08-07 21:51:43 096] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-07 21:51:43,254] - TCPPacketReceiver::processPendingEvents(192.168.1.104:3184): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-07 21:51:43,262] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-07 21:51:43,266] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-07 21:51:43,272] - onLoginAppShutDown()
  INFO root [2018-08-07 21:51:43,272] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-07 21:51:43,272] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-07 21:51:43,273] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-07 21:51:43,273] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-07 21:51:43,273] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-07 21:51:43,274] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-07 21:51:43,274] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-07 21:51:43,274] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-07 21:51:43,274] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-07 21:51:43,274] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-07 21:51:43,299] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-07 21:51:43,299] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-07 21:51:43,601] - ThreadPool::destroy(): waiting for thread(2)[0x2159180,0x2159ad8,], try=1
