  INFO root [2018-07-30 16:53:18,177] - 
  INFO root [2018-07-30 16:53:18,177] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-30 16:53:18,179] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-07-30 16:53:18,180] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-07-30 16:53:18,180] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-07-30 16:53:18,188] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20013 )
  INFO root [2018-07-30 16:53:18,189] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20013, SOMAXCONN=128.
  INFO root [2018-07-30 16:53:18,205] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:31480 )
  INFO root [2018-07-30 16:53:18,205] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:31480, SOMAXCONN=128.
  INFO root [2018-07-30 16:53:18,205] - server-configs:
  INFO root [2018-07-30 16:53:18,205] - 	internalAddr : 10.139.66.192:31480
  INFO root [2018-07-30 16:53:18,205] - 	externalAddr : 10.139.66.192:20013
  INFO root [2018-07-30 16:53:18,206] - 	componentID : 9000
  INFO root [2018-07-30 16:53:18,413] - Components::findLogger: found logger, addr:10.139.66.192:31409
  INFO root [2018-07-30 16:53:18,413] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-07-30 16:53:18,414] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-30 16:53:18,431] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 2468 ----
  INFO root [2018-07-30 16:53:18,431] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-07-30 16:53:18,432] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-30 16:53:18,432] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-30 16:53:18,595] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-30 16:53:18,595] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-30 16:53:18,596] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-30 16:53:18,600] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-30 16:53:18,600] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-30 16:53:18,600] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-30 16:53:18,601] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-30 16:53:18,655] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-30 16:53:18,705] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-07-30 16:53:18,706] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-30 16:53:18,731] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-30 16:53:18,732] - TelnetServer server is running on port 31000
  INFO root [2018-07-30 16:53:19,279] - ---- loginapp is running ----
 DEBUG root [2018-07-30 16:53:19,280] - Components::process(): Request for the process of identity...
  WARN root [2018-07-30 16:53:25,530] - Forwarding logs to logger[10.139.66.192:31409/0/0/0]...
  INFO root [2018-07-30 16:54:09,598] - 
  INFO root [2018-07-30 16:54:09,599] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-30 16:54:09,600] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-07-30 16:54:09,600] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-07-30 16:54:09,601] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-07-30 16:54:09,607] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20013 )
  INFO root [2018-07-30 16:54:09,607] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20013, SOMAXCONN=128.
  INFO root [2018-07-30 16:54:09,621] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:31665 )
  INFO root [2018-07-30 16:54:09,621] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:31665, SOMAXCONN=128.
  INFO root [2018-07-30 16:54:09,622] - server-configs:
  INFO root [2018-07-30 16:54:09,622] - 	internalAddr : 10.139.66.192:31665
  INFO root [2018-07-30 16:54:09,622] - 	externalAddr : 10.139.66.192:20013
  INFO root [2018-07-30 16:54:09,622] - 	componentID : 9000
  INFO root [2018-07-30 16:54:09,844] - Components::findLogger: found logger, addr:10.139.66.192:31649
  INFO root [2018-07-30 16:54:09,845] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-07-30 16:54:09,845] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-30 16:54:09,865] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 15136 ----
  INFO root [2018-07-30 16:54:09,866] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-07-30 16:54:09,867] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-30 16:54:09,867] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-30 16:54:10,008] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-30 16:54:10,008] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-30 16:54:10,009] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-30 16:54:10,013] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-30 16:54:10,013] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-30 16:54:10,013] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-30 16:54:10,015] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-30 16:54:10,064] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-30 16:54:10,110] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-07-30 16:54:10,110] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-30 16:54:10,113] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-30 16:54:10,113] - TelnetServer server is running on port 31000
  INFO root [2018-07-30 16:54:10,561] - ---- loginapp is running ----
 DEBUG root [2018-07-30 16:54:10,562] - Components::process(): Request for the process of identity...
  WARN root [2018-07-30 16:54:16,788] - Forwarding logs to logger[10.139.66.192:31649/0/0/0]...
 ERROR root [2018-07-30 16:54:49,690] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-30 16:54:49,691] - The following logs sent to logger failed:
  WARN root [2018-07-30 16:54:49,692] - ==> [2018-07-30 16:54:49 690] TCPPacketReceiver::processPendingEvents(10.139.66.192:31649): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-30 16:54:49,692] - ==> [2018-07-30 16:54:49 690] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-30 16:54:50,192] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-07-30 16:54:52,666] - 
  INFO root [2018-07-30 16:54:52,668] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-30 16:54:52,669] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-07-30 16:54:52,670] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-07-30 16:54:52,670] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-07-30 16:54:52,684] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20013 )
  INFO root [2018-07-30 16:54:52,685] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20013, SOMAXCONN=128.
  INFO root [2018-07-30 16:54:52,703] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:31812 )
  INFO root [2018-07-30 16:54:52,704] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:31812, SOMAXCONN=128.
  INFO root [2018-07-30 16:54:52,704] - server-configs:
  INFO root [2018-07-30 16:54:52,704] - 	internalAddr : 10.139.66.192:31812
  INFO root [2018-07-30 16:54:52,704] - 	externalAddr : 10.139.66.192:20013
  INFO root [2018-07-30 16:54:52,704] - 	componentID : 9000
  INFO root [2018-07-30 16:54:52,939] - Components::findLogger: found logger, addr:10.139.66.192:31804
  INFO root [2018-07-30 16:54:52,939] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-07-30 16:54:52,939] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-30 16:54:52,959] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 17188 ----
  INFO root [2018-07-30 16:54:52,960] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-07-30 16:54:52,961] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-30 16:54:52,962] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-30 16:54:53,105] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-30 16:54:53,106] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-30 16:54:53,106] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-30 16:54:53,112] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-30 16:54:53,112] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-30 16:54:53,113] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-30 16:54:53,114] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-30 16:54:53,171] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-30 16:54:53,217] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-07-30 16:54:53,217] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-30 16:54:53,221] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-30 16:54:53,222] - TelnetServer server is running on port 31000
  INFO root [2018-07-30 16:54:53,677] - ---- loginapp is running ----
 DEBUG root [2018-07-30 16:54:53,677] - Components::process(): Request for the process of identity...
  WARN root [2018-07-30 16:54:59,933] - Forwarding logs to logger[10.139.66.192:31804/0/0/0]...
 ERROR root [2018-07-30 16:55:32,847] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-30 16:55:32,848] - The following logs sent to logger failed:
  WARN root [2018-07-30 16:55:32,848] - ==> [2018-07-30 16:55:32 847] TCPPacketReceiver::processPendingEvents(10.139.66.192:31804): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-30 16:55:32,848] - ==> [2018-07-30 16:55:32 848] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-30 16:55:35,957] - 
  INFO root [2018-07-30 16:55:35,957] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-30 16:55:35,959] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-07-30 16:55:35,960] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-07-30 16:55:35,960] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-07-30 16:55:35,964] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20013 )
  INFO root [2018-07-30 16:55:35,965] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20013, SOMAXCONN=128.
  INFO root [2018-07-30 16:55:35,984] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:31966 )
  INFO root [2018-07-30 16:55:35,985] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:31966, SOMAXCONN=128.
  INFO root [2018-07-30 16:55:35,985] - server-configs:
  INFO root [2018-07-30 16:55:35,985] - 	internalAddr : 10.139.66.192:31966
  INFO root [2018-07-30 16:55:35,986] - 	externalAddr : 10.139.66.192:20013
  INFO root [2018-07-30 16:55:35,986] - 	componentID : 9000
  INFO root [2018-07-30 16:55:36,221] - Components::findLogger: found logger, addr:10.139.66.192:31956
  INFO root [2018-07-30 16:55:36,222] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-07-30 16:55:36,222] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-30 16:55:36,241] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 3648 ----
  INFO root [2018-07-30 16:55:36,242] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-07-30 16:55:36,242] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-30 16:55:36,242] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-30 16:55:36,388] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-30 16:55:36,388] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-30 16:55:36,389] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-30 16:55:36,393] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-30 16:55:36,394] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-30 16:55:36,394] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-30 16:55:36,395] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-30 16:55:36,457] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-30 16:55:36,510] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-07-30 16:55:36,510] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-30 16:55:36,514] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-30 16:55:36,515] - TelnetServer server is running on port 31000
  INFO root [2018-07-30 16:55:37,062] - ---- loginapp is running ----
 DEBUG root [2018-07-30 16:55:37,063] - Components::process(): Request for the process of identity...
  WARN root [2018-07-30 16:55:43,363] - Forwarding logs to logger[10.139.66.192:31956/0/0/0]...
  INFO root [2018-07-30 16:56:01,828] - 
  INFO root [2018-07-30 16:56:01,829] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-30 16:56:01,830] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-07-30 16:56:01,830] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-07-30 16:56:01,831] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-07-30 16:56:01,839] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20013 )
  INFO root [2018-07-30 16:56:01,839] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20013, SOMAXCONN=128.
  INFO root [2018-07-30 16:56:01,853] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:32069 )
  INFO root [2018-07-30 16:56:01,853] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:32069, SOMAXCONN=128.
  INFO root [2018-07-30 16:56:01,853] - server-configs:
  INFO root [2018-07-30 16:56:01,853] - 	internalAddr : 10.139.66.192:32069
  INFO root [2018-07-30 16:56:01,853] - 	externalAddr : 10.139.66.192:20013
  INFO root [2018-07-30 16:56:01,853] - 	componentID : 9000
  INFO root [2018-07-30 16:56:02,097] - Components::findLogger: found logger, addr:10.139.66.192:32060
  INFO root [2018-07-30 16:56:02,097] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-07-30 16:56:02,097] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-30 16:56:02,116] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 160 ----
  INFO root [2018-07-30 16:56:02,116] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-07-30 16:56:02,117] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-30 16:56:02,117] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-30 16:56:02,274] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-30 16:56:02,274] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-30 16:56:02,275] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-30 16:56:02,280] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-30 16:56:02,281] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-30 16:56:02,281] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-30 16:56:02,282] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-30 16:56:02,341] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-30 16:56:02,397] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-07-30 16:56:02,397] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-30 16:56:02,401] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-30 16:56:02,402] - TelnetServer server is running on port 31000
  INFO root [2018-07-30 16:56:03,008] - ---- loginapp is running ----
 DEBUG root [2018-07-30 16:56:03,008] - Components::process(): Request for the process of identity...
  WARN root [2018-07-30 16:56:09,354] - Forwarding logs to logger[10.139.66.192:32060/0/0/0]...
 ERROR root [2018-07-30 17:04:24,673] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-30 17:04:24,692] - The following logs sent to logger failed:
  WARN root [2018-07-30 17:04:24,693] - ==> [2018-07-30 17:04:24 673] TCPPacketReceiver::processPendingEvents(10.139.66.192:32060): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-30 17:04:24,693] - ==> [2018-07-30 17:04:24 674] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
